// Generated by content-src/estudio/build-estudio.mjs — the lessons already written.
import type { Leccion } from '../types'

export const LECCIONES_ESCRITAS: Record<string, () => Promise<Leccion>> = {
  'genesis-12-50': () => import('./genesis-12-50.json').then((m) => m.default as unknown as Leccion),
  'pasion-y-muerte': () => import('./pasion-y-muerte.json').then((m) => m.default as unknown as Leccion),
}
