// Generated by content-src/mapas/build-mapas.mjs — do not edit by hand.
import type { MapaMental, MapasIndice } from './types'

export const MAPAS_SECCIONES: MapasIndice['secciones'] = [
  {
    "id": "panorama",
    "titulo": "Panorama de la Biblia",
    "mapas": [
      {
        "id": "mapa-de-la-biblia",
        "titulo": "La Biblia en un mapa"
      },
      {
        "id": "linea-del-tiempo",
        "titulo": "La línea del tiempo"
      },
      {
        "id": "tipos-de-libros",
        "titulo": "Los tipos de libros"
      },
      {
        "id": "pactos-de-dios",
        "titulo": "Los pactos de Dios"
      },
      {
        "id": "historia-de-la-salvacion",
        "titulo": "La historia de la salvación"
      },
      {
        "id": "jesus-en-toda-la-biblia",
        "titulo": "Jesús en toda la Biblia"
      }
    ]
  },
  {
    "id": "antiguo-testamento",
    "titulo": "Antiguo Testamento",
    "mapas": [
      {
        "id": "genesis",
        "titulo": "Génesis"
      },
      {
        "id": "exodo",
        "titulo": "Éxodo"
      },
      {
        "id": "levitico",
        "titulo": "Levítico"
      },
      {
        "id": "numeros",
        "titulo": "Números"
      },
      {
        "id": "deuteronomio",
        "titulo": "Deuteronomio"
      },
      {
        "id": "josue",
        "titulo": "Josué"
      },
      {
        "id": "jueces",
        "titulo": "Jueces"
      },
      {
        "id": "rut",
        "titulo": "Rut"
      },
      {
        "id": "1-samuel",
        "titulo": "1 Samuel"
      },
      {
        "id": "2-samuel",
        "titulo": "2 Samuel"
      },
      {
        "id": "1-reyes",
        "titulo": "1 Reyes"
      },
      {
        "id": "2-reyes",
        "titulo": "2 Reyes"
      },
      {
        "id": "1-cronicas",
        "titulo": "1 Crónicas"
      },
      {
        "id": "2-cronicas",
        "titulo": "2 Crónicas"
      },
      {
        "id": "esdras",
        "titulo": "Esdras"
      },
      {
        "id": "nehemias",
        "titulo": "Nehemías"
      },
      {
        "id": "ester",
        "titulo": "Ester"
      },
      {
        "id": "job",
        "titulo": "Job"
      },
      {
        "id": "salmos",
        "titulo": "Salmos"
      },
      {
        "id": "proverbios",
        "titulo": "Proverbios"
      },
      {
        "id": "eclesiastes",
        "titulo": "Eclesiastés"
      },
      {
        "id": "cantares",
        "titulo": "Cantares"
      },
      {
        "id": "isaias",
        "titulo": "Isaías"
      },
      {
        "id": "jeremias",
        "titulo": "Jeremías"
      },
      {
        "id": "lamentaciones",
        "titulo": "Lamentaciones"
      },
      {
        "id": "ezequiel",
        "titulo": "Ezequiel"
      },
      {
        "id": "daniel",
        "titulo": "Daniel"
      },
      {
        "id": "oseas",
        "titulo": "Oseas"
      },
      {
        "id": "joel",
        "titulo": "Joel"
      },
      {
        "id": "amos",
        "titulo": "Amós"
      },
      {
        "id": "abdias",
        "titulo": "Abdías"
      },
      {
        "id": "jonas",
        "titulo": "Jonás"
      },
      {
        "id": "miqueas",
        "titulo": "Miqueas"
      },
      {
        "id": "nahum",
        "titulo": "Nahúm"
      },
      {
        "id": "habacuc",
        "titulo": "Habacuc"
      },
      {
        "id": "sofonias",
        "titulo": "Sofonías"
      },
      {
        "id": "hageo",
        "titulo": "Hageo"
      },
      {
        "id": "zacarias",
        "titulo": "Zacarías"
      },
      {
        "id": "malaquias",
        "titulo": "Malaquías"
      }
    ]
  },
  {
    "id": "nuevo-testamento",
    "titulo": "Nuevo Testamento",
    "mapas": [
      {
        "id": "mateo",
        "titulo": "Mateo"
      },
      {
        "id": "marcos",
        "titulo": "Marcos"
      },
      {
        "id": "lucas",
        "titulo": "Lucas"
      },
      {
        "id": "juan",
        "titulo": "Juan"
      },
      {
        "id": "hechos",
        "titulo": "Hechos"
      },
      {
        "id": "romanos",
        "titulo": "Romanos"
      },
      {
        "id": "1-corintios",
        "titulo": "1 Corintios"
      },
      {
        "id": "2-corintios",
        "titulo": "2 Corintios"
      },
      {
        "id": "galatas",
        "titulo": "Gálatas"
      },
      {
        "id": "efesios",
        "titulo": "Efesios"
      },
      {
        "id": "filipenses",
        "titulo": "Filipenses"
      },
      {
        "id": "colosenses",
        "titulo": "Colosenses"
      },
      {
        "id": "1-tesalonicenses",
        "titulo": "1 Tesalonicenses"
      },
      {
        "id": "2-tesalonicenses",
        "titulo": "2 Tesalonicenses"
      },
      {
        "id": "1-timoteo",
        "titulo": "1 Timoteo"
      },
      {
        "id": "2-timoteo",
        "titulo": "2 Timoteo"
      },
      {
        "id": "tito",
        "titulo": "Tito"
      },
      {
        "id": "filemon",
        "titulo": "Filemón"
      },
      {
        "id": "hebreos",
        "titulo": "Hebreos"
      },
      {
        "id": "santiago",
        "titulo": "Santiago"
      },
      {
        "id": "1-pedro",
        "titulo": "1 Pedro"
      },
      {
        "id": "2-pedro",
        "titulo": "2 Pedro"
      },
      {
        "id": "1-juan",
        "titulo": "1 Juan"
      },
      {
        "id": "2-juan",
        "titulo": "2 Juan"
      },
      {
        "id": "3-juan",
        "titulo": "3 Juan"
      },
      {
        "id": "judas",
        "titulo": "Judas"
      },
      {
        "id": "apocalipsis",
        "titulo": "Apocalipsis"
      }
    ]
  }
]

export const MAPAS: Record<string, () => Promise<MapaMental>> = {
  '1-corintios': () => import('./1-corintios.json').then((m) => m.default as unknown as MapaMental),
  '1-cronicas': () => import('./1-cronicas.json').then((m) => m.default as unknown as MapaMental),
  '1-juan': () => import('./1-juan.json').then((m) => m.default as unknown as MapaMental),
  '1-pedro': () => import('./1-pedro.json').then((m) => m.default as unknown as MapaMental),
  '1-reyes': () => import('./1-reyes.json').then((m) => m.default as unknown as MapaMental),
  '1-samuel': () => import('./1-samuel.json').then((m) => m.default as unknown as MapaMental),
  '1-tesalonicenses': () => import('./1-tesalonicenses.json').then((m) => m.default as unknown as MapaMental),
  '1-timoteo': () => import('./1-timoteo.json').then((m) => m.default as unknown as MapaMental),
  '2-corintios': () => import('./2-corintios.json').then((m) => m.default as unknown as MapaMental),
  '2-cronicas': () => import('./2-cronicas.json').then((m) => m.default as unknown as MapaMental),
  '2-juan': () => import('./2-juan.json').then((m) => m.default as unknown as MapaMental),
  '2-pedro': () => import('./2-pedro.json').then((m) => m.default as unknown as MapaMental),
  '2-reyes': () => import('./2-reyes.json').then((m) => m.default as unknown as MapaMental),
  '2-samuel': () => import('./2-samuel.json').then((m) => m.default as unknown as MapaMental),
  '2-tesalonicenses': () => import('./2-tesalonicenses.json').then((m) => m.default as unknown as MapaMental),
  '2-timoteo': () => import('./2-timoteo.json').then((m) => m.default as unknown as MapaMental),
  '3-juan': () => import('./3-juan.json').then((m) => m.default as unknown as MapaMental),
  'abdias': () => import('./abdias.json').then((m) => m.default as unknown as MapaMental),
  'amos': () => import('./amos.json').then((m) => m.default as unknown as MapaMental),
  'apocalipsis': () => import('./apocalipsis.json').then((m) => m.default as unknown as MapaMental),
  'cantares': () => import('./cantares.json').then((m) => m.default as unknown as MapaMental),
  'colosenses': () => import('./colosenses.json').then((m) => m.default as unknown as MapaMental),
  'daniel': () => import('./daniel.json').then((m) => m.default as unknown as MapaMental),
  'deuteronomio': () => import('./deuteronomio.json').then((m) => m.default as unknown as MapaMental),
  'eclesiastes': () => import('./eclesiastes.json').then((m) => m.default as unknown as MapaMental),
  'efesios': () => import('./efesios.json').then((m) => m.default as unknown as MapaMental),
  'esdras': () => import('./esdras.json').then((m) => m.default as unknown as MapaMental),
  'ester': () => import('./ester.json').then((m) => m.default as unknown as MapaMental),
  'exodo': () => import('./exodo.json').then((m) => m.default as unknown as MapaMental),
  'ezequiel': () => import('./ezequiel.json').then((m) => m.default as unknown as MapaMental),
  'filemon': () => import('./filemon.json').then((m) => m.default as unknown as MapaMental),
  'filipenses': () => import('./filipenses.json').then((m) => m.default as unknown as MapaMental),
  'galatas': () => import('./galatas.json').then((m) => m.default as unknown as MapaMental),
  'genesis': () => import('./genesis.json').then((m) => m.default as unknown as MapaMental),
  'habacuc': () => import('./habacuc.json').then((m) => m.default as unknown as MapaMental),
  'hageo': () => import('./hageo.json').then((m) => m.default as unknown as MapaMental),
  'hebreos': () => import('./hebreos.json').then((m) => m.default as unknown as MapaMental),
  'hechos': () => import('./hechos.json').then((m) => m.default as unknown as MapaMental),
  'historia-de-la-salvacion': () => import('./historia-de-la-salvacion.json').then((m) => m.default as unknown as MapaMental),
  'isaias': () => import('./isaias.json').then((m) => m.default as unknown as MapaMental),
  'jeremias': () => import('./jeremias.json').then((m) => m.default as unknown as MapaMental),
  'jesus-en-toda-la-biblia': () => import('./jesus-en-toda-la-biblia.json').then((m) => m.default as unknown as MapaMental),
  'job': () => import('./job.json').then((m) => m.default as unknown as MapaMental),
  'joel': () => import('./joel.json').then((m) => m.default as unknown as MapaMental),
  'jonas': () => import('./jonas.json').then((m) => m.default as unknown as MapaMental),
  'josue': () => import('./josue.json').then((m) => m.default as unknown as MapaMental),
  'juan': () => import('./juan.json').then((m) => m.default as unknown as MapaMental),
  'judas': () => import('./judas.json').then((m) => m.default as unknown as MapaMental),
  'jueces': () => import('./jueces.json').then((m) => m.default as unknown as MapaMental),
  'lamentaciones': () => import('./lamentaciones.json').then((m) => m.default as unknown as MapaMental),
  'levitico': () => import('./levitico.json').then((m) => m.default as unknown as MapaMental),
  'linea-del-tiempo': () => import('./linea-del-tiempo.json').then((m) => m.default as unknown as MapaMental),
  'lucas': () => import('./lucas.json').then((m) => m.default as unknown as MapaMental),
  'malaquias': () => import('./malaquias.json').then((m) => m.default as unknown as MapaMental),
  'mapa-de-la-biblia': () => import('./mapa-de-la-biblia.json').then((m) => m.default as unknown as MapaMental),
  'marcos': () => import('./marcos.json').then((m) => m.default as unknown as MapaMental),
  'mateo': () => import('./mateo.json').then((m) => m.default as unknown as MapaMental),
  'miqueas': () => import('./miqueas.json').then((m) => m.default as unknown as MapaMental),
  'nahum': () => import('./nahum.json').then((m) => m.default as unknown as MapaMental),
  'nehemias': () => import('./nehemias.json').then((m) => m.default as unknown as MapaMental),
  'numeros': () => import('./numeros.json').then((m) => m.default as unknown as MapaMental),
  'oseas': () => import('./oseas.json').then((m) => m.default as unknown as MapaMental),
  'pactos-de-dios': () => import('./pactos-de-dios.json').then((m) => m.default as unknown as MapaMental),
  'proverbios': () => import('./proverbios.json').then((m) => m.default as unknown as MapaMental),
  'romanos': () => import('./romanos.json').then((m) => m.default as unknown as MapaMental),
  'rut': () => import('./rut.json').then((m) => m.default as unknown as MapaMental),
  'salmos': () => import('./salmos.json').then((m) => m.default as unknown as MapaMental),
  'santiago': () => import('./santiago.json').then((m) => m.default as unknown as MapaMental),
  'sofonias': () => import('./sofonias.json').then((m) => m.default as unknown as MapaMental),
  'tipos-de-libros': () => import('./tipos-de-libros.json').then((m) => m.default as unknown as MapaMental),
  'tito': () => import('./tito.json').then((m) => m.default as unknown as MapaMental),
  'zacarias': () => import('./zacarias.json').then((m) => m.default as unknown as MapaMental),
}
