// Guía de escucha: validate and publish.
//   node content-src/escucha/build-escucha.mjs              → validate all, publish if all pass
//   node content-src/escucha/build-escucha.mjs --check <id> → only validate those (publishes nothing)
// Publishes lib/content/escucha/<id>.json + lib/content/escucha/index.ts (a loader per audio).
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseRef, textOf, words, sentences, sameText } from '../biblia-util.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(HERE, '..', '..')
const OUT = path.join(ROOT, 'lib', 'content', 'escucha')
const emit = process.emitWarning
process.emitWarning = (w, ...r) => (/MODULE_TYPELESS|Module type of file/.test(String(w)) || r.some((x) => String(x?.code ?? x).includes('MODULE_TYPELESS')) ? undefined : emit.call(process, w, ...r))
const { LIMITES_ESCUCHA: L } = await import('../../lib/content/escucha/types.ts')
process.emitWarning = emit

const indice = JSON.parse(fs.readFileSync(path.join(HERE, 'indice.json'), 'utf8'))
const ids = new Set(indice.audios.map((a) => a.id))
const maestra = JSON.parse(fs.readFileSync(path.join(ROOT, 'content-src', 'estudio', 'maestra.json'), 'utf8'))
const estudioIds = new Set(maestra.lecciones.map((l) => l.id))
const BLACKLIST = /\bJehová\b/

function validate(file) {
  const e = []
  const g = JSON.parse(fs.readFileSync(file, 'utf8'))
  const txt = (w, s, max) => {
    if (typeof s !== 'string' || !s.trim()) return e.push(`${w}: vazio`)
    if (max && words(s) > max) e.push(`${w}: ${words(s)} palavras (máx. ${max})`)
    for (const f of sentences(s)) if (words(f) > L.fraseMax) e.push(`${w}: frase com ${words(f)} palavras (máx. ${L.fraseMax})`)
    if (BLACKLIST.test(s.replace(/«[^»]*»/g, ''))) e.push(`${w}: use «el Señor» fora de citação`)
  }
  if (g.id !== path.basename(file, '.json')) e.push('id ≠ nome do arquivo')
  if (!ids.has(g.id)) e.push('id não está no indice.json')
  if (!Array.isArray(g.puntos) || g.puntos.length !== L.puntos.cantidad) e.push(`puntos: exatamente ${L.puntos.cantidad}`)
  ;(g.puntos ?? []).forEach((p, i) => txt(`puntos[${i}]`, p, L.puntos.palabras))
  if (!g.versiculo || !parseRef(g.versiculo.referencia)) e.push('versiculo.referencia inválida')
  else {
    const t = textOf(g.versiculo.referencia)
    if (!t) e.push(`versiculo: ${g.versiculo.referencia} não existe no texto`)
    else if (!sameText(t, g.versiculo.texto)) e.push(`versiculo: não é o texto exato da RV1909\n     escrito: ${g.versiculo.texto}\n     RV1909:  ${t}`)
    if (words(g.versiculo.texto ?? '') > L.versiculo) e.push(`versiculo: longo demais (máx. ${L.versiculo})`)
  }
  txt('pregunta', g.pregunta, L.pregunta)
  txt('oracion', g.oracion, L.oracion)
  for (const id of g.estudio ?? []) if (!estudioIds.has(id)) e.push(`estudio: «${id}» não existe na maestra`)
  return e
}

const only = process.argv[2] === '--check' ? process.argv.slice(3) : null
const GDIR = path.join(HERE, 'guias')
fs.mkdirSync(GDIR, { recursive: true })
const files = fs.readdirSync(GDIR).filter((f) => f.endsWith('.json') && (!only || only.includes(f.replace(/\.json$/, ''))))
let failed = 0
for (const f of files) {
  const e = validate(path.join(GDIR, f))
  if (e.length) {
    failed++
    console.log(`✗ ${f}`)
    e.forEach((x) => console.log(`   - ${x}`))
  } else console.log(`OK ${f}`)
}
console.log(`${files.length} guias verificadas, ${failed} com erro.`)
if (only) process.exit(failed ? 1 : 0)
if (failed) {
  console.log('Nada publicado.')
  process.exit(1)
}
fs.mkdirSync(OUT, { recursive: true })
const loaders = []
for (const f of files) {
  fs.copyFileSync(path.join(GDIR, f), path.join(OUT, f))
  const id = f.replace(/\.json$/, '')
  loaders.push(`  '${id}': () => import('./${id}.json').then((m) => m.default as unknown as GuiaEscucha),`)
}
fs.writeFileSync(
  path.join(OUT, 'index.ts'),
  `// Generated by content-src/escucha/build-escucha.mjs — do not edit by hand.\n` +
    `import type { GuiaEscucha } from './types'\n\n` +
    `export const GUIAS_ESCUCHA: Record<string, () => Promise<GuiaEscucha>> = {\n${loaders.join('\n')}\n}\n`,
)
console.log(`Publicado: ${loaders.length} guias de escucha.`)
