// Generated by content-src/estudio/build-estudio.mjs from maestra.json — do not edit by hand.

export interface EstudioEra { id: string; titulo: string; fechas: string | null; frase: string }
export interface EstudioEntrada { id: string; seccion: string; titulo: string; rotulo: string; fecha: string | null }

export const ESTUDIO_ERAS: EstudioEra[] = [
  {
    "id": "introduccion",
    "titulo": "Introducción",
    "fechas": null,
    "frase": "Antes de empezar: cómo leer la Biblia como una sola historia de amor."
  },
  {
    "id": "comienzos",
    "titulo": "Los comienzos",
    "fechas": "Sin fecha",
    "frase": "Dios crea todo bueno, el pecado lo rompe y Dios promete un rescate."
  },
  {
    "id": "patriarcas",
    "titulo": "Los patriarcas",
    "fechas": "c. 2100–1800 a.C.",
    "frase": "Dios elige a la familia de Abraham para bendecir a todos los pueblos."
  },
  {
    "id": "exodo",
    "titulo": "Éxodo y desierto",
    "fechas": "c. 1526–1406 a.C. (debatida)",
    "frase": "Dios libera a Israel de Egipto, le da su Ley y camina con él."
  },
  {
    "id": "conquista",
    "titulo": "Conquista y jueces",
    "fechas": "c. 1406–1050 a.C.",
    "frase": "Israel entra en la tierra, olvida a Dios y Dios lo vuelve a levantar."
  },
  {
    "id": "reino-unido",
    "titulo": "El reino unido",
    "fechas": "c. 1050–930 a.C.",
    "frase": "Saúl, David y Salomón reinan; Dios promete un rey eterno de David."
  },
  {
    "id": "reino-dividido",
    "titulo": "El reino dividido",
    "fechas": "930–586 a.C.",
    "frase": "El reino se parte en dos y los profetas llaman al pueblo a volver."
  },
  {
    "id": "exilio",
    "titulo": "El exilio",
    "fechas": "605–538 a.C.",
    "frase": "Lejos de su tierra, el pueblo descubre que Dios sigue con ellos."
  },
  {
    "id": "regreso",
    "titulo": "El regreso",
    "fechas": "538–c. 430 a.C.",
    "frase": "El pueblo vuelve, reconstruye el templo y los muros, y espera al Mesías."
  },
  {
    "id": "entre-testamentos",
    "titulo": "Entre los Testamentos",
    "fechas": "c. 430–5 a.C.",
    "frase": "Persas, griegos y romanos gobiernan mientras el pueblo espera la promesa."
  },
  {
    "id": "jesus",
    "titulo": "Jesús",
    "fechas": "c. 6 a.C.–30/33 d.C.",
    "frase": "Dios se hace hombre en Jesús, que muere por amor y resucita."
  },
  {
    "id": "iglesia",
    "titulo": "La Iglesia",
    "fechas": "c. 30–95 d.C.",
    "frase": "El Espíritu Santo forma la Iglesia y la buena noticia llega a todos."
  },
  {
    "id": "conclusion",
    "titulo": "Conclusión",
    "fechas": null,
    "frase": "Del jardín perdido a la ciudad de Dios: una sola historia de amor."
  }
]

export const ESTUDIO_LECCIONES: EstudioEntrada[] = [
  {
    "id": "comienza-aqui",
    "seccion": "introduccion",
    "titulo": "Comienza aquí",
    "rotulo": "Lucas 24:13-35",
    "fecha": null
  },
  {
    "id": "como-usar",
    "seccion": "introduccion",
    "titulo": "Cómo usar este estudio",
    "rotulo": "Salmos 119:105-112",
    "fecha": null
  },
  {
    "id": "once-eras",
    "seccion": "introduccion",
    "titulo": "La gran historia en once eras",
    "rotulo": "Hechos 7:1-53",
    "fecha": null
  },
  {
    "id": "antiguo-y-nuevo",
    "seccion": "introduccion",
    "titulo": "¿Por qué Antiguo y Nuevo Testamento?",
    "rotulo": "Jeremías 31:31-34 + Lucas 22:14-20",
    "fecha": null
  },
  {
    "id": "tu-biblia",
    "seccion": "introduccion",
    "titulo": "Tu Biblia: católica y evangélica",
    "rotulo": "2 Timoteo 3:14-17",
    "fecha": null
  },
  {
    "id": "genesis-1-11",
    "seccion": "comienzos",
    "titulo": "En el principio",
    "rotulo": "Génesis 1–11",
    "fecha": "Sin fecha: la Biblia no la da"
  },
  {
    "id": "genesis-12-50",
    "seccion": "patriarcas",
    "titulo": "Dios llama a Abraham y a su familia",
    "rotulo": "Génesis 12–50",
    "fecha": "c. 2100–1800 a.C."
  },
  {
    "id": "job",
    "seccion": "patriarcas",
    "titulo": "Job: fe en medio del dolor",
    "rotulo": "Job 1–42",
    "fecha": "Época de los patriarcas (fecha incierta)"
  },
  {
    "id": "exodo",
    "seccion": "exodo",
    "titulo": "Dios libera a su pueblo de Egipto",
    "rotulo": "Éxodo 1–40",
    "fecha": "Salida de Egipto: c. 1446 o c. 1270 a.C."
  },
  {
    "id": "levitico",
    "seccion": "exodo",
    "titulo": "Un Dios santo vive entre su pueblo",
    "rotulo": "Levítico 1–27",
    "fecha": "c. 1445 a.C., al pie del Sinaí"
  },
  {
    "id": "numeros",
    "seccion": "exodo",
    "titulo": "Cuarenta años en el desierto",
    "rotulo": "Números 1–36 + Salmo 90",
    "fecha": "c. 1445–1406 a.C."
  },
  {
    "id": "deuteronomio",
    "seccion": "exodo",
    "titulo": "Moisés se despide del pueblo",
    "rotulo": "Deuteronomio 1–34",
    "fecha": "c. 1406 a.C., al final del desierto"
  },
  {
    "id": "josue",
    "seccion": "conquista",
    "titulo": "Israel entra en la tierra prometida",
    "rotulo": "Josué 1–24",
    "fecha": "c. 1406–1375 a.C."
  },
  {
    "id": "jueces",
    "seccion": "conquista",
    "titulo": "Caer y levantarse: el tiempo de los jueces",
    "rotulo": "Jueces 1–21",
    "fecha": "c. 1375–1050 a.C."
  },
  {
    "id": "rut",
    "seccion": "conquista",
    "titulo": "Rut: amor fiel en tiempos difíciles",
    "rotulo": "Rut 1–4",
    "fecha": "c. 1100 a.C., en tiempos de los jueces"
  },
  {
    "id": "1-samuel",
    "seccion": "reino-unido",
    "titulo": "Samuel, Saúl y el joven David",
    "rotulo": "1 Samuel 1–31",
    "fecha": "c. 1100–1010 a.C."
  },
  {
    "id": "2-samuel",
    "seccion": "reino-unido",
    "titulo": "David, rey según el corazón de Dios",
    "rotulo": "2 Samuel 1–24 + 1 Crónicas 10–29",
    "fecha": "c. 1010–970 a.C."
  },
  {
    "id": "salmos",
    "seccion": "reino-unido",
    "titulo": "Salmos: oraciones para toda la vida",
    "rotulo": "Salmos 1–150",
    "fecha": "Sobre todo en tiempos de David, c. 1000 a.C."
  },
  {
    "id": "salomon",
    "seccion": "reino-unido",
    "titulo": "Salomón: sabiduría y un templo para Dios",
    "rotulo": "1 Reyes 1–11 + 2 Crónicas 1–9",
    "fecha": "c. 970–930 a.C."
  },
  {
    "id": "proverbios",
    "seccion": "reino-unido",
    "titulo": "Proverbios: sabiduría para cada día",
    "rotulo": "Proverbios 1–31",
    "fecha": "c. 970–930 a.C., con Salomón"
  },
  {
    "id": "cantares",
    "seccion": "reino-unido",
    "titulo": "Cantares: el regalo del amor",
    "rotulo": "Cantares 1–8",
    "fecha": "c. 960 a.C., tiempos de Salomón"
  },
  {
    "id": "eclesiastes",
    "seccion": "reino-unido",
    "titulo": "Eclesiastés: ¿qué da sentido a la vida?",
    "rotulo": "Eclesiastés 1–12",
    "fecha": "c. 935 a.C., según la tradición"
  },
  {
    "id": "1-reyes-12-22",
    "seccion": "reino-dividido",
    "titulo": "El reino se divide y Elías habla",
    "rotulo": "1 Reyes 12–22 + 2 Crónicas 10–20",
    "fecha": "c. 930–850 a.C."
  },
  {
    "id": "joel",
    "seccion": "reino-dividido",
    "titulo": "Joel: el Espíritu para todos",
    "rotulo": "Joel 1–3",
    "fecha": "Fecha incierta (quizás c. 835 a.C.)"
  },
  {
    "id": "2-reyes-1-14",
    "seccion": "reino-dividido",
    "titulo": "Eliseo y los reyes de Israel y Judá",
    "rotulo": "2 Reyes 1–14 + 2 Crónicas 21–25",
    "fecha": "c. 850–790 a.C."
  },
  {
    "id": "jonas",
    "seccion": "reino-dividido",
    "titulo": "Jonás: Dios ama también a Nínive",
    "rotulo": "Jonás 1–4",
    "fecha": "c. 780–760 a.C."
  },
  {
    "id": "amos",
    "seccion": "reino-dividido",
    "titulo": "Amós: justicia para el pobre",
    "rotulo": "Amós 1–9",
    "fecha": "c. 760 a.C."
  },
  {
    "id": "oseas",
    "seccion": "reino-dividido",
    "titulo": "Oseas: un amor que no se rinde",
    "rotulo": "Oseas 1–14",
    "fecha": "c. 755–715 a.C."
  },
  {
    "id": "2-reyes-15-17",
    "seccion": "reino-dividido",
    "titulo": "Cae Samaria, el reino del norte",
    "rotulo": "2 Reyes 15–17 + 2 Crónicas 26–28",
    "fecha": "c. 750–722 a.C."
  },
  {
    "id": "isaias",
    "seccion": "reino-dividido",
    "titulo": "Isaías: el Santo que viene a salvar",
    "rotulo": "Isaías 1–66",
    "fecha": "c. 740–680 a.C."
  },
  {
    "id": "miqueas",
    "seccion": "reino-dividido",
    "titulo": "Miqueas: lo que Dios pide de ti",
    "rotulo": "Miqueas 1–7",
    "fecha": "c. 735–700 a.C."
  },
  {
    "id": "2-reyes-18-21",
    "seccion": "reino-dividido",
    "titulo": "Ezequías confía; Manasés se aleja",
    "rotulo": "2 Reyes 18–21 + 2 Crónicas 29–33",
    "fecha": "c. 715–640 a.C."
  },
  {
    "id": "nahum",
    "seccion": "reino-dividido",
    "titulo": "Nahúm: el fin de Nínive",
    "rotulo": "Nahúm 1–3",
    "fecha": "c. 660–612 a.C."
  },
  {
    "id": "2-reyes-22-23",
    "seccion": "reino-dividido",
    "titulo": "Josías y el libro de la Ley",
    "rotulo": "2 Reyes 22–23 + 2 Crónicas 34–35",
    "fecha": "c. 640–609 a.C."
  },
  {
    "id": "sofonias",
    "seccion": "reino-dividido",
    "titulo": "Sofonías: el día del Señor",
    "rotulo": "Sofonías 1–3",
    "fecha": "c. 630 a.C., en tiempos de Josías"
  },
  {
    "id": "jeremias",
    "seccion": "reino-dividido",
    "titulo": "Jeremías: lágrimas y un pacto nuevo",
    "rotulo": "Jeremías 1–52",
    "fecha": "c. 627–580 a.C."
  },
  {
    "id": "habacuc",
    "seccion": "reino-dividido",
    "titulo": "Habacuc: el justo vivirá por la fe",
    "rotulo": "Habacuc 1–3",
    "fecha": "c. 610–600 a.C."
  },
  {
    "id": "2-reyes-24-25",
    "seccion": "reino-dividido",
    "titulo": "Cae Jerusalén y el pueblo va cautivo",
    "rotulo": "2 Reyes 23:31–25:30 + 2 Crónicas 36",
    "fecha": "609–586 a.C."
  },
  {
    "id": "lamentaciones",
    "seccion": "reino-dividido",
    "titulo": "Lamentaciones: llorar con esperanza",
    "rotulo": "Lamentaciones 1–5",
    "fecha": "c. 586 a.C."
  },
  {
    "id": "abdias",
    "seccion": "exilio",
    "titulo": "Abdías: Dios ve la injusticia",
    "rotulo": "Abdías 1",
    "fecha": "c. 586 a.C."
  },
  {
    "id": "ezequiel",
    "seccion": "exilio",
    "titulo": "Ezequiel: Dios da un corazón nuevo",
    "rotulo": "Ezequiel 1–48",
    "fecha": "593–571 a.C."
  },
  {
    "id": "daniel",
    "seccion": "exilio",
    "titulo": "Daniel: fieles en tierra extraña",
    "rotulo": "Daniel 1–12",
    "fecha": "605–c. 535 a.C."
  },
  {
    "id": "esdras-1-6",
    "seccion": "regreso",
    "titulo": "Vuelven a casa y reconstruyen el templo",
    "rotulo": "Esdras 1–6 + 2 Crónicas 36:22-23",
    "fecha": "538–516 a.C."
  },
  {
    "id": "hageo",
    "seccion": "regreso",
    "titulo": "Hageo: primero la casa de Dios",
    "rotulo": "Hageo 1–2",
    "fecha": "520 a.C."
  },
  {
    "id": "zacarias",
    "seccion": "regreso",
    "titulo": "Zacarías: tu Rey viene a ti",
    "rotulo": "Zacarías 1–14",
    "fecha": "520–c. 480 a.C."
  },
  {
    "id": "ester",
    "seccion": "regreso",
    "titulo": "Ester: valor para salvar a su pueblo",
    "rotulo": "Ester 1–10",
    "fecha": "c. 483–473 a.C."
  },
  {
    "id": "esdras-7-10",
    "seccion": "regreso",
    "titulo": "Esdras enseña la Ley de Dios",
    "rotulo": "Esdras 7–10",
    "fecha": "458 a.C."
  },
  {
    "id": "nehemias",
    "seccion": "regreso",
    "titulo": "Nehemías levanta los muros",
    "rotulo": "Nehemías 1–13",
    "fecha": "445–c. 430 a.C."
  },
  {
    "id": "cronicas",
    "seccion": "regreso",
    "titulo": "Crónicas: la historia contada otra vez",
    "rotulo": "1 Crónicas 1–9 (+ todo 1 y 2 Crónicas)",
    "fecha": "Escrito c. 450–400 a.C."
  },
  {
    "id": "malaquias",
    "seccion": "regreso",
    "titulo": "Malaquías: el Señor vendrá a su templo",
    "rotulo": "Malaquías 1–4",
    "fecha": "c. 430 a.C."
  },
  {
    "id": "entre-testamentos",
    "seccion": "entre-testamentos",
    "titulo": "Entre los dos Testamentos",
    "rotulo": "Daniel 11:1-35 + Juan 10:22-23",
    "fecha": "c. 430–5 a.C."
  },
  {
    "id": "el-verbo",
    "seccion": "jesus",
    "titulo": "El Verbo, antes de todo",
    "rotulo": "Juan 1:1-18",
    "fecha": "Antes del principio"
  },
  {
    "id": "anuncios",
    "seccion": "jesus",
    "titulo": "Dos anuncios: Juan y Jesús",
    "rotulo": "Lucas 1 + Mateo 1",
    "fecha": "c. 7–5 a.C."
  },
  {
    "id": "nacimiento",
    "seccion": "jesus",
    "titulo": "Nace Jesús en Belén",
    "rotulo": "Lucas 2 + Mateo 2",
    "fecha": "c. 6–4 a.C. (nacimiento) a c. 8 d.C. (Jesús en el templo)"
  },
  {
    "id": "inicio-ministerio",
    "seccion": "jesus",
    "titulo": "Jesús comienza su misión",
    "rotulo": "Mateo 3–4 + Marcos 1 + Lucas 3–4 + Juan 1:19–4:54",
    "fecha": "c. 27–28 d.C."
  },
  {
    "id": "galilea-ensenanzas",
    "seccion": "jesus",
    "titulo": "Lo que Jesús enseñó en Galilea",
    "rotulo": "Mateo 5–7 + Mateo 13 + Lucas 6:17-49",
    "fecha": "c. 28–29 d.C."
  },
  {
    "id": "galilea-milagros",
    "seccion": "jesus",
    "titulo": "Milagros en Galilea y los Doce",
    "rotulo": "Mateo 8–18 + Marcos 2–9 + Lucas 5–9 + Juan 5–6",
    "fecha": "c. 28–29 d.C."
  },
  {
    "id": "camino-a-jerusalen",
    "seccion": "jesus",
    "titulo": "Camino a Jerusalén",
    "rotulo": "Lucas 9:51–19:27 + Juan 7–11 + Mateo 19–20 + Marcos 10",
    "fecha": "c. 29–30 d.C."
  },
  {
    "id": "ultima-semana",
    "seccion": "jesus",
    "titulo": "La última semana y la última cena",
    "rotulo": "Mateo 21–26 + Marcos 11–14 + Lucas 19–22 + Juan 12–17",
    "fecha": "c. 30 o 33 d.C."
  },
  {
    "id": "pasion-y-muerte",
    "seccion": "jesus",
    "titulo": "Pasión y muerte de Jesús",
    "rotulo": "Mateo 26–27 + Marcos 14–15 + Lucas 22–23 + Juan 18–19",
    "fecha": "c. 30 o 33 d.C., en la Pascua"
  },
  {
    "id": "resurreccion",
    "seccion": "jesus",
    "titulo": "¡Resucitó! Apariciones y ascensión",
    "rotulo": "Mateo 28 + Marcos 16 + Lucas 24 + Juan 20–21 + Hechos 1:1-11",
    "fecha": "c. 30 o 33 d.C., cuarenta días"
  },
  {
    "id": "hechos-1-7",
    "seccion": "iglesia",
    "titulo": "Nace la Iglesia en Jerusalén",
    "rotulo": "Hechos 1–7",
    "fecha": "c. 30–35 d.C."
  },
  {
    "id": "hechos-8-12",
    "seccion": "iglesia",
    "titulo": "La buena noticia sale de Jerusalén",
    "rotulo": "Hechos 8–12",
    "fecha": "c. 35–44 d.C."
  },
  {
    "id": "santiago",
    "seccion": "iglesia",
    "titulo": "Santiago: una fe que se ve",
    "rotulo": "Santiago 1–5",
    "fecha": "Escrita c. 45–49 d.C."
  },
  {
    "id": "hechos-13-14",
    "seccion": "iglesia",
    "titulo": "Primer viaje de Pablo y Bernabé",
    "rotulo": "Hechos 13–14",
    "fecha": "c. 46–48 d.C."
  },
  {
    "id": "galatas",
    "seccion": "iglesia",
    "titulo": "Gálatas: libres por la gracia",
    "rotulo": "Gálatas 1–6",
    "fecha": "Escrita c. 48–49 d.C."
  },
  {
    "id": "hechos-15-18",
    "seccion": "iglesia",
    "titulo": "El concilio y el segundo viaje",
    "rotulo": "Hechos 15:1–18:22",
    "fecha": "c. 49–52 d.C."
  },
  {
    "id": "1-tesalonicenses",
    "seccion": "iglesia",
    "titulo": "1 Tesalonicenses: esperanza en su venida",
    "rotulo": "1 Tesalonicenses 1–5",
    "fecha": "Escrita c. 50–51 d.C."
  },
  {
    "id": "2-tesalonicenses",
    "seccion": "iglesia",
    "titulo": "2 Tesalonicenses: firmes mientras esperamos",
    "rotulo": "2 Tesalonicenses 1–3",
    "fecha": "Escrita c. 51 d.C."
  },
  {
    "id": "hechos-18-20",
    "seccion": "iglesia",
    "titulo": "Tercer viaje: Pablo en Éfeso",
    "rotulo": "Hechos 18:23–20:38",
    "fecha": "c. 53–57 d.C."
  },
  {
    "id": "1-corintios",
    "seccion": "iglesia",
    "titulo": "1 Corintios: el camino del amor",
    "rotulo": "1 Corintios 1–16",
    "fecha": "Escrita c. 54–55 d.C."
  },
  {
    "id": "2-corintios",
    "seccion": "iglesia",
    "titulo": "2 Corintios: fuerza en la debilidad",
    "rotulo": "2 Corintios 1–13",
    "fecha": "Escrita c. 55–56 d.C."
  },
  {
    "id": "romanos",
    "seccion": "iglesia",
    "titulo": "Romanos: la buena noticia para todos",
    "rotulo": "Romanos 1–16",
    "fecha": "Escrita c. 57 d.C."
  },
  {
    "id": "hechos-21-28",
    "seccion": "iglesia",
    "titulo": "Pablo, preso, llega a Roma",
    "rotulo": "Hechos 21–28",
    "fecha": "c. 57–62 d.C."
  },
  {
    "id": "efesios",
    "seccion": "iglesia",
    "titulo": "Efesios: un solo cuerpo en Cristo",
    "rotulo": "Efesios 1–6",
    "fecha": "Escrita c. 60–62 d.C."
  },
  {
    "id": "colosenses",
    "seccion": "iglesia",
    "titulo": "Colosenses: Cristo es lo primero",
    "rotulo": "Colosenses 1–4",
    "fecha": "Escrita c. 60–62 d.C."
  },
  {
    "id": "filemon",
    "seccion": "iglesia",
    "titulo": "Filemón: recíbelo como a un hermano",
    "rotulo": "Filemón 1",
    "fecha": "Escrita c. 60–62 d.C."
  },
  {
    "id": "filipenses",
    "seccion": "iglesia",
    "titulo": "Filipenses: alegría en toda situación",
    "rotulo": "Filipenses 1–4",
    "fecha": "Escrita c. 61–62 d.C."
  },
  {
    "id": "1-timoteo",
    "seccion": "iglesia",
    "titulo": "1 Timoteo: cuidar la familia de Dios",
    "rotulo": "1 Timoteo 1–6",
    "fecha": "Escrita c. 62–64 d.C."
  },
  {
    "id": "tito",
    "seccion": "iglesia",
    "titulo": "Tito: una fe que hace el bien",
    "rotulo": "Tito 1–3",
    "fecha": "Escrita c. 62–64 d.C."
  },
  {
    "id": "1-pedro",
    "seccion": "iglesia",
    "titulo": "1 Pedro: esperanza en el sufrimiento",
    "rotulo": "1 Pedro 1–5",
    "fecha": "Escrita c. 62–64 d.C."
  },
  {
    "id": "2-timoteo",
    "seccion": "iglesia",
    "titulo": "2 Timoteo: termina bien la carrera",
    "rotulo": "2 Timoteo 1–4",
    "fecha": "Escrita c. 64–67 d.C."
  },
  {
    "id": "2-pedro",
    "seccion": "iglesia",
    "titulo": "2 Pedro: crecer y no olvidar",
    "rotulo": "2 Pedro 1–3",
    "fecha": "Escrita c. 65–67 d.C."
  },
  {
    "id": "hebreos",
    "seccion": "iglesia",
    "titulo": "Hebreos: Jesús, mejor que todo",
    "rotulo": "Hebreos 1–13",
    "fecha": "Escrita antes del año 70 d.C."
  },
  {
    "id": "judas",
    "seccion": "iglesia",
    "titulo": "Judas: cuida la fe que recibiste",
    "rotulo": "Judas 1",
    "fecha": "Escrita c. 65–80 d.C."
  },
  {
    "id": "1-juan",
    "seccion": "iglesia",
    "titulo": "1 Juan: Dios es amor",
    "rotulo": "1 Juan 1–5",
    "fecha": "Escrita c. 85–95 d.C."
  },
  {
    "id": "2-juan",
    "seccion": "iglesia",
    "titulo": "2 Juan: verdad y amor juntos",
    "rotulo": "2 Juan 1",
    "fecha": "Escrita c. 85–95 d.C."
  },
  {
    "id": "3-juan",
    "seccion": "iglesia",
    "titulo": "3 Juan: abre tu casa a los hermanos",
    "rotulo": "3 Juan 1",
    "fecha": "Escrita c. 85–95 d.C."
  },
  {
    "id": "apocalipsis",
    "seccion": "iglesia",
    "titulo": "Apocalipsis: el Cordero vence",
    "rotulo": "Apocalipsis 1–22",
    "fecha": "Escrito c. 95 d.C."
  },
  {
    "id": "conclusion",
    "seccion": "conclusion",
    "titulo": "Del Génesis al Apocalipsis",
    "rotulo": "Génesis 3:15 + Apocalipsis 22:1-5",
    "fecha": null
  }
]
