// Generated by content-src/guias/build-guias.mjs — do not edit by hand.
import type { GuiaIndice, GuiaLeccion } from './types'

export const GUIA_SECCIONES: Record<string, GuiaIndice['secciones']> = {
  "mandamientos": [
    {
      "id": "antes-de-empezar",
      "titulo": "Antes de empezar",
      "lecciones": [
        {
          "id": "comienza-aqui",
          "titulo": "Comienza aquí: un Dios que primero libera",
          "subtitulo": "Éxodo 20:2"
        },
        {
          "id": "dos-maneras-de-contarlos",
          "titulo": "¿Por qué hay dos maneras de contarlos?",
          "subtitulo": "Evangélicos y católicos: el mismo texto de Dios"
        }
      ]
    },
    {
      "id": "los-diez-mandamientos",
      "titulo": "Los Diez Mandamientos",
      "lecciones": [
        {
          "id": "solo-dios-primer-lugar",
          "titulo": "Solo Dios en el primer lugar",
          "subtitulo": "Evangélico: 1.º · Católico: 1.º"
        },
        {
          "id": "adorar-solo-a-dios",
          "titulo": "Adorar solo a Dios",
          "subtitulo": "Evangélico: 2.º · Católico: parte del 1.º"
        },
        {
          "id": "nombre-de-dios-santo",
          "titulo": "El nombre de Dios es santo",
          "subtitulo": "Evangélico: 3.º · Católico: 2.º"
        },
        {
          "id": "dia-para-dios-y-descansar",
          "titulo": "Un día para Dios y para descansar",
          "subtitulo": "Evangélico: 4.º · Católico: 3.º"
        },
        {
          "id": "honra-padre-y-madre",
          "titulo": "Honra a tu padre y a tu madre",
          "subtitulo": "Evangélico: 5.º · Católico: 4.º"
        },
        {
          "id": "cuidar-la-vida",
          "titulo": "Cuidar la vida",
          "subtitulo": "Evangélico: 6.º · Católico: 5.º"
        },
        {
          "id": "fidelidad-y-pureza",
          "titulo": "Fidelidad y pureza",
          "subtitulo": "Evangélico: 7.º · Católico: 6.º"
        },
        {
          "id": "lo-que-es-de-otro",
          "titulo": "Lo que es de otro, es de otro",
          "subtitulo": "Evangélico: 8.º · Católico: 7.º"
        },
        {
          "id": "hablar-con-la-verdad",
          "titulo": "Hablar con la verdad",
          "subtitulo": "Evangélico: 9.º · Católico: 8.º"
        },
        {
          "id": "corazon-contento",
          "titulo": "Un corazón contento",
          "subtitulo": "Evangélico: 10.º · Católico: 9.º y 10.º"
        }
      ]
    },
    {
      "id": "el-gran-mandamiento",
      "titulo": "El gran mandamiento",
      "lecciones": [
        {
          "id": "amar-a-dios-y-al-projimo",
          "titulo": "Amar a Dios y amar al prójimo",
          "subtitulo": "Mateo 22:36-40"
        },
        {
          "id": "repaso-final",
          "titulo": "Repaso final",
          "subtitulo": "Quiz de diez preguntas y «Los 10 en tus manos»"
        }
      ]
    }
  ],
  "milagros-jesus": [
    {
      "id": "comienzos",
      "titulo": "Los comienzos",
      "lecciones": [
        {
          "id": "bodas-de-cana",
          "titulo": "El agua que se volvió vino",
          "subtitulo": "Juan 2:1-11"
        },
        {
          "id": "hijo-del-oficial-del-rey",
          "titulo": "El hijo del oficial del rey",
          "subtitulo": "Juan 4:46-54"
        }
      ]
    },
    {
      "id": "galilea",
      "titulo": "El gran ministerio en Galilea",
      "lecciones": [
        {
          "id": "primera-pesca-milagrosa",
          "titulo": "La primera pesca milagrosa",
          "subtitulo": "Lucas 5:1-11"
        },
        {
          "id": "sinagoga-de-capernaum",
          "titulo": "El hombre de la sinagoga de Capernaúm",
          "subtitulo": "Marcos 1:21-28"
        },
        {
          "id": "suegra-de-pedro",
          "titulo": "La suegra de Pedro",
          "subtitulo": "Marcos 1:29-31"
        },
        {
          "id": "al-caer-la-tarde",
          "titulo": "Al caer la tarde, sanaba a todos",
          "subtitulo": "Marcos 1:32-34"
        },
        {
          "id": "el-leproso",
          "titulo": "El leproso: «Quiero, sé limpio»",
          "subtitulo": "Marcos 1:40-45"
        },
        {
          "id": "paralitico-del-techo",
          "titulo": "El paralítico que bajaron por el techo",
          "subtitulo": "Marcos 2:1-12"
        },
        {
          "id": "paralitico-de-betesda",
          "titulo": "El paralítico del estanque de Betesda",
          "subtitulo": "Juan 5:1-15"
        },
        {
          "id": "mano-seca",
          "titulo": "El hombre de la mano seca",
          "subtitulo": "Marcos 3:1-6"
        },
        {
          "id": "siervo-del-centurion",
          "titulo": "El siervo del centurión",
          "subtitulo": "Lucas 7:1-10"
        },
        {
          "id": "hijo-de-la-viuda-de-nain",
          "titulo": "El hijo de la viuda de Naín",
          "subtitulo": "Lucas 7:11-17"
        },
        {
          "id": "no-veia-ni-hablaba",
          "titulo": "El hombre que no veía ni hablaba",
          "subtitulo": "Mateo 12:22-23"
        },
        {
          "id": "calma-la-tempestad",
          "titulo": "Jesús calma la tempestad",
          "subtitulo": "Marcos 4:35-41"
        },
        {
          "id": "hombre-de-gadara",
          "titulo": "El hombre de Gadara",
          "subtitulo": "Marcos 5:1-20"
        },
        {
          "id": "mujer-que-toco-su-manto",
          "titulo": "La mujer que tocó su manto",
          "subtitulo": "Marcos 5:25-34"
        },
        {
          "id": "hija-de-jairo",
          "titulo": "La hija de Jairo: «Talita cumi»",
          "subtitulo": "Marcos 5:35-43"
        },
        {
          "id": "dos-ciegos",
          "titulo": "Dos ciegos que lo seguían",
          "subtitulo": "Mateo 9:27-31"
        },
        {
          "id": "mudo-que-volvio-a-hablar",
          "titulo": "El mudo que volvió a hablar",
          "subtitulo": "Mateo 9:32-34"
        }
      ]
    },
    {
      "id": "tierras-vecinas",
      "titulo": "Panes, mar y tierras vecinas",
      "lecciones": [
        {
          "id": "cinco-mil",
          "titulo": "Cinco panes y dos peces",
          "subtitulo": "Juan 6:1-14"
        },
        {
          "id": "camina-sobre-el-agua",
          "titulo": "Jesús camina sobre el agua",
          "subtitulo": "Mateo 14:22-33"
        },
        {
          "id": "en-genesaret",
          "titulo": "En Genesaret, tocaban su manto",
          "subtitulo": "Marcos 6:53-56"
        },
        {
          "id": "mujer-cananea",
          "titulo": "La fe de la mujer cananea",
          "subtitulo": "Marcos 7:24-30"
        },
        {
          "id": "efata",
          "titulo": "«Efata»: el sordo que hablaba mal",
          "subtitulo": "Marcos 7:31-37"
        },
        {
          "id": "cuatro-mil",
          "titulo": "Siete panes para cuatro mil",
          "subtitulo": "Marcos 8:1-10"
        },
        {
          "id": "ciego-de-betsaida",
          "titulo": "El ciego de Betsaida, poco a poco",
          "subtitulo": "Marcos 8:22-26"
        },
        {
          "id": "transfiguracion",
          "titulo": "La Transfiguración",
          "subtitulo": "Lucas 9:28-36"
        },
        {
          "id": "muchacho-al-pie-del-monte",
          "titulo": "El muchacho que el padre trajo",
          "subtitulo": "Marcos 9:14-29"
        },
        {
          "id": "moneda-en-el-pez",
          "titulo": "La moneda en la boca del pez",
          "subtitulo": "Mateo 17:24-27"
        }
      ]
    },
    {
      "id": "camino-jerusalen",
      "titulo": "Camino a Jerusalén",
      "lecciones": [
        {
          "id": "ciego-de-nacimiento",
          "titulo": "El ciego de nacimiento",
          "subtitulo": "Juan 9:1-41"
        },
        {
          "id": "mujer-encorvada",
          "titulo": "La mujer encorvada",
          "subtitulo": "Lucas 13:10-17"
        },
        {
          "id": "hidropesia",
          "titulo": "El hombre hinchado (hidropesía)",
          "subtitulo": "Lucas 14:1-6"
        },
        {
          "id": "lazaro",
          "titulo": "Lázaro, ¡sal fuera!",
          "subtitulo": "Juan 11:1-44"
        },
        {
          "id": "diez-leprosos",
          "titulo": "Los diez leprosos y el que volvió",
          "subtitulo": "Lucas 17:11-19"
        },
        {
          "id": "bartimeo",
          "titulo": "Bartimeo y los ciegos de Jericó",
          "subtitulo": "Marcos 10:46-52"
        }
      ]
    },
    {
      "id": "ultima-semana",
      "titulo": "La última semana y la victoria",
      "lecciones": [
        {
          "id": "higuera-sin-fruto",
          "titulo": "La higuera sin fruto",
          "subtitulo": "Mateo 21:18-22"
        },
        {
          "id": "ciegos-y-cojos-en-el-templo",
          "titulo": "Ciegos y cojos en el templo",
          "subtitulo": "Mateo 21:14"
        },
        {
          "id": "yo-soy-getsemani",
          "titulo": "«Yo soy»: los soldados caen en tierra",
          "subtitulo": "Juan 18:4-6"
        },
        {
          "id": "oreja-de-malco",
          "titulo": "La oreja de Malco",
          "subtitulo": "Lucas 22:49-51"
        },
        {
          "id": "senales-en-la-cruz",
          "titulo": "Señales en la cruz",
          "subtitulo": "Mateo 27:45-54"
        },
        {
          "id": "ha-resucitado",
          "titulo": "¡Ha resucitado!",
          "subtitulo": "Mateo 28:1-10"
        },
        {
          "id": "segunda-pesca",
          "titulo": "La segunda pesca: 153 peces",
          "subtitulo": "Juan 21:1-14"
        },
        {
          "id": "ascension",
          "titulo": "La Ascensión",
          "subtitulo": "Lucas 24:50-53"
        }
      ]
    }
  ],
  "mujeres-virtuosas": [
    {
      "id": "introduccion",
      "titulo": "Introducción",
      "lecciones": [
        {
          "id": "comienza-aqui",
          "titulo": "Comienza aquí",
          "subtitulo": "Qué significa «virtuosa» y cómo usar esta guía"
        },
        {
          "id": "guia-para-grupos",
          "titulo": "Cómo usar esta guía en grupo",
          "subtitulo": "Un encuentro de 45 minutos, paso a paso"
        }
      ]
    },
    {
      "id": "comienzos-y-patriarcas",
      "titulo": "Los comienzos y los patriarcas",
      "lecciones": [
        {
          "id": "eva",
          "titulo": "Eva",
          "subtitulo": "La madre de todos los vivientes"
        },
        {
          "id": "sara",
          "titulo": "Sara",
          "subtitulo": "La que se rió y vio la promesa"
        },
        {
          "id": "agar",
          "titulo": "Agar",
          "subtitulo": "La que fue vista por Dios"
        },
        {
          "id": "rebeca",
          "titulo": "Rebeca",
          "subtitulo": "La joven que dijo «Sí, iré»"
        },
        {
          "id": "lea",
          "titulo": "Lea",
          "subtitulo": "La menos amada, a quien Dios miró"
        },
        {
          "id": "raquel",
          "titulo": "Raquel",
          "subtitulo": "La que esperó un hijo con lágrimas"
        }
      ]
    },
    {
      "id": "egipto-y-desierto",
      "titulo": "Egipto y el desierto",
      "lecciones": [
        {
          "id": "sifra-y-fua",
          "titulo": "Sifra y Fúa",
          "subtitulo": "Las parteras valientes"
        },
        {
          "id": "jocabed",
          "titulo": "Jocabed",
          "subtitulo": "La madre que confió el cesto"
        },
        {
          "id": "miriam",
          "titulo": "Miriam",
          "subtitulo": "La que cantó junto al mar"
        },
        {
          "id": "hijas-de-zelofehad",
          "titulo": "Las hijas de Zelofehad",
          "subtitulo": "Cinco hermanas que pidieron su herencia"
        }
      ]
    },
    {
      "id": "tierra-prometida-y-jueces",
      "titulo": "La tierra prometida y los jueces",
      "lecciones": [
        {
          "id": "rahab",
          "titulo": "Rahab",
          "subtitulo": "La del cordón de grana"
        },
        {
          "id": "debora",
          "titulo": "Débora (y Jael)",
          "subtitulo": "Madre en Israel"
        },
        {
          "id": "noemi",
          "titulo": "Noemí",
          "subtitulo": "De la amargura a la alegría"
        },
        {
          "id": "rut",
          "titulo": "Rut",
          "subtitulo": "La moabita que eligió quedarse"
        },
        {
          "id": "ana-madre-de-samuel",
          "titulo": "Ana, la madre de Samuel",
          "subtitulo": "La que derramó su alma ante Dios"
        }
      ]
    },
    {
      "id": "reyes-y-profetas",
      "titulo": "Reyes y profetas",
      "lecciones": [
        {
          "id": "abigail",
          "titulo": "Abigail",
          "subtitulo": "La que detuvo una venganza"
        },
        {
          "id": "viuda-de-sarepta",
          "titulo": "La viuda de Sarepta",
          "subtitulo": "Harina y aceite que no se acabaron"
        },
        {
          "id": "sunamita",
          "titulo": "La sunamita",
          "subtitulo": "Un cuarto para el profeta"
        },
        {
          "id": "nina-de-naaman",
          "titulo": "La niña de la casa de Naamán",
          "subtitulo": "Una niña que habló de esperanza"
        },
        {
          "id": "hulda",
          "titulo": "Hulda",
          "subtitulo": "La profetisa del rey Josías"
        }
      ]
    },
    {
      "id": "exilio-y-regreso",
      "titulo": "Exilio y regreso",
      "lecciones": [
        {
          "id": "ester",
          "titulo": "Ester",
          "subtitulo": "Para esta hora"
        }
      ]
    },
    {
      "id": "evangelios",
      "titulo": "Los evangelios",
      "lecciones": [
        {
          "id": "elisabet",
          "titulo": "Elisabet",
          "subtitulo": "La que esperó hasta la vejez"
        },
        {
          "id": "maria-madre-de-jesus",
          "titulo": "María, la madre de Jesús",
          "subtitulo": "La que dijo sí a Dios"
        },
        {
          "id": "ana-la-profetisa",
          "titulo": "Ana, la profetisa",
          "subtitulo": "La que esperaba en el templo"
        },
        {
          "id": "mujer-samaritana",
          "titulo": "La mujer samaritana",
          "subtitulo": "El encuentro junto al pozo"
        },
        {
          "id": "mujer-que-toco-su-manto",
          "titulo": "La mujer que tocó su manto",
          "subtitulo": "Doce años de espera, un toque de fe"
        },
        {
          "id": "mujer-que-ungio-sus-pies",
          "titulo": "La mujer perdonada",
          "subtitulo": "La que ungió los pies de Jesús"
        },
        {
          "id": "juana-susana-y-otras",
          "titulo": "Juana, Susana y las que servían",
          "subtitulo": "Mujeres que seguían y sostenían a Jesús"
        },
        {
          "id": "mujer-cananea",
          "titulo": "La mujer cananea",
          "subtitulo": "La fe que insistió"
        },
        {
          "id": "marta-de-betania",
          "titulo": "Marta de Betania",
          "subtitulo": "La que sirvió y creyó"
        },
        {
          "id": "maria-de-betania",
          "titulo": "María de Betania",
          "subtitulo": "La que se sentó a los pies de Jesús"
        },
        {
          "id": "viuda-de-las-dos-blancas",
          "titulo": "La viuda de las dos blancas",
          "subtitulo": "La que dio todo lo que tenía"
        },
        {
          "id": "maria-magdalena",
          "titulo": "María Magdalena",
          "subtitulo": "La primera testigo de la resurrección"
        }
      ]
    },
    {
      "id": "iglesia-naciente",
      "titulo": "La iglesia naciente",
      "lecciones": [
        {
          "id": "tabita",
          "titulo": "Tabita (Dorcas)",
          "subtitulo": "Manos llenas de bien"
        },
        {
          "id": "rode",
          "titulo": "Rode",
          "subtitulo": "La muchacha que oyó llamar"
        },
        {
          "id": "lidia",
          "titulo": "Lidia",
          "subtitulo": "Un corazón abierto"
        },
        {
          "id": "priscila",
          "titulo": "Priscila",
          "subtitulo": "Con Aquila, al servicio del Evangelio"
        },
        {
          "id": "febe",
          "titulo": "Febe",
          "subtitulo": "La que llevó la carta a los Romanos"
        },
        {
          "id": "loida-y-eunice",
          "titulo": "Loida y Eunice",
          "subtitulo": "La fe de abuela a nieto"
        }
      ]
    },
    {
      "id": "para-cerrar",
      "titulo": "Para cerrar",
      "lecciones": [
        {
          "id": "genealogia-de-jesus",
          "titulo": "Las mujeres en la genealogía de Jesús",
          "subtitulo": "Tamar, Rahab, Rut, Betsabé y María"
        },
        {
          "id": "mujer-virtuosa-proverbios-31",
          "titulo": "La mujer virtuosa de Proverbios 31",
          "subtitulo": "Un retrato, no una lista"
        }
      ]
    }
  ],
  "biografias": [
    {
      "id": "comienza-aqui",
      "titulo": "Comienza aquí",
      "lecciones": [
        {
          "id": "comienza-aqui",
          "titulo": "Comienza aquí",
          "subtitulo": "Cómo leer las fichas: Biblia y tradición"
        },
        {
          "id": "quien-es-quien",
          "titulo": "Quién es quién",
          "subtitulo": "Simones, Santiagos, Judas, Josés y otros nombres repetidos"
        },
        {
          "id": "listas-de-los-doce",
          "titulo": "Las listas de los Doce",
          "subtitulo": "Las cuatro listas y sus nombres, lado a lado"
        },
        {
          "id": "linea-del-tiempo",
          "titulo": "Línea del tiempo de los personajes",
          "subtitulo": "Del Edén a la Iglesia naciente"
        }
      ]
    },
    {
      "id": "los-doce",
      "titulo": "Los Doce",
      "lecciones": [
        {
          "id": "pedro",
          "titulo": "Pedro",
          "subtitulo": "El pescador que cayó y fue restaurado"
        },
        {
          "id": "andres",
          "titulo": "Andrés",
          "subtitulo": "El hermano que llevó a Pedro a Jesús"
        },
        {
          "id": "santiago-hijo-de-zebedeo",
          "titulo": "Santiago, hijo de Zebedeo",
          "subtitulo": "En la RVR1960, Jacobo; hermano de Juan"
        },
        {
          "id": "juan",
          "titulo": "Juan",
          "subtitulo": "El discípulo a quien Jesús amaba"
        },
        {
          "id": "felipe",
          "titulo": "Felipe",
          "subtitulo": "El de Betsaida que dijo: «Ven y ve»"
        },
        {
          "id": "bartolome",
          "titulo": "Bartolomé",
          "subtitulo": "También llamado Natanael"
        },
        {
          "id": "tomas",
          "titulo": "Tomás",
          "subtitulo": "El que dijo: «¡Señor mío, y Dios mío!»"
        },
        {
          "id": "mateo",
          "titulo": "Mateo",
          "subtitulo": "El cobrador de impuestos, también llamado Leví"
        },
        {
          "id": "santiago-hijo-de-alfeo",
          "titulo": "Santiago, hijo de Alfeo",
          "subtitulo": "En la RVR1960, Jacobo"
        },
        {
          "id": "judas-tadeo",
          "titulo": "Judas Tadeo",
          "subtitulo": "También Lebeo o «Judas hermano de Jacobo»"
        },
        {
          "id": "simon-el-zelote",
          "titulo": "Simón el Zelote",
          "subtitulo": "En la RVR1960, Simón el cananista"
        },
        {
          "id": "judas-iscariote",
          "titulo": "Judas Iscariote",
          "subtitulo": "El que entregó a Jesús"
        },
        {
          "id": "matias",
          "titulo": "Matías",
          "subtitulo": "El elegido para completar a los Doce"
        }
      ]
    },
    {
      "id": "alrededor-de-jesus",
      "titulo": "Alrededor de Jesús",
      "lecciones": [
        {
          "id": "jose-de-nazaret",
          "titulo": "José de Nazaret",
          "subtitulo": "El hombre justo que cuidó a Jesús"
        },
        {
          "id": "zacarias",
          "titulo": "Zacarías",
          "subtitulo": "El sacerdote, padre de Juan el Bautista"
        },
        {
          "id": "juan-el-bautista",
          "titulo": "Juan el Bautista",
          "subtitulo": "La voz que preparó el camino"
        },
        {
          "id": "simeon-del-templo",
          "titulo": "Simeón",
          "subtitulo": "El anciano que tomó al niño en brazos"
        },
        {
          "id": "lazaro",
          "titulo": "Lázaro de Betania",
          "subtitulo": "El amigo de Jesús"
        },
        {
          "id": "nicodemo",
          "titulo": "Nicodemo",
          "subtitulo": "El maestro que vino de noche"
        },
        {
          "id": "jose-de-arimatea",
          "titulo": "José de Arimatea",
          "subtitulo": "El que dio su sepulcro a Jesús"
        },
        {
          "id": "zaqueo",
          "titulo": "Zaqueo",
          "subtitulo": "El cobrador que bajó del árbol"
        }
      ]
    },
    {
      "id": "iglesia-naciente",
      "titulo": "La Iglesia naciente",
      "lecciones": [
        {
          "id": "pablo",
          "titulo": "Pablo",
          "subtitulo": "De perseguidor a apóstol de las naciones"
        },
        {
          "id": "bernabe",
          "titulo": "Bernabé",
          "subtitulo": "El hijo de consolación"
        },
        {
          "id": "esteban",
          "titulo": "Esteban",
          "subtitulo": "El primer mártir de la Iglesia"
        },
        {
          "id": "felipe-el-evangelista",
          "titulo": "Felipe el evangelista",
          "subtitulo": "Uno de los siete, el que habló al etíope"
        },
        {
          "id": "santiago-hermano-del-senor",
          "titulo": "Santiago, hermano del Señor",
          "subtitulo": "Líder de la iglesia de Jerusalén"
        },
        {
          "id": "juan-marcos",
          "titulo": "Juan Marcos",
          "subtitulo": "El que volvió a ser útil"
        },
        {
          "id": "lucas",
          "titulo": "Lucas",
          "subtitulo": "El médico amado que escribió dos libros"
        },
        {
          "id": "silas",
          "titulo": "Silas",
          "subtitulo": "Compañero de Pablo, cantando en la cárcel"
        },
        {
          "id": "timoteo",
          "titulo": "Timoteo",
          "subtitulo": "El joven hijo en la fe de Pablo"
        },
        {
          "id": "cornelio",
          "titulo": "Cornelio",
          "subtitulo": "El centurión romano que abrió la puerta"
        }
      ]
    },
    {
      "id": "antiguo-testamento",
      "titulo": "Antiguo Testamento",
      "lecciones": [
        {
          "id": "adan",
          "titulo": "Adán",
          "subtitulo": "El primer hombre"
        },
        {
          "id": "noe",
          "titulo": "Noé",
          "subtitulo": "El que construyó el arca"
        },
        {
          "id": "abraham",
          "titulo": "Abraham",
          "subtitulo": "El padre de la fe"
        },
        {
          "id": "isaac",
          "titulo": "Isaac",
          "subtitulo": "El hijo de la promesa"
        },
        {
          "id": "jacob",
          "titulo": "Jacob",
          "subtitulo": "El que luchó y fue llamado Israel"
        },
        {
          "id": "jose-hijo-de-jacob",
          "titulo": "José, hijo de Jacob",
          "subtitulo": "De esclavo a gobernador de Egipto"
        },
        {
          "id": "job",
          "titulo": "Job",
          "subtitulo": "Fiel en medio del dolor"
        },
        {
          "id": "moises",
          "titulo": "Moisés",
          "subtitulo": "El que sacó a Israel de Egipto"
        },
        {
          "id": "josue",
          "titulo": "Josué",
          "subtitulo": "El que guió al pueblo a la tierra prometida"
        },
        {
          "id": "gedeon",
          "titulo": "Gedeón",
          "subtitulo": "El más pequeño, con trescientos hombres"
        },
        {
          "id": "sanson",
          "titulo": "Sansón",
          "subtitulo": "Una fuerza que venía de Dios"
        },
        {
          "id": "samuel",
          "titulo": "Samuel",
          "subtitulo": "El niño que escuchó a Dios"
        },
        {
          "id": "saul",
          "titulo": "Saúl",
          "subtitulo": "El primer rey de Israel"
        },
        {
          "id": "david",
          "titulo": "David",
          "subtitulo": "El pastor que llegó a ser rey"
        },
        {
          "id": "salomon",
          "titulo": "Salomón",
          "subtitulo": "El rey que pidió sabiduría"
        },
        {
          "id": "elias",
          "titulo": "Elías",
          "subtitulo": "El profeta del fuego y del silbo apacible"
        },
        {
          "id": "eliseo",
          "titulo": "Eliseo",
          "subtitulo": "El que recibió el manto de Elías"
        },
        {
          "id": "jonas",
          "titulo": "Jonás",
          "subtitulo": "El profeta que huyó y volvió"
        },
        {
          "id": "isaias",
          "titulo": "Isaías",
          "subtitulo": "El profeta que anunció al Mesías"
        },
        {
          "id": "jeremias",
          "titulo": "Jeremías",
          "subtitulo": "El profeta de las lágrimas y la esperanza"
        },
        {
          "id": "daniel",
          "titulo": "Daniel",
          "subtitulo": "Fiel a Dios en Babilonia"
        },
        {
          "id": "esdras-y-nehemias",
          "titulo": "Esdras y Nehemías",
          "subtitulo": "Reconstruir la Ley y los muros"
        }
      ]
    }
  ],
  "caminando-gigantes": [
    {
      "id": "comienza-aqui",
      "titulo": "Comienza aquí",
      "lecciones": [
        {
          "id": "comienza-aqui",
          "titulo": "Cómo usar esta biblioteca",
          "subtitulo": "Cuatro pasos cuando llega una lucha"
        },
        {
          "id": "que-estas-viviendo",
          "titulo": "¿Qué estás viviendo hoy?",
          "subtitulo": "Busca tu lucha y encuentra a tu gigante"
        }
      ]
    },
    {
      "id": "injusticia-y-espera",
      "titulo": "Injusticia y espera",
      "lecciones": [
        {
          "id": "jose",
          "titulo": "José",
          "subtitulo": "Cuando hacer todo bien no evita el sufrimiento"
        },
        {
          "id": "david-perseguido",
          "titulo": "David, perseguido",
          "subtitulo": "Cuando te atacan sin motivo, una y otra vez"
        },
        {
          "id": "abraham",
          "titulo": "Abraham",
          "subtitulo": "Cuando la promesa tarda años en llegar"
        },
        {
          "id": "ana",
          "titulo": "Ana",
          "subtitulo": "Cuando tu dolor es invisible para los demás"
        }
      ]
    },
    {
      "id": "perdida-y-duelo",
      "titulo": "Pérdida y duelo",
      "lecciones": [
        {
          "id": "job",
          "titulo": "Job",
          "subtitulo": "Cuando no hay respuestas"
        },
        {
          "id": "noemi",
          "titulo": "Noemí",
          "subtitulo": "Cuando la amargura quiere ser tu nombre"
        },
        {
          "id": "marta-y-maria",
          "titulo": "Marta y María",
          "subtitulo": "Cuando Jesús parece llegar tarde"
        },
        {
          "id": "jeremias-lamentaciones",
          "titulo": "Jeremías, entre ruinas",
          "subtitulo": "Cuando el dolor es profundo y no termina"
        }
      ]
    },
    {
      "id": "miedo-y-llamado",
      "titulo": "Miedo, inseguridad y llamado",
      "lecciones": [
        {
          "id": "moises",
          "titulo": "Moisés",
          "subtitulo": "Cuando tu pasado quiere descalificarte"
        },
        {
          "id": "gedeon",
          "titulo": "Gedeón",
          "subtitulo": "Cuando te sientes demasiado pequeño"
        },
        {
          "id": "jeremias",
          "titulo": "Jeremías",
          "subtitulo": "Cuando nadie te escucha ni te entiende"
        },
        {
          "id": "timoteo",
          "titulo": "Timoteo",
          "subtitulo": "Cuando eres joven, tímido y te toca liderar"
        },
        {
          "id": "ester",
          "titulo": "Ester",
          "subtitulo": "Cuando callar es más peligroso que hablar"
        }
      ]
    },
    {
      "id": "cansancio-y-soledad",
      "titulo": "Cansancio y soledad",
      "lecciones": [
        {
          "id": "elias",
          "titulo": "Elías",
          "subtitulo": "Cuando ya no puedes más"
        },
        {
          "id": "agar",
          "titulo": "Agar",
          "subtitulo": "Cuando te sientes abandonado en el desierto"
        }
      ]
    },
    {
      "id": "culpa-y-nuevo-comienzo",
      "titulo": "Culpa, caída y nuevo comienzo",
      "lecciones": [
        {
          "id": "david-caida",
          "titulo": "David, después de caer",
          "subtitulo": "Cuando el corazón baja la guardia"
        },
        {
          "id": "pedro",
          "titulo": "Pedro",
          "subtitulo": "Cuando fallas en el momento más importante"
        },
        {
          "id": "sanson",
          "titulo": "Sansón",
          "subtitulo": "Cuando el don corre más rápido que el carácter"
        },
        {
          "id": "jonas",
          "titulo": "Jonás",
          "subtitulo": "Cuando huyes de lo que Dios te pidió"
        },
        {
          "id": "zaqueo",
          "titulo": "Zaqueo",
          "subtitulo": "Cuando todos te juzgan por tu pasado"
        },
        {
          "id": "la-samaritana",
          "titulo": "La mujer samaritana",
          "subtitulo": "Cuando cargas una historia que te avergüenza"
        }
      ]
    },
    {
      "id": "familia-y-relaciones",
      "titulo": "Familia y relaciones",
      "lecciones": [
        {
          "id": "jacob-y-esau",
          "titulo": "Jacob y Esaú",
          "subtitulo": "Cuando una pelea de familia dura años"
        },
        {
          "id": "rut",
          "titulo": "Rut",
          "subtitulo": "Cuando eliges quedarte y ser fiel"
        },
        {
          "id": "abigail",
          "titulo": "Abigail",
          "subtitulo": "Cuando te toca poner paz en medio del conflicto"
        }
      ]
    },
    {
      "id": "fe-bajo-presion",
      "titulo": "Fe bajo presión",
      "lecciones": [
        {
          "id": "daniel",
          "titulo": "Daniel",
          "subtitulo": "Cuando ser fiel pone tu vida en riesgo"
        },
        {
          "id": "tres-jovenes",
          "titulo": "Sadrac, Mesac y Abed-nego",
          "subtitulo": "Cuando todos se arrodillan y tú no"
        },
        {
          "id": "pablo",
          "titulo": "Pablo",
          "subtitulo": "Cuando obedecer trae problemas constantes"
        },
        {
          "id": "esteban",
          "titulo": "Esteban",
          "subtitulo": "Cuando la fidelidad lo cuesta todo"
        }
      ]
    },
    {
      "id": "enfermedad-y-limites",
      "titulo": "Enfermedad y límites",
      "lecciones": [
        {
          "id": "la-mujer-que-toco-el-manto",
          "titulo": "La mujer que tocó el manto",
          "subtitulo": "Cuando llevas años enfermo y cansado"
        },
        {
          "id": "naaman",
          "titulo": "Naamán",
          "subtitulo": "Cuando el orgullo se interpone en tu sanidad"
        }
      ]
    },
    {
      "id": "el-gigante-mayor",
      "titulo": "El Gigante mayor",
      "lecciones": [
        {
          "id": "jesus",
          "titulo": "Jesús en Getsemaní",
          "subtitulo": "Cuando obedecer significa entregarlo todo"
        },
        {
          "id": "tu-caminas-con-gigantes",
          "titulo": "Tú caminas con gigantes",
          "subtitulo": "No fueron perfectos: fueron fieles en el dolor"
        }
      ]
    }
  ],
  "palabras-senor": [
    {
      "id": "comienza-aqui",
      "titulo": "Comienza aquí",
      "lecciones": [
        {
          "id": "como-usar-esta-guia",
          "titulo": "Cómo usar esta guía",
          "subtitulo": "Siete pasos para vivir la Palabra"
        }
      ]
    },
    {
      "id": "perdon-y-heridas",
      "titulo": "Perdón y heridas",
      "lecciones": [
        {
          "id": "no-puedo-perdonar-a-quien-me-hirio",
          "titulo": "Cuando no puedo perdonar a quien me hirió"
        },
        {
          "id": "no-logro-perdonarme-a-mi-mismo",
          "titulo": "Cuando no logro perdonarme a mí mismo"
        },
        {
          "id": "me-piden-perdon-y-no-se-si-creerles",
          "titulo": "Cuando me piden perdón y no sé si creerles"
        },
        {
          "id": "necesito-pedir-perdon",
          "titulo": "Cuando necesito pedir perdón"
        },
        {
          "id": "el-rencor-vuelve-una-y-otra-vez",
          "titulo": "Cuando el rencor vuelve una y otra vez"
        },
        {
          "id": "me-traiciona-alguien-cercano",
          "titulo": "Cuando me traiciona alguien cercano"
        },
        {
          "id": "cargo-heridas-de-mi-infancia",
          "titulo": "Cuando cargo heridas de mi infancia"
        },
        {
          "id": "me-hirieron-en-la-iglesia",
          "titulo": "Cuando me hirieron en la iglesia"
        }
      ]
    },
    {
      "id": "emociones",
      "titulo": "Emociones",
      "lecciones": [
        {
          "id": "la-ira-me-domina",
          "titulo": "Cuando la ira me domina"
        },
        {
          "id": "la-ansiedad-no-me-deja-en-paz",
          "titulo": "Cuando la ansiedad no me deja en paz"
        },
        {
          "id": "vivo-con-miedo",
          "titulo": "Cuando vivo con miedo"
        },
        {
          "id": "la-tristeza-no-se-va",
          "titulo": "Cuando la tristeza no se va"
        },
        {
          "id": "creo-que-tengo-depresion",
          "titulo": "Cuando creo que tengo depresión"
        },
        {
          "id": "estoy-agotado-por-dentro",
          "titulo": "Cuando estoy agotado por dentro"
        },
        {
          "id": "siento-envidia",
          "titulo": "Cuando siento envidia"
        },
        {
          "id": "los-celos-me-quitan-la-paz",
          "titulo": "Cuando los celos me quitan la paz"
        }
      ]
    },
    {
      "id": "identidad",
      "titulo": "Identidad y autoestima",
      "lecciones": [
        {
          "id": "no-me-gusta-quien-soy",
          "titulo": "Cuando no me gusta quien soy"
        },
        {
          "id": "me-siento-incapaz",
          "titulo": "Cuando me siento incapaz"
        },
        {
          "id": "me-comparo-con-los-demas",
          "titulo": "Cuando me comparo con los demás"
        },
        {
          "id": "me-rechazan-o-me-abandonan",
          "titulo": "Cuando me rechazan o me abandonan"
        },
        {
          "id": "cometo-el-mismo-error-otra-vez",
          "titulo": "Cuando cometo el mismo error otra vez"
        },
        {
          "id": "me-siento-vacio",
          "titulo": "Cuando me siento vacío"
        },
        {
          "id": "me-siento-solo",
          "titulo": "Cuando me siento solo"
        },
        {
          "id": "necesito-que-todos-me-aprueben",
          "titulo": "Cuando necesito que todos me aprueben"
        }
      ]
    },
    {
      "id": "pareja",
      "titulo": "Matrimonio y pareja",
      "lecciones": [
        {
          "id": "peleamos-todo-el-tiempo",
          "titulo": "Cuando peleamos todo el tiempo"
        },
        {
          "id": "el-amor-parece-enfriarse",
          "titulo": "Cuando el amor parece enfriarse"
        },
        {
          "id": "mi-pareja-no-comparte-mi-fe",
          "titulo": "Cuando mi pareja no comparte mi fe"
        },
        {
          "id": "hubo-infidelidad",
          "titulo": "Cuando hubo infidelidad"
        },
        {
          "id": "el-dinero-nos-divide",
          "titulo": "Cuando el dinero nos divide"
        },
        {
          "id": "busco-pareja-y-quiero-elegir-bien",
          "titulo": "Cuando busco pareja y quiero elegir bien"
        },
        {
          "id": "estoy-soltero-y-espero",
          "titulo": "Cuando estoy soltero y espero"
        },
        {
          "id": "la-tentacion-amenaza-mi-matrimonio",
          "titulo": "Cuando la tentación amenaza mi matrimonio"
        }
      ]
    },
    {
      "id": "familia",
      "titulo": "Hijos y familia",
      "lecciones": [
        {
          "id": "mi-hijo-se-aleja-o-se-rebela",
          "titulo": "Cuando mi hijo se aleja o se rebela"
        },
        {
          "id": "quiero-ensenar-la-fe-a-mis-hijos",
          "titulo": "Cuando quiero enseñar la fe a mis hijos"
        },
        {
          "id": "mis-padres-son-dificiles",
          "titulo": "Cuando mis padres son difíciles"
        },
        {
          "id": "mi-familia-no-entiende-mi-fe",
          "titulo": "Cuando mi familia no entiende mi fe"
        },
        {
          "id": "hay-peleas-constantes-en-casa",
          "titulo": "Cuando hay peleas constantes en casa"
        },
        {
          "id": "necesito-poner-limites",
          "titulo": "Cuando necesito poner límites"
        },
        {
          "id": "cuido-a-mis-padres-ancianos",
          "titulo": "Cuando cuido a mis padres ancianos"
        },
        {
          "id": "vivo-lejos-de-mi-familia",
          "titulo": "Cuando vivo lejos de mi familia"
        }
      ]
    },
    {
      "id": "amistades",
      "titulo": "Amistades y convivencia",
      "lecciones": [
        {
          "id": "una-amistad-me-aleja-de-dios",
          "titulo": "Cuando una amistad me aleja de Dios"
        },
        {
          "id": "tengo-que-confrontar-a-alguien",
          "titulo": "Cuando tengo que confrontar a alguien"
        },
        {
          "id": "siento-que-me-utilizan",
          "titulo": "Cuando siento que me utilizan"
        },
        {
          "id": "hablan-mal-de-mi",
          "titulo": "Cuando hablan mal de mí"
        },
        {
          "id": "soy-yo-quien-habla-mal-de-otros",
          "titulo": "Cuando soy yo quien habla mal de otros"
        },
        {
          "id": "convivo-con-alguien-dificil",
          "titulo": "Cuando convivo con alguien difícil"
        },
        {
          "id": "me-cuesta-hacer-amigos",
          "titulo": "Cuando me cuesta hacer amigos"
        },
        {
          "id": "las-redes-sociales-me-roban-la-paz",
          "titulo": "Cuando las redes sociales me roban la paz"
        }
      ]
    },
    {
      "id": "trabajo",
      "titulo": "Trabajo y propósito",
      "lecciones": [
        {
          "id": "odio-mi-trabajo",
          "titulo": "Cuando odio mi trabajo"
        },
        {
          "id": "mi-jefe-es-injusto",
          "titulo": "Cuando mi jefe es injusto"
        },
        {
          "id": "pierdo-el-trabajo",
          "titulo": "Cuando pierdo el trabajo"
        },
        {
          "id": "fracaso-en-lo-que-emprendo",
          "titulo": "Cuando fracaso en lo que emprendo"
        },
        {
          "id": "no-se-cual-es-mi-proposito",
          "titulo": "Cuando no sé cuál es mi propósito"
        },
        {
          "id": "me-siento-estancado",
          "titulo": "Cuando me siento estancado"
        },
        {
          "id": "tengo-miedo-de-volver-a-intentarlo",
          "titulo": "Cuando tengo miedo de volver a intentarlo"
        },
        {
          "id": "me-piden-hacer-algo-incorrecto",
          "titulo": "Cuando me piden hacer algo incorrecto"
        }
      ]
    },
    {
      "id": "dinero",
      "titulo": "Dinero y provisión",
      "lecciones": [
        {
          "id": "el-dinero-no-alcanza",
          "titulo": "Cuando el dinero no alcanza"
        },
        {
          "id": "vivo-endeudado",
          "titulo": "Cuando vivo endeudado"
        },
        {
          "id": "temo-por-mi-futuro-economico",
          "titulo": "Cuando temo por mi futuro económico"
        },
        {
          "id": "me-va-bien-y-me-alejo-de-dios",
          "titulo": "Cuando me va bien y me alejo de Dios"
        },
        {
          "id": "no-se-administrar-lo-que-tengo",
          "titulo": "Cuando no sé administrar lo que tengo"
        },
        {
          "id": "quiero-dar-pero-tengo-poco",
          "titulo": "Cuando quiero dar pero tengo poco"
        },
        {
          "id": "me-tienta-el-dinero-facil",
          "titulo": "Cuando me tienta el dinero fácil"
        },
        {
          "id": "nunca-me-parece-suficiente",
          "titulo": "Cuando nunca me parece suficiente"
        }
      ]
    },
    {
      "id": "decisiones",
      "titulo": "Decisiones y dirección",
      "lecciones": [
        {
          "id": "tengo-que-tomar-una-decision-importante",
          "titulo": "Cuando tengo que tomar una decisión importante"
        },
        {
          "id": "no-se-que-camino-elegir",
          "titulo": "Cuando no sé qué camino elegir"
        },
        {
          "id": "una-puerta-se-cierra",
          "titulo": "Cuando una puerta se cierra"
        },
        {
          "id": "me-toca-esperar",
          "titulo": "Cuando me toca esperar"
        },
        {
          "id": "pienso-en-mudarme-o-emigrar",
          "titulo": "Cuando pienso en mudarme o emigrar"
        },
        {
          "id": "quiero-empezar-algo-nuevo",
          "titulo": "Cuando quiero empezar algo nuevo"
        },
        {
          "id": "recibo-consejos-que-se-contradicen",
          "titulo": "Cuando recibo consejos que se contradicen"
        },
        {
          "id": "me-presionan-para-decidir-ya",
          "titulo": "Cuando me presionan para decidir ya"
        }
      ]
    },
    {
      "id": "fe",
      "titulo": "Fe y vida espiritual",
      "lecciones": [
        {
          "id": "oro-y-parece-que-dios-no-responde",
          "titulo": "Cuando oro y parece que Dios no responde"
        },
        {
          "id": "mi-fe-esta-debil",
          "titulo": "Cuando mi fe está débil"
        },
        {
          "id": "me-siento-lejos-de-dios",
          "titulo": "Cuando me siento lejos de Dios"
        },
        {
          "id": "solo-oro-en-los-problemas",
          "titulo": "Cuando solo oro en los problemas"
        },
        {
          "id": "tengo-dudas-sobre-dios",
          "titulo": "Cuando tengo dudas sobre Dios"
        },
        {
          "id": "no-tengo-tiempo-para-dios",
          "titulo": "Cuando no tengo tiempo para Dios"
        },
        {
          "id": "me-cuesta-leer-la-biblia",
          "titulo": "Cuando me cuesta leer la Biblia"
        },
        {
          "id": "me-canso-del-camino-cristiano",
          "titulo": "Cuando me canso del camino cristiano"
        }
      ]
    },
    {
      "id": "tentacion",
      "titulo": "Tentación y hábitos",
      "lecciones": [
        {
          "id": "lucho-con-un-pecado-oculto",
          "titulo": "Cuando lucho con un pecado oculto"
        },
        {
          "id": "caigo-siempre-en-la-misma-tentacion",
          "titulo": "Cuando caigo siempre en la misma tentación"
        },
        {
          "id": "me-siento-sucio-por-dentro",
          "titulo": "Cuando me siento sucio por dentro"
        },
        {
          "id": "justifico-lo-que-se-que-esta-mal",
          "titulo": "Cuando justifico lo que sé que está mal"
        },
        {
          "id": "una-adiccion-me-domina",
          "titulo": "Cuando una adicción me domina"
        },
        {
          "id": "pierdo-el-control-con-la-comida-o-las",
          "titulo": "Cuando pierdo el control con la comida o las compras"
        },
        {
          "id": "la-pereza-me-gana",
          "titulo": "Cuando la pereza me gana"
        },
        {
          "id": "me-descubro-mintiendo",
          "titulo": "Cuando me descubro mintiendo"
        }
      ]
    },
    {
      "id": "dolor",
      "titulo": "Dolor, enfermedad y pérdida",
      "lecciones": [
        {
          "id": "muere-alguien-que-amo",
          "titulo": "Cuando muere alguien que amo"
        },
        {
          "id": "estoy-enfermo-hace-mucho-tiempo",
          "titulo": "Cuando estoy enfermo hace mucho tiempo"
        },
        {
          "id": "alguien-que-amo-esta-enfermo",
          "titulo": "Cuando alguien que amo está enfermo"
        },
        {
          "id": "perdi-un-embarazo",
          "titulo": "Cuando perdí un embarazo"
        },
        {
          "id": "envejezco-y-me-siento-inutil",
          "titulo": "Cuando envejezco y me siento inútil"
        },
        {
          "id": "sufro-una-injusticia",
          "titulo": "Cuando sufro una injusticia"
        },
        {
          "id": "sufro-y-no-entiendo-por-que",
          "titulo": "Cuando sufro y no entiendo por qué"
        },
        {
          "id": "pienso-que-ya-no-hay-salida",
          "titulo": "Cuando pienso que ya no hay salida"
        }
      ]
    },
    {
      "id": "hacedor",
      "titulo": "Vivir como hacedor de la Palabra",
      "lecciones": [
        {
          "id": "se-lo-correcto-pero-no-lo-hago",
          "titulo": "Cuando sé lo correcto pero no lo hago"
        },
        {
          "id": "sigo-actuando-como-antes",
          "titulo": "Cuando sigo actuando como antes"
        },
        {
          "id": "me-siento-hipocrita",
          "titulo": "Cuando me siento hipócrita"
        },
        {
          "id": "se-burlan-de-mi-fe",
          "titulo": "Cuando se burlan de mi fe"
        },
        {
          "id": "me-da-verguenza-mi-fe",
          "titulo": "Cuando me da vergüenza mi fe"
        },
        {
          "id": "quiero-servir-y-no-se-como",
          "titulo": "Cuando quiero servir y no sé cómo"
        },
        {
          "id": "quiero-hablar-de-jesus-sin-pelear",
          "titulo": "Cuando quiero hablar de Jesús sin pelear"
        },
        {
          "id": "quiero-una-fe-verdadera",
          "titulo": "Cuando quiero una fe verdadera"
        }
      ]
    },
    {
      "id": "cierre",
      "titulo": "Cierre",
      "lecciones": [
        {
          "id": "hacedores-de-la-palabra",
          "titulo": "Hacedores de la Palabra",
          "subtitulo": "Quien oye entiende; quien practica se transforma"
        }
      ]
    }
  ]
}

/** "<guia>/<lesson id>" → the written lesson. */
export const GUIA_LECCIONES: Record<string, () => Promise<GuiaLeccion>> = {
  'mandamientos/adorar-solo-a-dios': () => import('./mandamientos/adorar-solo-a-dios.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/amar-a-dios-y-al-projimo': () => import('./mandamientos/amar-a-dios-y-al-projimo.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/comienza-aqui': () => import('./mandamientos/comienza-aqui.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/corazon-contento': () => import('./mandamientos/corazon-contento.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/cuidar-la-vida': () => import('./mandamientos/cuidar-la-vida.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/dia-para-dios-y-descansar': () => import('./mandamientos/dia-para-dios-y-descansar.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/dos-maneras-de-contarlos': () => import('./mandamientos/dos-maneras-de-contarlos.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/fidelidad-y-pureza': () => import('./mandamientos/fidelidad-y-pureza.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/hablar-con-la-verdad': () => import('./mandamientos/hablar-con-la-verdad.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/honra-padre-y-madre': () => import('./mandamientos/honra-padre-y-madre.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/lo-que-es-de-otro': () => import('./mandamientos/lo-que-es-de-otro.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/nombre-de-dios-santo': () => import('./mandamientos/nombre-de-dios-santo.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/repaso-final': () => import('./mandamientos/repaso-final.json').then((m) => m.default as unknown as GuiaLeccion),
  'mandamientos/solo-dios-primer-lugar': () => import('./mandamientos/solo-dios-primer-lugar.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/al-caer-la-tarde': () => import('./milagros-jesus/al-caer-la-tarde.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/ascension': () => import('./milagros-jesus/ascension.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/bartimeo': () => import('./milagros-jesus/bartimeo.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/bodas-de-cana': () => import('./milagros-jesus/bodas-de-cana.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/calma-la-tempestad': () => import('./milagros-jesus/calma-la-tempestad.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/camina-sobre-el-agua': () => import('./milagros-jesus/camina-sobre-el-agua.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/ciego-de-betsaida': () => import('./milagros-jesus/ciego-de-betsaida.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/ciego-de-nacimiento': () => import('./milagros-jesus/ciego-de-nacimiento.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/ciegos-y-cojos-en-el-templo': () => import('./milagros-jesus/ciegos-y-cojos-en-el-templo.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/cinco-mil': () => import('./milagros-jesus/cinco-mil.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/cuatro-mil': () => import('./milagros-jesus/cuatro-mil.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/diez-leprosos': () => import('./milagros-jesus/diez-leprosos.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/dos-ciegos': () => import('./milagros-jesus/dos-ciegos.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/efata': () => import('./milagros-jesus/efata.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/el-leproso': () => import('./milagros-jesus/el-leproso.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/en-genesaret': () => import('./milagros-jesus/en-genesaret.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/ha-resucitado': () => import('./milagros-jesus/ha-resucitado.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/hidropesia': () => import('./milagros-jesus/hidropesia.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/higuera-sin-fruto': () => import('./milagros-jesus/higuera-sin-fruto.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/hija-de-jairo': () => import('./milagros-jesus/hija-de-jairo.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/hijo-de-la-viuda-de-nain': () => import('./milagros-jesus/hijo-de-la-viuda-de-nain.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/hijo-del-oficial-del-rey': () => import('./milagros-jesus/hijo-del-oficial-del-rey.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/hombre-de-gadara': () => import('./milagros-jesus/hombre-de-gadara.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/lazaro': () => import('./milagros-jesus/lazaro.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/mano-seca': () => import('./milagros-jesus/mano-seca.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/moneda-en-el-pez': () => import('./milagros-jesus/moneda-en-el-pez.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/muchacho-al-pie-del-monte': () => import('./milagros-jesus/muchacho-al-pie-del-monte.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/mudo-que-volvio-a-hablar': () => import('./milagros-jesus/mudo-que-volvio-a-hablar.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/mujer-cananea': () => import('./milagros-jesus/mujer-cananea.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/mujer-encorvada': () => import('./milagros-jesus/mujer-encorvada.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/mujer-que-toco-su-manto': () => import('./milagros-jesus/mujer-que-toco-su-manto.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/no-veia-ni-hablaba': () => import('./milagros-jesus/no-veia-ni-hablaba.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/oreja-de-malco': () => import('./milagros-jesus/oreja-de-malco.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/paralitico-de-betesda': () => import('./milagros-jesus/paralitico-de-betesda.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/paralitico-del-techo': () => import('./milagros-jesus/paralitico-del-techo.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/primera-pesca-milagrosa': () => import('./milagros-jesus/primera-pesca-milagrosa.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/segunda-pesca': () => import('./milagros-jesus/segunda-pesca.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/senales-en-la-cruz': () => import('./milagros-jesus/senales-en-la-cruz.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/siervo-del-centurion': () => import('./milagros-jesus/siervo-del-centurion.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/sinagoga-de-capernaum': () => import('./milagros-jesus/sinagoga-de-capernaum.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/suegra-de-pedro': () => import('./milagros-jesus/suegra-de-pedro.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/transfiguracion': () => import('./milagros-jesus/transfiguracion.json').then((m) => m.default as unknown as GuiaLeccion),
  'milagros-jesus/yo-soy-getsemani': () => import('./milagros-jesus/yo-soy-getsemani.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/abigail': () => import('./mujeres-virtuosas/abigail.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/agar': () => import('./mujeres-virtuosas/agar.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/ana-la-profetisa': () => import('./mujeres-virtuosas/ana-la-profetisa.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/ana-madre-de-samuel': () => import('./mujeres-virtuosas/ana-madre-de-samuel.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/comienza-aqui': () => import('./mujeres-virtuosas/comienza-aqui.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/debora': () => import('./mujeres-virtuosas/debora.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/elisabet': () => import('./mujeres-virtuosas/elisabet.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/ester': () => import('./mujeres-virtuosas/ester.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/eva': () => import('./mujeres-virtuosas/eva.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/febe': () => import('./mujeres-virtuosas/febe.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/genealogia-de-jesus': () => import('./mujeres-virtuosas/genealogia-de-jesus.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/guia-para-grupos': () => import('./mujeres-virtuosas/guia-para-grupos.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/hijas-de-zelofehad': () => import('./mujeres-virtuosas/hijas-de-zelofehad.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/hulda': () => import('./mujeres-virtuosas/hulda.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/jocabed': () => import('./mujeres-virtuosas/jocabed.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/juana-susana-y-otras': () => import('./mujeres-virtuosas/juana-susana-y-otras.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/lea': () => import('./mujeres-virtuosas/lea.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/lidia': () => import('./mujeres-virtuosas/lidia.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/loida-y-eunice': () => import('./mujeres-virtuosas/loida-y-eunice.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/maria-de-betania': () => import('./mujeres-virtuosas/maria-de-betania.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/maria-madre-de-jesus': () => import('./mujeres-virtuosas/maria-madre-de-jesus.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/maria-magdalena': () => import('./mujeres-virtuosas/maria-magdalena.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/marta-de-betania': () => import('./mujeres-virtuosas/marta-de-betania.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/miriam': () => import('./mujeres-virtuosas/miriam.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/mujer-cananea': () => import('./mujeres-virtuosas/mujer-cananea.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/mujer-que-toco-su-manto': () => import('./mujeres-virtuosas/mujer-que-toco-su-manto.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/mujer-que-ungio-sus-pies': () => import('./mujeres-virtuosas/mujer-que-ungio-sus-pies.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/mujer-samaritana': () => import('./mujeres-virtuosas/mujer-samaritana.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/mujer-virtuosa-proverbios-31': () => import('./mujeres-virtuosas/mujer-virtuosa-proverbios-31.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/nina-de-naaman': () => import('./mujeres-virtuosas/nina-de-naaman.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/noemi': () => import('./mujeres-virtuosas/noemi.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/priscila': () => import('./mujeres-virtuosas/priscila.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/rahab': () => import('./mujeres-virtuosas/rahab.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/raquel': () => import('./mujeres-virtuosas/raquel.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/rebeca': () => import('./mujeres-virtuosas/rebeca.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/rode': () => import('./mujeres-virtuosas/rode.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/rut': () => import('./mujeres-virtuosas/rut.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/sara': () => import('./mujeres-virtuosas/sara.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/sifra-y-fua': () => import('./mujeres-virtuosas/sifra-y-fua.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/sunamita': () => import('./mujeres-virtuosas/sunamita.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/tabita': () => import('./mujeres-virtuosas/tabita.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/viuda-de-las-dos-blancas': () => import('./mujeres-virtuosas/viuda-de-las-dos-blancas.json').then((m) => m.default as unknown as GuiaLeccion),
  'mujeres-virtuosas/viuda-de-sarepta': () => import('./mujeres-virtuosas/viuda-de-sarepta.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/abraham': () => import('./biografias/abraham.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/adan': () => import('./biografias/adan.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/andres': () => import('./biografias/andres.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/bartolome': () => import('./biografias/bartolome.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/bernabe': () => import('./biografias/bernabe.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/comienza-aqui': () => import('./biografias/comienza-aqui.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/cornelio': () => import('./biografias/cornelio.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/daniel': () => import('./biografias/daniel.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/david': () => import('./biografias/david.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/elias': () => import('./biografias/elias.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/eliseo': () => import('./biografias/eliseo.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/esdras-y-nehemias': () => import('./biografias/esdras-y-nehemias.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/esteban': () => import('./biografias/esteban.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/felipe-el-evangelista': () => import('./biografias/felipe-el-evangelista.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/felipe': () => import('./biografias/felipe.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/gedeon': () => import('./biografias/gedeon.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/isaac': () => import('./biografias/isaac.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/isaias': () => import('./biografias/isaias.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/jacob': () => import('./biografias/jacob.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/jeremias': () => import('./biografias/jeremias.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/job': () => import('./biografias/job.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/jonas': () => import('./biografias/jonas.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/jose-de-arimatea': () => import('./biografias/jose-de-arimatea.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/jose-de-nazaret': () => import('./biografias/jose-de-nazaret.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/jose-hijo-de-jacob': () => import('./biografias/jose-hijo-de-jacob.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/josue': () => import('./biografias/josue.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/juan-el-bautista': () => import('./biografias/juan-el-bautista.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/juan-marcos': () => import('./biografias/juan-marcos.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/juan': () => import('./biografias/juan.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/judas-iscariote': () => import('./biografias/judas-iscariote.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/judas-tadeo': () => import('./biografias/judas-tadeo.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/lazaro': () => import('./biografias/lazaro.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/linea-del-tiempo': () => import('./biografias/linea-del-tiempo.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/listas-de-los-doce': () => import('./biografias/listas-de-los-doce.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/lucas': () => import('./biografias/lucas.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/mateo': () => import('./biografias/mateo.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/matias': () => import('./biografias/matias.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/moises': () => import('./biografias/moises.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/nicodemo': () => import('./biografias/nicodemo.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/noe': () => import('./biografias/noe.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/pablo': () => import('./biografias/pablo.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/pedro': () => import('./biografias/pedro.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/quien-es-quien': () => import('./biografias/quien-es-quien.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/salomon': () => import('./biografias/salomon.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/samuel': () => import('./biografias/samuel.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/sanson': () => import('./biografias/sanson.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/santiago-hermano-del-senor': () => import('./biografias/santiago-hermano-del-senor.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/santiago-hijo-de-alfeo': () => import('./biografias/santiago-hijo-de-alfeo.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/santiago-hijo-de-zebedeo': () => import('./biografias/santiago-hijo-de-zebedeo.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/saul': () => import('./biografias/saul.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/silas': () => import('./biografias/silas.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/simeon-del-templo': () => import('./biografias/simeon-del-templo.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/simon-el-zelote': () => import('./biografias/simon-el-zelote.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/timoteo': () => import('./biografias/timoteo.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/tomas': () => import('./biografias/tomas.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/zacarias': () => import('./biografias/zacarias.json').then((m) => m.default as unknown as GuiaLeccion),
  'biografias/zaqueo': () => import('./biografias/zaqueo.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/abigail': () => import('./caminando-gigantes/abigail.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/abraham': () => import('./caminando-gigantes/abraham.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/agar': () => import('./caminando-gigantes/agar.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/ana': () => import('./caminando-gigantes/ana.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/comienza-aqui': () => import('./caminando-gigantes/comienza-aqui.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/daniel': () => import('./caminando-gigantes/daniel.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/david-caida': () => import('./caminando-gigantes/david-caida.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/david-perseguido': () => import('./caminando-gigantes/david-perseguido.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/elias': () => import('./caminando-gigantes/elias.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/esteban': () => import('./caminando-gigantes/esteban.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/ester': () => import('./caminando-gigantes/ester.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/gedeon': () => import('./caminando-gigantes/gedeon.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/jacob-y-esau': () => import('./caminando-gigantes/jacob-y-esau.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/jeremias-lamentaciones': () => import('./caminando-gigantes/jeremias-lamentaciones.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/jeremias': () => import('./caminando-gigantes/jeremias.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/jesus': () => import('./caminando-gigantes/jesus.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/job': () => import('./caminando-gigantes/job.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/jonas': () => import('./caminando-gigantes/jonas.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/jose': () => import('./caminando-gigantes/jose.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/la-mujer-que-toco-el-manto': () => import('./caminando-gigantes/la-mujer-que-toco-el-manto.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/la-samaritana': () => import('./caminando-gigantes/la-samaritana.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/marta-y-maria': () => import('./caminando-gigantes/marta-y-maria.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/moises': () => import('./caminando-gigantes/moises.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/naaman': () => import('./caminando-gigantes/naaman.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/noemi': () => import('./caminando-gigantes/noemi.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/pablo': () => import('./caminando-gigantes/pablo.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/pedro': () => import('./caminando-gigantes/pedro.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/que-estas-viviendo': () => import('./caminando-gigantes/que-estas-viviendo.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/rut': () => import('./caminando-gigantes/rut.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/sanson': () => import('./caminando-gigantes/sanson.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/timoteo': () => import('./caminando-gigantes/timoteo.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/tres-jovenes': () => import('./caminando-gigantes/tres-jovenes.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/tu-caminas-con-gigantes': () => import('./caminando-gigantes/tu-caminas-con-gigantes.json').then((m) => m.default as unknown as GuiaLeccion),
  'caminando-gigantes/zaqueo': () => import('./caminando-gigantes/zaqueo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/alguien-que-amo-esta-enfermo': () => import('./palabras-senor/alguien-que-amo-esta-enfermo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/busco-pareja-y-quiero-elegir-bien': () => import('./palabras-senor/busco-pareja-y-quiero-elegir-bien.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/caigo-siempre-en-la-misma-tentacion': () => import('./palabras-senor/caigo-siempre-en-la-misma-tentacion.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/cargo-heridas-de-mi-infancia': () => import('./palabras-senor/cargo-heridas-de-mi-infancia.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/cometo-el-mismo-error-otra-vez': () => import('./palabras-senor/cometo-el-mismo-error-otra-vez.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/como-usar-esta-guia': () => import('./palabras-senor/como-usar-esta-guia.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/convivo-con-alguien-dificil': () => import('./palabras-senor/convivo-con-alguien-dificil.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/creo-que-tengo-depresion': () => import('./palabras-senor/creo-que-tengo-depresion.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/cuido-a-mis-padres-ancianos': () => import('./palabras-senor/cuido-a-mis-padres-ancianos.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/el-amor-parece-enfriarse': () => import('./palabras-senor/el-amor-parece-enfriarse.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/el-dinero-no-alcanza': () => import('./palabras-senor/el-dinero-no-alcanza.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/el-dinero-nos-divide': () => import('./palabras-senor/el-dinero-nos-divide.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/el-rencor-vuelve-una-y-otra-vez': () => import('./palabras-senor/el-rencor-vuelve-una-y-otra-vez.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/envejezco-y-me-siento-inutil': () => import('./palabras-senor/envejezco-y-me-siento-inutil.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/estoy-agotado-por-dentro': () => import('./palabras-senor/estoy-agotado-por-dentro.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/estoy-enfermo-hace-mucho-tiempo': () => import('./palabras-senor/estoy-enfermo-hace-mucho-tiempo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/estoy-soltero-y-espero': () => import('./palabras-senor/estoy-soltero-y-espero.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/fracaso-en-lo-que-emprendo': () => import('./palabras-senor/fracaso-en-lo-que-emprendo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/hablan-mal-de-mi': () => import('./palabras-senor/hablan-mal-de-mi.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/hacedores-de-la-palabra': () => import('./palabras-senor/hacedores-de-la-palabra.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/hay-peleas-constantes-en-casa': () => import('./palabras-senor/hay-peleas-constantes-en-casa.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/hubo-infidelidad': () => import('./palabras-senor/hubo-infidelidad.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/justifico-lo-que-se-que-esta-mal': () => import('./palabras-senor/justifico-lo-que-se-que-esta-mal.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/la-ansiedad-no-me-deja-en-paz': () => import('./palabras-senor/la-ansiedad-no-me-deja-en-paz.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/la-ira-me-domina': () => import('./palabras-senor/la-ira-me-domina.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/la-pereza-me-gana': () => import('./palabras-senor/la-pereza-me-gana.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/la-tentacion-amenaza-mi-matrimonio': () => import('./palabras-senor/la-tentacion-amenaza-mi-matrimonio.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/la-tristeza-no-se-va': () => import('./palabras-senor/la-tristeza-no-se-va.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/las-redes-sociales-me-roban-la-paz': () => import('./palabras-senor/las-redes-sociales-me-roban-la-paz.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/los-celos-me-quitan-la-paz': () => import('./palabras-senor/los-celos-me-quitan-la-paz.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/lucho-con-un-pecado-oculto': () => import('./palabras-senor/lucho-con-un-pecado-oculto.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-canso-del-camino-cristiano': () => import('./palabras-senor/me-canso-del-camino-cristiano.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-comparo-con-los-demas': () => import('./palabras-senor/me-comparo-con-los-demas.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-cuesta-hacer-amigos': () => import('./palabras-senor/me-cuesta-hacer-amigos.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-cuesta-leer-la-biblia': () => import('./palabras-senor/me-cuesta-leer-la-biblia.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-da-verguenza-mi-fe': () => import('./palabras-senor/me-da-verguenza-mi-fe.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-descubro-mintiendo': () => import('./palabras-senor/me-descubro-mintiendo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-hirieron-en-la-iglesia': () => import('./palabras-senor/me-hirieron-en-la-iglesia.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-piden-hacer-algo-incorrecto': () => import('./palabras-senor/me-piden-hacer-algo-incorrecto.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-piden-perdon-y-no-se-si-creerles': () => import('./palabras-senor/me-piden-perdon-y-no-se-si-creerles.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-presionan-para-decidir-ya': () => import('./palabras-senor/me-presionan-para-decidir-ya.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-rechazan-o-me-abandonan': () => import('./palabras-senor/me-rechazan-o-me-abandonan.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-siento-estancado': () => import('./palabras-senor/me-siento-estancado.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-siento-hipocrita': () => import('./palabras-senor/me-siento-hipocrita.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-siento-incapaz': () => import('./palabras-senor/me-siento-incapaz.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-siento-lejos-de-dios': () => import('./palabras-senor/me-siento-lejos-de-dios.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-siento-solo': () => import('./palabras-senor/me-siento-solo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-siento-sucio-por-dentro': () => import('./palabras-senor/me-siento-sucio-por-dentro.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-siento-vacio': () => import('./palabras-senor/me-siento-vacio.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-tienta-el-dinero-facil': () => import('./palabras-senor/me-tienta-el-dinero-facil.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-toca-esperar': () => import('./palabras-senor/me-toca-esperar.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-traiciona-alguien-cercano': () => import('./palabras-senor/me-traiciona-alguien-cercano.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/me-va-bien-y-me-alejo-de-dios': () => import('./palabras-senor/me-va-bien-y-me-alejo-de-dios.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/mi-familia-no-entiende-mi-fe': () => import('./palabras-senor/mi-familia-no-entiende-mi-fe.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/mi-fe-esta-debil': () => import('./palabras-senor/mi-fe-esta-debil.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/mi-hijo-se-aleja-o-se-rebela': () => import('./palabras-senor/mi-hijo-se-aleja-o-se-rebela.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/mi-jefe-es-injusto': () => import('./palabras-senor/mi-jefe-es-injusto.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/mi-pareja-no-comparte-mi-fe': () => import('./palabras-senor/mi-pareja-no-comparte-mi-fe.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/mis-padres-son-dificiles': () => import('./palabras-senor/mis-padres-son-dificiles.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/muere-alguien-que-amo': () => import('./palabras-senor/muere-alguien-que-amo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/necesito-pedir-perdon': () => import('./palabras-senor/necesito-pedir-perdon.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/necesito-poner-limites': () => import('./palabras-senor/necesito-poner-limites.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/necesito-que-todos-me-aprueben': () => import('./palabras-senor/necesito-que-todos-me-aprueben.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/no-logro-perdonarme-a-mi-mismo': () => import('./palabras-senor/no-logro-perdonarme-a-mi-mismo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/no-me-gusta-quien-soy': () => import('./palabras-senor/no-me-gusta-quien-soy.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/no-puedo-perdonar-a-quien-me-hirio': () => import('./palabras-senor/no-puedo-perdonar-a-quien-me-hirio.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/no-se-administrar-lo-que-tengo': () => import('./palabras-senor/no-se-administrar-lo-que-tengo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/no-se-cual-es-mi-proposito': () => import('./palabras-senor/no-se-cual-es-mi-proposito.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/no-se-que-camino-elegir': () => import('./palabras-senor/no-se-que-camino-elegir.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/no-tengo-tiempo-para-dios': () => import('./palabras-senor/no-tengo-tiempo-para-dios.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/nunca-me-parece-suficiente': () => import('./palabras-senor/nunca-me-parece-suficiente.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/odio-mi-trabajo': () => import('./palabras-senor/odio-mi-trabajo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/oro-y-parece-que-dios-no-responde': () => import('./palabras-senor/oro-y-parece-que-dios-no-responde.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/peleamos-todo-el-tiempo': () => import('./palabras-senor/peleamos-todo-el-tiempo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/perdi-un-embarazo': () => import('./palabras-senor/perdi-un-embarazo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/pienso-en-mudarme-o-emigrar': () => import('./palabras-senor/pienso-en-mudarme-o-emigrar.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/pienso-que-ya-no-hay-salida': () => import('./palabras-senor/pienso-que-ya-no-hay-salida.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/pierdo-el-control-con-la-comida-o-las': () => import('./palabras-senor/pierdo-el-control-con-la-comida-o-las.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/pierdo-el-trabajo': () => import('./palabras-senor/pierdo-el-trabajo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/quiero-dar-pero-tengo-poco': () => import('./palabras-senor/quiero-dar-pero-tengo-poco.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/quiero-empezar-algo-nuevo': () => import('./palabras-senor/quiero-empezar-algo-nuevo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/quiero-ensenar-la-fe-a-mis-hijos': () => import('./palabras-senor/quiero-ensenar-la-fe-a-mis-hijos.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/quiero-hablar-de-jesus-sin-pelear': () => import('./palabras-senor/quiero-hablar-de-jesus-sin-pelear.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/quiero-servir-y-no-se-como': () => import('./palabras-senor/quiero-servir-y-no-se-como.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/quiero-una-fe-verdadera': () => import('./palabras-senor/quiero-una-fe-verdadera.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/recibo-consejos-que-se-contradicen': () => import('./palabras-senor/recibo-consejos-que-se-contradicen.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/se-burlan-de-mi-fe': () => import('./palabras-senor/se-burlan-de-mi-fe.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/se-lo-correcto-pero-no-lo-hago': () => import('./palabras-senor/se-lo-correcto-pero-no-lo-hago.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/siento-envidia': () => import('./palabras-senor/siento-envidia.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/siento-que-me-utilizan': () => import('./palabras-senor/siento-que-me-utilizan.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/sigo-actuando-como-antes': () => import('./palabras-senor/sigo-actuando-como-antes.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/solo-oro-en-los-problemas': () => import('./palabras-senor/solo-oro-en-los-problemas.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/soy-yo-quien-habla-mal-de-otros': () => import('./palabras-senor/soy-yo-quien-habla-mal-de-otros.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/sufro-una-injusticia': () => import('./palabras-senor/sufro-una-injusticia.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/sufro-y-no-entiendo-por-que': () => import('./palabras-senor/sufro-y-no-entiendo-por-que.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/temo-por-mi-futuro-economico': () => import('./palabras-senor/temo-por-mi-futuro-economico.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/tengo-dudas-sobre-dios': () => import('./palabras-senor/tengo-dudas-sobre-dios.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/tengo-miedo-de-volver-a-intentarlo': () => import('./palabras-senor/tengo-miedo-de-volver-a-intentarlo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/tengo-que-confrontar-a-alguien': () => import('./palabras-senor/tengo-que-confrontar-a-alguien.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/tengo-que-tomar-una-decision-importante': () => import('./palabras-senor/tengo-que-tomar-una-decision-importante.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/una-adiccion-me-domina': () => import('./palabras-senor/una-adiccion-me-domina.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/una-amistad-me-aleja-de-dios': () => import('./palabras-senor/una-amistad-me-aleja-de-dios.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/una-puerta-se-cierra': () => import('./palabras-senor/una-puerta-se-cierra.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/vivo-con-miedo': () => import('./palabras-senor/vivo-con-miedo.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/vivo-endeudado': () => import('./palabras-senor/vivo-endeudado.json').then((m) => m.default as unknown as GuiaLeccion),
  'palabras-senor/vivo-lejos-de-mi-familia': () => import('./palabras-senor/vivo-lejos-de-mi-familia.json').then((m) => m.default as unknown as GuiaLeccion),
}
