// Generated by content-src/guias/build-guias.mjs — do not edit by hand.
import type { GuiaIndice, GuiaLeccion } from './types'

export const GUIA_SECCIONES: Record<string, GuiaIndice['secciones']> = {}

/** "<guia>/<lesson id>" → the written lesson. */
export const GUIA_LECCIONES: Record<string, () => Promise<GuiaLeccion>> = {

}
