// Generated by content-src/guias/build-guias.mjs — do not edit by hand.
// The lessons' texts live in content-private/guias and come from /api/content (members only).
import { fetchContent } from '../fetch-content'
import type { GuiaIndice, GuiaLeccion } from './types'

export const GUIA_SECCIONES: Record<string, GuiaIndice['secciones']> = {
  "mandamientos": [
    {
      "id": "antes-de-empezar",
      "titulo": "Antes de empezar",
      "lecciones": [
        {
          "id": "comienza-aqui",
          "titulo": "Comienza aquí: un Dios que primero libera",
          "subtitulo": "Éxodo 20:2"
        },
        {
          "id": "dos-maneras-de-contarlos",
          "titulo": "¿Por qué hay dos maneras de contarlos?",
          "subtitulo": "Evangélicos y católicos: el mismo texto de Dios"
        }
      ]
    },
    {
      "id": "los-diez-mandamientos",
      "titulo": "Los Diez Mandamientos",
      "lecciones": [
        {
          "id": "solo-dios-primer-lugar",
          "titulo": "Solo Dios en el primer lugar",
          "subtitulo": "Evangélico: 1.º · Católico: 1.º"
        },
        {
          "id": "adorar-solo-a-dios",
          "titulo": "Adorar solo a Dios",
          "subtitulo": "Evangélico: 2.º · Católico: parte del 1.º"
        },
        {
          "id": "nombre-de-dios-santo",
          "titulo": "El nombre de Dios es santo",
          "subtitulo": "Evangélico: 3.º · Católico: 2.º"
        },
        {
          "id": "dia-para-dios-y-descansar",
          "titulo": "Un día para Dios y para descansar",
          "subtitulo": "Evangélico: 4.º · Católico: 3.º"
        },
        {
          "id": "honra-padre-y-madre",
          "titulo": "Honra a tu padre y a tu madre",
          "subtitulo": "Evangélico: 5.º · Católico: 4.º"
        },
        {
          "id": "cuidar-la-vida",
          "titulo": "Cuidar la vida",
          "subtitulo": "Evangélico: 6.º · Católico: 5.º"
        },
        {
          "id": "fidelidad-y-pureza",
          "titulo": "Fidelidad y pureza",
          "subtitulo": "Evangélico: 7.º · Católico: 6.º"
        },
        {
          "id": "lo-que-es-de-otro",
          "titulo": "Lo que es de otro, es de otro",
          "subtitulo": "Evangélico: 8.º · Católico: 7.º"
        },
        {
          "id": "hablar-con-la-verdad",
          "titulo": "Hablar con la verdad",
          "subtitulo": "Evangélico: 9.º · Católico: 8.º"
        },
        {
          "id": "corazon-contento",
          "titulo": "Un corazón contento",
          "subtitulo": "Evangélico: 10.º · Católico: 9.º y 10.º"
        }
      ]
    },
    {
      "id": "el-gran-mandamiento",
      "titulo": "El gran mandamiento",
      "lecciones": [
        {
          "id": "amar-a-dios-y-al-projimo",
          "titulo": "Amar a Dios y amar al prójimo",
          "subtitulo": "Mateo 22:36-40"
        },
        {
          "id": "repaso-final",
          "titulo": "Repaso final",
          "subtitulo": "Quiz de diez preguntas y «Los 10 en tus manos»"
        }
      ]
    }
  ],
  "milagros-jesus": [
    {
      "id": "comienzos",
      "titulo": "Los comienzos",
      "lecciones": [
        {
          "id": "bodas-de-cana",
          "titulo": "El agua que se volvió vino",
          "subtitulo": "Juan 2:1-11"
        },
        {
          "id": "hijo-del-oficial-del-rey",
          "titulo": "El hijo del oficial del rey",
          "subtitulo": "Juan 4:46-54"
        }
      ]
    },
    {
      "id": "galilea",
      "titulo": "El gran ministerio en Galilea",
      "lecciones": [
        {
          "id": "primera-pesca-milagrosa",
          "titulo": "La primera pesca milagrosa",
          "subtitulo": "Lucas 5:1-11"
        },
        {
          "id": "sinagoga-de-capernaum",
          "titulo": "El hombre de la sinagoga de Capernaúm",
          "subtitulo": "Marcos 1:21-28"
        },
        {
          "id": "suegra-de-pedro",
          "titulo": "La suegra de Pedro",
          "subtitulo": "Marcos 1:29-31"
        },
        {
          "id": "al-caer-la-tarde",
          "titulo": "Al caer la tarde, sanaba a todos",
          "subtitulo": "Marcos 1:32-34"
        },
        {
          "id": "el-leproso",
          "titulo": "El leproso: «Quiero, sé limpio»",
          "subtitulo": "Marcos 1:40-45"
        },
        {
          "id": "paralitico-del-techo",
          "titulo": "El paralítico que bajaron por el techo",
          "subtitulo": "Marcos 2:1-12"
        },
        {
          "id": "paralitico-de-betesda",
          "titulo": "El paralítico del estanque de Betesda",
          "subtitulo": "Juan 5:1-15"
        },
        {
          "id": "mano-seca",
          "titulo": "El hombre de la mano seca",
          "subtitulo": "Marcos 3:1-6"
        },
        {
          "id": "siervo-del-centurion",
          "titulo": "El siervo del centurión",
          "subtitulo": "Lucas 7:1-10"
        },
        {
          "id": "hijo-de-la-viuda-de-nain",
          "titulo": "El hijo de la viuda de Naín",
          "subtitulo": "Lucas 7:11-17"
        },
        {
          "id": "no-veia-ni-hablaba",
          "titulo": "El hombre que no veía ni hablaba",
          "subtitulo": "Mateo 12:22-23"
        },
        {
          "id": "calma-la-tempestad",
          "titulo": "Jesús calma la tempestad",
          "subtitulo": "Marcos 4:35-41"
        },
        {
          "id": "hombre-de-gadara",
          "titulo": "El hombre de Gadara",
          "subtitulo": "Marcos 5:1-20"
        },
        {
          "id": "mujer-que-toco-su-manto",
          "titulo": "La mujer que tocó su manto",
          "subtitulo": "Marcos 5:25-34"
        },
        {
          "id": "hija-de-jairo",
          "titulo": "La hija de Jairo: «Talita cumi»",
          "subtitulo": "Marcos 5:35-43"
        },
        {
          "id": "dos-ciegos",
          "titulo": "Dos ciegos que lo seguían",
          "subtitulo": "Mateo 9:27-31"
        },
        {
          "id": "mudo-que-volvio-a-hablar",
          "titulo": "El mudo que volvió a hablar",
          "subtitulo": "Mateo 9:32-34"
        }
      ]
    },
    {
      "id": "tierras-vecinas",
      "titulo": "Panes, mar y tierras vecinas",
      "lecciones": [
        {
          "id": "cinco-mil",
          "titulo": "Cinco panes y dos peces",
          "subtitulo": "Juan 6:1-14"
        },
        {
          "id": "camina-sobre-el-agua",
          "titulo": "Jesús camina sobre el agua",
          "subtitulo": "Mateo 14:22-33"
        },
        {
          "id": "en-genesaret",
          "titulo": "En Genesaret, tocaban su manto",
          "subtitulo": "Marcos 6:53-56"
        },
        {
          "id": "mujer-cananea",
          "titulo": "La fe de la mujer cananea",
          "subtitulo": "Marcos 7:24-30"
        },
        {
          "id": "efata",
          "titulo": "«Efata»: el sordo que hablaba mal",
          "subtitulo": "Marcos 7:31-37"
        },
        {
          "id": "cuatro-mil",
          "titulo": "Siete panes para cuatro mil",
          "subtitulo": "Marcos 8:1-10"
        },
        {
          "id": "ciego-de-betsaida",
          "titulo": "El ciego de Betsaida, poco a poco",
          "subtitulo": "Marcos 8:22-26"
        },
        {
          "id": "transfiguracion",
          "titulo": "La Transfiguración",
          "subtitulo": "Lucas 9:28-36"
        },
        {
          "id": "muchacho-al-pie-del-monte",
          "titulo": "El muchacho que el padre trajo",
          "subtitulo": "Marcos 9:14-29"
        },
        {
          "id": "moneda-en-el-pez",
          "titulo": "La moneda en la boca del pez",
          "subtitulo": "Mateo 17:24-27"
        }
      ]
    },
    {
      "id": "camino-jerusalen",
      "titulo": "Camino a Jerusalén",
      "lecciones": [
        {
          "id": "ciego-de-nacimiento",
          "titulo": "El ciego de nacimiento",
          "subtitulo": "Juan 9:1-41"
        },
        {
          "id": "mujer-encorvada",
          "titulo": "La mujer encorvada",
          "subtitulo": "Lucas 13:10-17"
        },
        {
          "id": "hidropesia",
          "titulo": "El hombre hinchado (hidropesía)",
          "subtitulo": "Lucas 14:1-6"
        },
        {
          "id": "lazaro",
          "titulo": "Lázaro, ¡sal fuera!",
          "subtitulo": "Juan 11:1-44"
        },
        {
          "id": "diez-leprosos",
          "titulo": "Los diez leprosos y el que volvió",
          "subtitulo": "Lucas 17:11-19"
        },
        {
          "id": "bartimeo",
          "titulo": "Bartimeo y los ciegos de Jericó",
          "subtitulo": "Marcos 10:46-52"
        }
      ]
    },
    {
      "id": "ultima-semana",
      "titulo": "La última semana y la victoria",
      "lecciones": [
        {
          "id": "higuera-sin-fruto",
          "titulo": "La higuera sin fruto",
          "subtitulo": "Mateo 21:18-22"
        },
        {
          "id": "ciegos-y-cojos-en-el-templo",
          "titulo": "Ciegos y cojos en el templo",
          "subtitulo": "Mateo 21:14"
        },
        {
          "id": "yo-soy-getsemani",
          "titulo": "«Yo soy»: los soldados caen en tierra",
          "subtitulo": "Juan 18:4-6"
        },
        {
          "id": "oreja-de-malco",
          "titulo": "La oreja de Malco",
          "subtitulo": "Lucas 22:49-51"
        },
        {
          "id": "senales-en-la-cruz",
          "titulo": "Señales en la cruz",
          "subtitulo": "Mateo 27:45-54"
        },
        {
          "id": "ha-resucitado",
          "titulo": "¡Ha resucitado!",
          "subtitulo": "Mateo 28:1-10"
        },
        {
          "id": "segunda-pesca",
          "titulo": "La segunda pesca: 153 peces",
          "subtitulo": "Juan 21:1-14"
        },
        {
          "id": "ascension",
          "titulo": "La Ascensión",
          "subtitulo": "Lucas 24:50-53"
        }
      ]
    }
  ],
  "mujeres-virtuosas": [
    {
      "id": "introduccion",
      "titulo": "Introducción",
      "lecciones": [
        {
          "id": "comienza-aqui",
          "titulo": "Comienza aquí",
          "subtitulo": "Qué significa «virtuosa» y cómo usar esta guía"
        },
        {
          "id": "guia-para-grupos",
          "titulo": "Cómo usar esta guía en grupo",
          "subtitulo": "Un encuentro de 45 minutos, paso a paso"
        }
      ]
    },
    {
      "id": "comienzos-y-patriarcas",
      "titulo": "Los comienzos y los patriarcas",
      "lecciones": [
        {
          "id": "eva",
          "titulo": "Eva",
          "subtitulo": "La madre de todos los vivientes"
        },
        {
          "id": "sara",
          "titulo": "Sara",
          "subtitulo": "La que se rió y vio la promesa"
        },
        {
          "id": "agar",
          "titulo": "Agar",
          "subtitulo": "La que fue vista por Dios"
        },
        {
          "id": "rebeca",
          "titulo": "Rebeca",
          "subtitulo": "La joven que dijo «Sí, iré»"
        },
        {
          "id": "lea",
          "titulo": "Lea",
          "subtitulo": "La menos amada, a quien Dios miró"
        },
        {
          "id": "raquel",
          "titulo": "Raquel",
          "subtitulo": "La que esperó un hijo con lágrimas"
        }
      ]
    },
    {
      "id": "egipto-y-desierto",
      "titulo": "Egipto y el desierto",
      "lecciones": [
        {
          "id": "sifra-y-fua",
          "titulo": "Sifra y Fúa",
          "subtitulo": "Las parteras valientes"
        },
        {
          "id": "jocabed",
          "titulo": "Jocabed",
          "subtitulo": "La madre que confió el cesto"
        },
        {
          "id": "miriam",
          "titulo": "Miriam",
          "subtitulo": "La que cantó junto al mar"
        },
        {
          "id": "hijas-de-zelofehad",
          "titulo": "Las hijas de Zelofehad",
          "subtitulo": "Cinco hermanas que pidieron su herencia"
        }
      ]
    },
    {
      "id": "tierra-prometida-y-jueces",
      "titulo": "La tierra prometida y los jueces",
      "lecciones": [
        {
          "id": "rahab",
          "titulo": "Rahab",
          "subtitulo": "La del cordón de grana"
        },
        {
          "id": "debora",
          "titulo": "Débora (y Jael)",
          "subtitulo": "Madre en Israel"
        },
        {
          "id": "noemi",
          "titulo": "Noemí",
          "subtitulo": "De la amargura a la alegría"
        },
        {
          "id": "rut",
          "titulo": "Rut",
          "subtitulo": "La moabita que eligió quedarse"
        },
        {
          "id": "ana-madre-de-samuel",
          "titulo": "Ana, la madre de Samuel",
          "subtitulo": "La que derramó su alma ante Dios"
        }
      ]
    },
    {
      "id": "reyes-y-profetas",
      "titulo": "Reyes y profetas",
      "lecciones": [
        {
          "id": "abigail",
          "titulo": "Abigail",
          "subtitulo": "La que detuvo una venganza"
        },
        {
          "id": "viuda-de-sarepta",
          "titulo": "La viuda de Sarepta",
          "subtitulo": "Harina y aceite que no se acabaron"
        },
        {
          "id": "sunamita",
          "titulo": "La sunamita",
          "subtitulo": "Un cuarto para el profeta"
        },
        {
          "id": "nina-de-naaman",
          "titulo": "La niña de la casa de Naamán",
          "subtitulo": "Una niña que habló de esperanza"
        },
        {
          "id": "hulda",
          "titulo": "Hulda",
          "subtitulo": "La profetisa del rey Josías"
        }
      ]
    },
    {
      "id": "exilio-y-regreso",
      "titulo": "Exilio y regreso",
      "lecciones": [
        {
          "id": "ester",
          "titulo": "Ester",
          "subtitulo": "Para esta hora"
        }
      ]
    },
    {
      "id": "evangelios",
      "titulo": "Los evangelios",
      "lecciones": [
        {
          "id": "elisabet",
          "titulo": "Elisabet",
          "subtitulo": "La que esperó hasta la vejez"
        },
        {
          "id": "maria-madre-de-jesus",
          "titulo": "María, la madre de Jesús",
          "subtitulo": "La que dijo sí a Dios"
        },
        {
          "id": "ana-la-profetisa",
          "titulo": "Ana, la profetisa",
          "subtitulo": "La que esperaba en el templo"
        },
        {
          "id": "mujer-samaritana",
          "titulo": "La mujer samaritana",
          "subtitulo": "El encuentro junto al pozo"
        },
        {
          "id": "mujer-que-toco-su-manto",
          "titulo": "La mujer que tocó su manto",
          "subtitulo": "Doce años de espera, un toque de fe"
        },
        {
          "id": "mujer-que-ungio-sus-pies",
          "titulo": "La mujer perdonada",
          "subtitulo": "La que ungió los pies de Jesús"
        },
        {
          "id": "juana-susana-y-otras",
          "titulo": "Juana, Susana y las que servían",
          "subtitulo": "Mujeres que seguían y sostenían a Jesús"
        },
        {
          "id": "mujer-cananea",
          "titulo": "La mujer cananea",
          "subtitulo": "La fe que insistió"
        },
        {
          "id": "marta-de-betania",
          "titulo": "Marta de Betania",
          "subtitulo": "La que sirvió y creyó"
        },
        {
          "id": "maria-de-betania",
          "titulo": "María de Betania",
          "subtitulo": "La que se sentó a los pies de Jesús"
        },
        {
          "id": "viuda-de-las-dos-blancas",
          "titulo": "La viuda de las dos blancas",
          "subtitulo": "La que dio todo lo que tenía"
        },
        {
          "id": "maria-magdalena",
          "titulo": "María Magdalena",
          "subtitulo": "La primera testigo de la resurrección"
        }
      ]
    },
    {
      "id": "iglesia-naciente",
      "titulo": "La iglesia naciente",
      "lecciones": [
        {
          "id": "tabita",
          "titulo": "Tabita (Dorcas)",
          "subtitulo": "Manos llenas de bien"
        },
        {
          "id": "rode",
          "titulo": "Rode",
          "subtitulo": "La muchacha que oyó llamar"
        },
        {
          "id": "lidia",
          "titulo": "Lidia",
          "subtitulo": "Un corazón abierto"
        },
        {
          "id": "priscila",
          "titulo": "Priscila",
          "subtitulo": "Con Aquila, al servicio del Evangelio"
        },
        {
          "id": "febe",
          "titulo": "Febe",
          "subtitulo": "La que llevó la carta a los Romanos"
        },
        {
          "id": "loida-y-eunice",
          "titulo": "Loida y Eunice",
          "subtitulo": "La fe de abuela a nieto"
        }
      ]
    },
    {
      "id": "para-cerrar",
      "titulo": "Para cerrar",
      "lecciones": [
        {
          "id": "genealogia-de-jesus",
          "titulo": "Las mujeres en la genealogía de Jesús",
          "subtitulo": "Tamar, Rahab, Rut, Betsabé y María"
        },
        {
          "id": "mujer-virtuosa-proverbios-31",
          "titulo": "La mujer virtuosa de Proverbios 31",
          "subtitulo": "Un retrato, no una lista"
        }
      ]
    }
  ],
  "biografias": [
    {
      "id": "comienza-aqui",
      "titulo": "Comienza aquí",
      "lecciones": [
        {
          "id": "comienza-aqui",
          "titulo": "Comienza aquí",
          "subtitulo": "Cómo leer las fichas: Biblia y tradición"
        },
        {
          "id": "quien-es-quien",
          "titulo": "Quién es quién",
          "subtitulo": "Simones, Santiagos, Judas, Josés y otros nombres repetidos"
        },
        {
          "id": "listas-de-los-doce",
          "titulo": "Las listas de los Doce",
          "subtitulo": "Las cuatro listas y sus nombres, lado a lado"
        },
        {
          "id": "linea-del-tiempo",
          "titulo": "Línea del tiempo de los personajes",
          "subtitulo": "Del Edén a la Iglesia naciente"
        }
      ]
    },
    {
      "id": "los-doce",
      "titulo": "Los Doce",
      "lecciones": [
        {
          "id": "pedro",
          "titulo": "Pedro",
          "subtitulo": "El pescador que cayó y fue restaurado"
        },
        {
          "id": "andres",
          "titulo": "Andrés",
          "subtitulo": "El hermano que llevó a Pedro a Jesús"
        },
        {
          "id": "santiago-hijo-de-zebedeo",
          "titulo": "Santiago, hijo de Zebedeo",
          "subtitulo": "En la RVR1960, Jacobo; hermano de Juan"
        },
        {
          "id": "juan",
          "titulo": "Juan",
          "subtitulo": "El discípulo a quien Jesús amaba"
        },
        {
          "id": "felipe",
          "titulo": "Felipe",
          "subtitulo": "El de Betsaida que dijo: «Ven y ve»"
        },
        {
          "id": "bartolome",
          "titulo": "Bartolomé",
          "subtitulo": "También llamado Natanael"
        },
        {
          "id": "tomas",
          "titulo": "Tomás",
          "subtitulo": "El que dijo: «¡Señor mío, y Dios mío!»"
        },
        {
          "id": "mateo",
          "titulo": "Mateo",
          "subtitulo": "El cobrador de impuestos, también llamado Leví"
        },
        {
          "id": "santiago-hijo-de-alfeo",
          "titulo": "Santiago, hijo de Alfeo",
          "subtitulo": "En la RVR1960, Jacobo"
        },
        {
          "id": "judas-tadeo",
          "titulo": "Judas Tadeo",
          "subtitulo": "También Lebeo o «Judas hermano de Jacobo»"
        },
        {
          "id": "simon-el-zelote",
          "titulo": "Simón el Zelote",
          "subtitulo": "En la RVR1960, Simón el cananista"
        },
        {
          "id": "judas-iscariote",
          "titulo": "Judas Iscariote",
          "subtitulo": "El que entregó a Jesús"
        },
        {
          "id": "matias",
          "titulo": "Matías",
          "subtitulo": "El elegido para completar a los Doce"
        }
      ]
    },
    {
      "id": "alrededor-de-jesus",
      "titulo": "Alrededor de Jesús",
      "lecciones": [
        {
          "id": "jose-de-nazaret",
          "titulo": "José de Nazaret",
          "subtitulo": "El hombre justo que cuidó a Jesús"
        },
        {
          "id": "zacarias",
          "titulo": "Zacarías",
          "subtitulo": "El sacerdote, padre de Juan el Bautista"
        },
        {
          "id": "juan-el-bautista",
          "titulo": "Juan el Bautista",
          "subtitulo": "La voz que preparó el camino"
        },
        {
          "id": "simeon-del-templo",
          "titulo": "Simeón",
          "subtitulo": "El anciano que tomó al niño en brazos"
        },
        {
          "id": "lazaro",
          "titulo": "Lázaro de Betania",
          "subtitulo": "El amigo de Jesús"
        },
        {
          "id": "nicodemo",
          "titulo": "Nicodemo",
          "subtitulo": "El maestro que vino de noche"
        },
        {
          "id": "jose-de-arimatea",
          "titulo": "José de Arimatea",
          "subtitulo": "El que dio su sepulcro a Jesús"
        },
        {
          "id": "zaqueo",
          "titulo": "Zaqueo",
          "subtitulo": "El cobrador que bajó del árbol"
        }
      ]
    },
    {
      "id": "iglesia-naciente",
      "titulo": "La Iglesia naciente",
      "lecciones": [
        {
          "id": "pablo",
          "titulo": "Pablo",
          "subtitulo": "De perseguidor a apóstol de las naciones"
        },
        {
          "id": "bernabe",
          "titulo": "Bernabé",
          "subtitulo": "El hijo de consolación"
        },
        {
          "id": "esteban",
          "titulo": "Esteban",
          "subtitulo": "El primer mártir de la Iglesia"
        },
        {
          "id": "felipe-el-evangelista",
          "titulo": "Felipe el evangelista",
          "subtitulo": "Uno de los siete, el que habló al etíope"
        },
        {
          "id": "santiago-hermano-del-senor",
          "titulo": "Santiago, hermano del Señor",
          "subtitulo": "Líder de la iglesia de Jerusalén"
        },
        {
          "id": "juan-marcos",
          "titulo": "Juan Marcos",
          "subtitulo": "El que volvió a ser útil"
        },
        {
          "id": "lucas",
          "titulo": "Lucas",
          "subtitulo": "El médico amado que escribió dos libros"
        },
        {
          "id": "silas",
          "titulo": "Silas",
          "subtitulo": "Compañero de Pablo, cantando en la cárcel"
        },
        {
          "id": "timoteo",
          "titulo": "Timoteo",
          "subtitulo": "El joven hijo en la fe de Pablo"
        },
        {
          "id": "cornelio",
          "titulo": "Cornelio",
          "subtitulo": "El centurión romano que abrió la puerta"
        }
      ]
    },
    {
      "id": "antiguo-testamento",
      "titulo": "Antiguo Testamento",
      "lecciones": [
        {
          "id": "adan",
          "titulo": "Adán",
          "subtitulo": "El primer hombre"
        },
        {
          "id": "noe",
          "titulo": "Noé",
          "subtitulo": "El que construyó el arca"
        },
        {
          "id": "abraham",
          "titulo": "Abraham",
          "subtitulo": "El padre de la fe"
        },
        {
          "id": "isaac",
          "titulo": "Isaac",
          "subtitulo": "El hijo de la promesa"
        },
        {
          "id": "jacob",
          "titulo": "Jacob",
          "subtitulo": "El que luchó y fue llamado Israel"
        },
        {
          "id": "jose-hijo-de-jacob",
          "titulo": "José, hijo de Jacob",
          "subtitulo": "De esclavo a gobernador de Egipto"
        },
        {
          "id": "job",
          "titulo": "Job",
          "subtitulo": "Fiel en medio del dolor"
        },
        {
          "id": "moises",
          "titulo": "Moisés",
          "subtitulo": "El que sacó a Israel de Egipto"
        },
        {
          "id": "josue",
          "titulo": "Josué",
          "subtitulo": "El que guió al pueblo a la tierra prometida"
        },
        {
          "id": "gedeon",
          "titulo": "Gedeón",
          "subtitulo": "El más pequeño, con trescientos hombres"
        },
        {
          "id": "sanson",
          "titulo": "Sansón",
          "subtitulo": "Una fuerza que venía de Dios"
        },
        {
          "id": "samuel",
          "titulo": "Samuel",
          "subtitulo": "El niño que escuchó a Dios"
        },
        {
          "id": "saul",
          "titulo": "Saúl",
          "subtitulo": "El primer rey de Israel"
        },
        {
          "id": "david",
          "titulo": "David",
          "subtitulo": "El pastor que llegó a ser rey"
        },
        {
          "id": "salomon",
          "titulo": "Salomón",
          "subtitulo": "El rey que pidió sabiduría"
        },
        {
          "id": "elias",
          "titulo": "Elías",
          "subtitulo": "El profeta del fuego y del silbo apacible"
        },
        {
          "id": "eliseo",
          "titulo": "Eliseo",
          "subtitulo": "El que recibió el manto de Elías"
        },
        {
          "id": "jonas",
          "titulo": "Jonás",
          "subtitulo": "El profeta que huyó y volvió"
        },
        {
          "id": "isaias",
          "titulo": "Isaías",
          "subtitulo": "El profeta que anunció al Mesías"
        },
        {
          "id": "jeremias",
          "titulo": "Jeremías",
          "subtitulo": "El profeta de las lágrimas y la esperanza"
        },
        {
          "id": "daniel",
          "titulo": "Daniel",
          "subtitulo": "Fiel a Dios en Babilonia"
        },
        {
          "id": "esdras-y-nehemias",
          "titulo": "Esdras y Nehemías",
          "subtitulo": "Reconstruir la Ley y los muros"
        }
      ]
    }
  ],
  "caminando-gigantes": [
    {
      "id": "comienza-aqui",
      "titulo": "Comienza aquí",
      "lecciones": [
        {
          "id": "comienza-aqui",
          "titulo": "Cómo usar esta biblioteca",
          "subtitulo": "Cuatro pasos cuando llega una lucha"
        },
        {
          "id": "que-estas-viviendo",
          "titulo": "¿Qué estás viviendo hoy?",
          "subtitulo": "Busca tu lucha y encuentra a tu gigante"
        }
      ]
    },
    {
      "id": "injusticia-y-espera",
      "titulo": "Injusticia y espera",
      "lecciones": [
        {
          "id": "jose",
          "titulo": "José",
          "subtitulo": "Cuando hacer todo bien no evita el sufrimiento"
        },
        {
          "id": "david-perseguido",
          "titulo": "David, perseguido",
          "subtitulo": "Cuando te atacan sin motivo, una y otra vez"
        },
        {
          "id": "abraham",
          "titulo": "Abraham",
          "subtitulo": "Cuando la promesa tarda años en llegar"
        },
        {
          "id": "ana",
          "titulo": "Ana",
          "subtitulo": "Cuando tu dolor es invisible para los demás"
        }
      ]
    },
    {
      "id": "perdida-y-duelo",
      "titulo": "Pérdida y duelo",
      "lecciones": [
        {
          "id": "job",
          "titulo": "Job",
          "subtitulo": "Cuando no hay respuestas"
        },
        {
          "id": "noemi",
          "titulo": "Noemí",
          "subtitulo": "Cuando la amargura quiere ser tu nombre"
        },
        {
          "id": "marta-y-maria",
          "titulo": "Marta y María",
          "subtitulo": "Cuando Jesús parece llegar tarde"
        },
        {
          "id": "jeremias-lamentaciones",
          "titulo": "Jeremías, entre ruinas",
          "subtitulo": "Cuando el dolor es profundo y no termina"
        }
      ]
    },
    {
      "id": "miedo-y-llamado",
      "titulo": "Miedo, inseguridad y llamado",
      "lecciones": [
        {
          "id": "moises",
          "titulo": "Moisés",
          "subtitulo": "Cuando tu pasado quiere descalificarte"
        },
        {
          "id": "gedeon",
          "titulo": "Gedeón",
          "subtitulo": "Cuando te sientes demasiado pequeño"
        },
        {
          "id": "jeremias",
          "titulo": "Jeremías",
          "subtitulo": "Cuando nadie te escucha ni te entiende"
        },
        {
          "id": "timoteo",
          "titulo": "Timoteo",
          "subtitulo": "Cuando eres joven, tímido y te toca liderar"
        },
        {
          "id": "ester",
          "titulo": "Ester",
          "subtitulo": "Cuando callar es más peligroso que hablar"
        }
      ]
    },
    {
      "id": "cansancio-y-soledad",
      "titulo": "Cansancio y soledad",
      "lecciones": [
        {
          "id": "elias",
          "titulo": "Elías",
          "subtitulo": "Cuando ya no puedes más"
        },
        {
          "id": "agar",
          "titulo": "Agar",
          "subtitulo": "Cuando te sientes abandonado en el desierto"
        }
      ]
    },
    {
      "id": "culpa-y-nuevo-comienzo",
      "titulo": "Culpa, caída y nuevo comienzo",
      "lecciones": [
        {
          "id": "david-caida",
          "titulo": "David, después de caer",
          "subtitulo": "Cuando el corazón baja la guardia"
        },
        {
          "id": "pedro",
          "titulo": "Pedro",
          "subtitulo": "Cuando fallas en el momento más importante"
        },
        {
          "id": "sanson",
          "titulo": "Sansón",
          "subtitulo": "Cuando el don corre más rápido que el carácter"
        },
        {
          "id": "jonas",
          "titulo": "Jonás",
          "subtitulo": "Cuando huyes de lo que Dios te pidió"
        },
        {
          "id": "zaqueo",
          "titulo": "Zaqueo",
          "subtitulo": "Cuando todos te juzgan por tu pasado"
        },
        {
          "id": "la-samaritana",
          "titulo": "La mujer samaritana",
          "subtitulo": "Cuando cargas una historia que te avergüenza"
        }
      ]
    },
    {
      "id": "familia-y-relaciones",
      "titulo": "Familia y relaciones",
      "lecciones": [
        {
          "id": "jacob-y-esau",
          "titulo": "Jacob y Esaú",
          "subtitulo": "Cuando una pelea de familia dura años"
        },
        {
          "id": "rut",
          "titulo": "Rut",
          "subtitulo": "Cuando eliges quedarte y ser fiel"
        },
        {
          "id": "abigail",
          "titulo": "Abigail",
          "subtitulo": "Cuando te toca poner paz en medio del conflicto"
        }
      ]
    },
    {
      "id": "fe-bajo-presion",
      "titulo": "Fe bajo presión",
      "lecciones": [
        {
          "id": "daniel",
          "titulo": "Daniel",
          "subtitulo": "Cuando ser fiel pone tu vida en riesgo"
        },
        {
          "id": "tres-jovenes",
          "titulo": "Sadrac, Mesac y Abed-nego",
          "subtitulo": "Cuando todos se arrodillan y tú no"
        },
        {
          "id": "pablo",
          "titulo": "Pablo",
          "subtitulo": "Cuando obedecer trae problemas constantes"
        },
        {
          "id": "esteban",
          "titulo": "Esteban",
          "subtitulo": "Cuando la fidelidad lo cuesta todo"
        }
      ]
    },
    {
      "id": "enfermedad-y-limites",
      "titulo": "Enfermedad y límites",
      "lecciones": [
        {
          "id": "la-mujer-que-toco-el-manto",
          "titulo": "La mujer que tocó el manto",
          "subtitulo": "Cuando llevas años enfermo y cansado"
        },
        {
          "id": "naaman",
          "titulo": "Naamán",
          "subtitulo": "Cuando el orgullo se interpone en tu sanidad"
        }
      ]
    },
    {
      "id": "el-gigante-mayor",
      "titulo": "El Gigante mayor",
      "lecciones": [
        {
          "id": "jesus",
          "titulo": "Jesús en Getsemaní",
          "subtitulo": "Cuando obedecer significa entregarlo todo"
        },
        {
          "id": "tu-caminas-con-gigantes",
          "titulo": "Tú caminas con gigantes",
          "subtitulo": "No fueron perfectos: fueron fieles en el dolor"
        }
      ]
    }
  ],
  "palabras-senor": [
    {
      "id": "comienza-aqui",
      "titulo": "Comienza aquí",
      "lecciones": [
        {
          "id": "como-usar-esta-guia",
          "titulo": "Cómo usar esta guía",
          "subtitulo": "Siete pasos para vivir la Palabra"
        }
      ]
    },
    {
      "id": "perdon-y-heridas",
      "titulo": "Perdón y heridas",
      "lecciones": [
        {
          "id": "no-puedo-perdonar-a-quien-me-hirio",
          "titulo": "Cuando no puedo perdonar a quien me hirió"
        },
        {
          "id": "no-logro-perdonarme-a-mi-mismo",
          "titulo": "Cuando no logro perdonarme a mí mismo"
        },
        {
          "id": "me-piden-perdon-y-no-se-si-creerles",
          "titulo": "Cuando me piden perdón y no sé si creerles"
        },
        {
          "id": "necesito-pedir-perdon",
          "titulo": "Cuando necesito pedir perdón"
        },
        {
          "id": "el-rencor-vuelve-una-y-otra-vez",
          "titulo": "Cuando el rencor vuelve una y otra vez"
        },
        {
          "id": "me-traiciona-alguien-cercano",
          "titulo": "Cuando me traiciona alguien cercano"
        },
        {
          "id": "cargo-heridas-de-mi-infancia",
          "titulo": "Cuando cargo heridas de mi infancia"
        },
        {
          "id": "me-hirieron-en-la-iglesia",
          "titulo": "Cuando me hirieron en la iglesia"
        }
      ]
    },
    {
      "id": "emociones",
      "titulo": "Emociones",
      "lecciones": [
        {
          "id": "la-ira-me-domina",
          "titulo": "Cuando la ira me domina"
        },
        {
          "id": "la-ansiedad-no-me-deja-en-paz",
          "titulo": "Cuando la ansiedad no me deja en paz"
        },
        {
          "id": "vivo-con-miedo",
          "titulo": "Cuando vivo con miedo"
        },
        {
          "id": "la-tristeza-no-se-va",
          "titulo": "Cuando la tristeza no se va"
        },
        {
          "id": "creo-que-tengo-depresion",
          "titulo": "Cuando creo que tengo depresión"
        },
        {
          "id": "estoy-agotado-por-dentro",
          "titulo": "Cuando estoy agotado por dentro"
        },
        {
          "id": "siento-envidia",
          "titulo": "Cuando siento envidia"
        },
        {
          "id": "los-celos-me-quitan-la-paz",
          "titulo": "Cuando los celos me quitan la paz"
        }
      ]
    },
    {
      "id": "identidad",
      "titulo": "Identidad y autoestima",
      "lecciones": [
        {
          "id": "no-me-gusta-quien-soy",
          "titulo": "Cuando no me gusta quien soy"
        },
        {
          "id": "me-siento-incapaz",
          "titulo": "Cuando me siento incapaz"
        },
        {
          "id": "me-comparo-con-los-demas",
          "titulo": "Cuando me comparo con los demás"
        },
        {
          "id": "me-rechazan-o-me-abandonan",
          "titulo": "Cuando me rechazan o me abandonan"
        },
        {
          "id": "cometo-el-mismo-error-otra-vez",
          "titulo": "Cuando cometo el mismo error otra vez"
        },
        {
          "id": "me-siento-vacio",
          "titulo": "Cuando me siento vacío"
        },
        {
          "id": "me-siento-solo",
          "titulo": "Cuando me siento solo"
        },
        {
          "id": "necesito-que-todos-me-aprueben",
          "titulo": "Cuando necesito que todos me aprueben"
        }
      ]
    },
    {
      "id": "pareja",
      "titulo": "Matrimonio y pareja",
      "lecciones": [
        {
          "id": "peleamos-todo-el-tiempo",
          "titulo": "Cuando peleamos todo el tiempo"
        },
        {
          "id": "el-amor-parece-enfriarse",
          "titulo": "Cuando el amor parece enfriarse"
        },
        {
          "id": "mi-pareja-no-comparte-mi-fe",
          "titulo": "Cuando mi pareja no comparte mi fe"
        },
        {
          "id": "hubo-infidelidad",
          "titulo": "Cuando hubo infidelidad"
        },
        {
          "id": "el-dinero-nos-divide",
          "titulo": "Cuando el dinero nos divide"
        },
        {
          "id": "busco-pareja-y-quiero-elegir-bien",
          "titulo": "Cuando busco pareja y quiero elegir bien"
        },
        {
          "id": "estoy-soltero-y-espero",
          "titulo": "Cuando estoy soltero y espero"
        },
        {
          "id": "la-tentacion-amenaza-mi-matrimonio",
          "titulo": "Cuando la tentación amenaza mi matrimonio"
        }
      ]
    },
    {
      "id": "familia",
      "titulo": "Hijos y familia",
      "lecciones": [
        {
          "id": "mi-hijo-se-aleja-o-se-rebela",
          "titulo": "Cuando mi hijo se aleja o se rebela"
        },
        {
          "id": "quiero-ensenar-la-fe-a-mis-hijos",
          "titulo": "Cuando quiero enseñar la fe a mis hijos"
        },
        {
          "id": "mis-padres-son-dificiles",
          "titulo": "Cuando mis padres son difíciles"
        },
        {
          "id": "mi-familia-no-entiende-mi-fe",
          "titulo": "Cuando mi familia no entiende mi fe"
        },
        {
          "id": "hay-peleas-constantes-en-casa",
          "titulo": "Cuando hay peleas constantes en casa"
        },
        {
          "id": "necesito-poner-limites",
          "titulo": "Cuando necesito poner límites"
        },
        {
          "id": "cuido-a-mis-padres-ancianos",
          "titulo": "Cuando cuido a mis padres ancianos"
        },
        {
          "id": "vivo-lejos-de-mi-familia",
          "titulo": "Cuando vivo lejos de mi familia"
        }
      ]
    },
    {
      "id": "amistades",
      "titulo": "Amistades y convivencia",
      "lecciones": [
        {
          "id": "una-amistad-me-aleja-de-dios",
          "titulo": "Cuando una amistad me aleja de Dios"
        },
        {
          "id": "tengo-que-confrontar-a-alguien",
          "titulo": "Cuando tengo que confrontar a alguien"
        },
        {
          "id": "siento-que-me-utilizan",
          "titulo": "Cuando siento que me utilizan"
        },
        {
          "id": "hablan-mal-de-mi",
          "titulo": "Cuando hablan mal de mí"
        },
        {
          "id": "soy-yo-quien-habla-mal-de-otros",
          "titulo": "Cuando soy yo quien habla mal de otros"
        },
        {
          "id": "convivo-con-alguien-dificil",
          "titulo": "Cuando convivo con alguien difícil"
        },
        {
          "id": "me-cuesta-hacer-amigos",
          "titulo": "Cuando me cuesta hacer amigos"
        },
        {
          "id": "las-redes-sociales-me-roban-la-paz",
          "titulo": "Cuando las redes sociales me roban la paz"
        }
      ]
    },
    {
      "id": "trabajo",
      "titulo": "Trabajo y propósito",
      "lecciones": [
        {
          "id": "odio-mi-trabajo",
          "titulo": "Cuando odio mi trabajo"
        },
        {
          "id": "mi-jefe-es-injusto",
          "titulo": "Cuando mi jefe es injusto"
        },
        {
          "id": "pierdo-el-trabajo",
          "titulo": "Cuando pierdo el trabajo"
        },
        {
          "id": "fracaso-en-lo-que-emprendo",
          "titulo": "Cuando fracaso en lo que emprendo"
        },
        {
          "id": "no-se-cual-es-mi-proposito",
          "titulo": "Cuando no sé cuál es mi propósito"
        },
        {
          "id": "me-siento-estancado",
          "titulo": "Cuando me siento estancado"
        },
        {
          "id": "tengo-miedo-de-volver-a-intentarlo",
          "titulo": "Cuando tengo miedo de volver a intentarlo"
        },
        {
          "id": "me-piden-hacer-algo-incorrecto",
          "titulo": "Cuando me piden hacer algo incorrecto"
        }
      ]
    },
    {
      "id": "dinero",
      "titulo": "Dinero y provisión",
      "lecciones": [
        {
          "id": "el-dinero-no-alcanza",
          "titulo": "Cuando el dinero no alcanza"
        },
        {
          "id": "vivo-endeudado",
          "titulo": "Cuando vivo endeudado"
        },
        {
          "id": "temo-por-mi-futuro-economico",
          "titulo": "Cuando temo por mi futuro económico"
        },
        {
          "id": "me-va-bien-y-me-alejo-de-dios",
          "titulo": "Cuando me va bien y me alejo de Dios"
        },
        {
          "id": "no-se-administrar-lo-que-tengo",
          "titulo": "Cuando no sé administrar lo que tengo"
        },
        {
          "id": "quiero-dar-pero-tengo-poco",
          "titulo": "Cuando quiero dar pero tengo poco"
        },
        {
          "id": "me-tienta-el-dinero-facil",
          "titulo": "Cuando me tienta el dinero fácil"
        },
        {
          "id": "nunca-me-parece-suficiente",
          "titulo": "Cuando nunca me parece suficiente"
        }
      ]
    },
    {
      "id": "decisiones",
      "titulo": "Decisiones y dirección",
      "lecciones": [
        {
          "id": "tengo-que-tomar-una-decision-importante",
          "titulo": "Cuando tengo que tomar una decisión importante"
        },
        {
          "id": "no-se-que-camino-elegir",
          "titulo": "Cuando no sé qué camino elegir"
        },
        {
          "id": "una-puerta-se-cierra",
          "titulo": "Cuando una puerta se cierra"
        },
        {
          "id": "me-toca-esperar",
          "titulo": "Cuando me toca esperar"
        },
        {
          "id": "pienso-en-mudarme-o-emigrar",
          "titulo": "Cuando pienso en mudarme o emigrar"
        },
        {
          "id": "quiero-empezar-algo-nuevo",
          "titulo": "Cuando quiero empezar algo nuevo"
        },
        {
          "id": "recibo-consejos-que-se-contradicen",
          "titulo": "Cuando recibo consejos que se contradicen"
        },
        {
          "id": "me-presionan-para-decidir-ya",
          "titulo": "Cuando me presionan para decidir ya"
        }
      ]
    },
    {
      "id": "fe",
      "titulo": "Fe y vida espiritual",
      "lecciones": [
        {
          "id": "oro-y-parece-que-dios-no-responde",
          "titulo": "Cuando oro y parece que Dios no responde"
        },
        {
          "id": "mi-fe-esta-debil",
          "titulo": "Cuando mi fe está débil"
        },
        {
          "id": "me-siento-lejos-de-dios",
          "titulo": "Cuando me siento lejos de Dios"
        },
        {
          "id": "solo-oro-en-los-problemas",
          "titulo": "Cuando solo oro en los problemas"
        },
        {
          "id": "tengo-dudas-sobre-dios",
          "titulo": "Cuando tengo dudas sobre Dios"
        },
        {
          "id": "no-tengo-tiempo-para-dios",
          "titulo": "Cuando no tengo tiempo para Dios"
        },
        {
          "id": "me-cuesta-leer-la-biblia",
          "titulo": "Cuando me cuesta leer la Biblia"
        },
        {
          "id": "me-canso-del-camino-cristiano",
          "titulo": "Cuando me canso del camino cristiano"
        }
      ]
    },
    {
      "id": "tentacion",
      "titulo": "Tentación y hábitos",
      "lecciones": [
        {
          "id": "lucho-con-un-pecado-oculto",
          "titulo": "Cuando lucho con un pecado oculto"
        },
        {
          "id": "caigo-siempre-en-la-misma-tentacion",
          "titulo": "Cuando caigo siempre en la misma tentación"
        },
        {
          "id": "me-siento-sucio-por-dentro",
          "titulo": "Cuando me siento sucio por dentro"
        },
        {
          "id": "justifico-lo-que-se-que-esta-mal",
          "titulo": "Cuando justifico lo que sé que está mal"
        },
        {
          "id": "una-adiccion-me-domina",
          "titulo": "Cuando una adicción me domina"
        },
        {
          "id": "pierdo-el-control-con-la-comida-o-las",
          "titulo": "Cuando pierdo el control con la comida o las compras"
        },
        {
          "id": "la-pereza-me-gana",
          "titulo": "Cuando la pereza me gana"
        },
        {
          "id": "me-descubro-mintiendo",
          "titulo": "Cuando me descubro mintiendo"
        }
      ]
    },
    {
      "id": "dolor",
      "titulo": "Dolor, enfermedad y pérdida",
      "lecciones": [
        {
          "id": "muere-alguien-que-amo",
          "titulo": "Cuando muere alguien que amo"
        },
        {
          "id": "estoy-enfermo-hace-mucho-tiempo",
          "titulo": "Cuando estoy enfermo hace mucho tiempo"
        },
        {
          "id": "alguien-que-amo-esta-enfermo",
          "titulo": "Cuando alguien que amo está enfermo"
        },
        {
          "id": "perdi-un-embarazo",
          "titulo": "Cuando perdí un embarazo"
        },
        {
          "id": "envejezco-y-me-siento-inutil",
          "titulo": "Cuando envejezco y me siento inútil"
        },
        {
          "id": "sufro-una-injusticia",
          "titulo": "Cuando sufro una injusticia"
        },
        {
          "id": "sufro-y-no-entiendo-por-que",
          "titulo": "Cuando sufro y no entiendo por qué"
        },
        {
          "id": "pienso-que-ya-no-hay-salida",
          "titulo": "Cuando pienso que ya no hay salida"
        }
      ]
    },
    {
      "id": "hacedor",
      "titulo": "Vivir como hacedor de la Palabra",
      "lecciones": [
        {
          "id": "se-lo-correcto-pero-no-lo-hago",
          "titulo": "Cuando sé lo correcto pero no lo hago"
        },
        {
          "id": "sigo-actuando-como-antes",
          "titulo": "Cuando sigo actuando como antes"
        },
        {
          "id": "me-siento-hipocrita",
          "titulo": "Cuando me siento hipócrita"
        },
        {
          "id": "se-burlan-de-mi-fe",
          "titulo": "Cuando se burlan de mi fe"
        },
        {
          "id": "me-da-verguenza-mi-fe",
          "titulo": "Cuando me da vergüenza mi fe"
        },
        {
          "id": "quiero-servir-y-no-se-como",
          "titulo": "Cuando quiero servir y no sé cómo"
        },
        {
          "id": "quiero-hablar-de-jesus-sin-pelear",
          "titulo": "Cuando quiero hablar de Jesús sin pelear"
        },
        {
          "id": "quiero-una-fe-verdadera",
          "titulo": "Cuando quiero una fe verdadera"
        }
      ]
    },
    {
      "id": "cierre",
      "titulo": "Cierre",
      "lecciones": [
        {
          "id": "hacedores-de-la-palabra",
          "titulo": "Hacedores de la Palabra",
          "subtitulo": "Quien oye entiende; quien practica se transforma"
        }
      ]
    }
  ]
}

/** "<guia>/<lesson id>" of every written lesson. */
export const GUIA_LECCIONES: ReadonlySet<string> = new Set([
  "mandamientos/adorar-solo-a-dios",
  "mandamientos/amar-a-dios-y-al-projimo",
  "mandamientos/comienza-aqui",
  "mandamientos/corazon-contento",
  "mandamientos/cuidar-la-vida",
  "mandamientos/dia-para-dios-y-descansar",
  "mandamientos/dos-maneras-de-contarlos",
  "mandamientos/fidelidad-y-pureza",
  "mandamientos/hablar-con-la-verdad",
  "mandamientos/honra-padre-y-madre",
  "mandamientos/lo-que-es-de-otro",
  "mandamientos/nombre-de-dios-santo",
  "mandamientos/repaso-final",
  "mandamientos/solo-dios-primer-lugar",
  "milagros-jesus/al-caer-la-tarde",
  "milagros-jesus/ascension",
  "milagros-jesus/bartimeo",
  "milagros-jesus/bodas-de-cana",
  "milagros-jesus/calma-la-tempestad",
  "milagros-jesus/camina-sobre-el-agua",
  "milagros-jesus/ciego-de-betsaida",
  "milagros-jesus/ciego-de-nacimiento",
  "milagros-jesus/ciegos-y-cojos-en-el-templo",
  "milagros-jesus/cinco-mil",
  "milagros-jesus/cuatro-mil",
  "milagros-jesus/diez-leprosos",
  "milagros-jesus/dos-ciegos",
  "milagros-jesus/efata",
  "milagros-jesus/el-leproso",
  "milagros-jesus/en-genesaret",
  "milagros-jesus/ha-resucitado",
  "milagros-jesus/hidropesia",
  "milagros-jesus/higuera-sin-fruto",
  "milagros-jesus/hija-de-jairo",
  "milagros-jesus/hijo-de-la-viuda-de-nain",
  "milagros-jesus/hijo-del-oficial-del-rey",
  "milagros-jesus/hombre-de-gadara",
  "milagros-jesus/lazaro",
  "milagros-jesus/mano-seca",
  "milagros-jesus/moneda-en-el-pez",
  "milagros-jesus/muchacho-al-pie-del-monte",
  "milagros-jesus/mudo-que-volvio-a-hablar",
  "milagros-jesus/mujer-cananea",
  "milagros-jesus/mujer-encorvada",
  "milagros-jesus/mujer-que-toco-su-manto",
  "milagros-jesus/no-veia-ni-hablaba",
  "milagros-jesus/oreja-de-malco",
  "milagros-jesus/paralitico-de-betesda",
  "milagros-jesus/paralitico-del-techo",
  "milagros-jesus/primera-pesca-milagrosa",
  "milagros-jesus/segunda-pesca",
  "milagros-jesus/senales-en-la-cruz",
  "milagros-jesus/siervo-del-centurion",
  "milagros-jesus/sinagoga-de-capernaum",
  "milagros-jesus/suegra-de-pedro",
  "milagros-jesus/transfiguracion",
  "milagros-jesus/yo-soy-getsemani",
  "mujeres-virtuosas/abigail",
  "mujeres-virtuosas/agar",
  "mujeres-virtuosas/ana-la-profetisa",
  "mujeres-virtuosas/ana-madre-de-samuel",
  "mujeres-virtuosas/comienza-aqui",
  "mujeres-virtuosas/debora",
  "mujeres-virtuosas/elisabet",
  "mujeres-virtuosas/ester",
  "mujeres-virtuosas/eva",
  "mujeres-virtuosas/febe",
  "mujeres-virtuosas/genealogia-de-jesus",
  "mujeres-virtuosas/guia-para-grupos",
  "mujeres-virtuosas/hijas-de-zelofehad",
  "mujeres-virtuosas/hulda",
  "mujeres-virtuosas/jocabed",
  "mujeres-virtuosas/juana-susana-y-otras",
  "mujeres-virtuosas/lea",
  "mujeres-virtuosas/lidia",
  "mujeres-virtuosas/loida-y-eunice",
  "mujeres-virtuosas/maria-de-betania",
  "mujeres-virtuosas/maria-madre-de-jesus",
  "mujeres-virtuosas/maria-magdalena",
  "mujeres-virtuosas/marta-de-betania",
  "mujeres-virtuosas/miriam",
  "mujeres-virtuosas/mujer-cananea",
  "mujeres-virtuosas/mujer-que-toco-su-manto",
  "mujeres-virtuosas/mujer-que-ungio-sus-pies",
  "mujeres-virtuosas/mujer-samaritana",
  "mujeres-virtuosas/mujer-virtuosa-proverbios-31",
  "mujeres-virtuosas/nina-de-naaman",
  "mujeres-virtuosas/noemi",
  "mujeres-virtuosas/priscila",
  "mujeres-virtuosas/rahab",
  "mujeres-virtuosas/raquel",
  "mujeres-virtuosas/rebeca",
  "mujeres-virtuosas/rode",
  "mujeres-virtuosas/rut",
  "mujeres-virtuosas/sara",
  "mujeres-virtuosas/sifra-y-fua",
  "mujeres-virtuosas/sunamita",
  "mujeres-virtuosas/tabita",
  "mujeres-virtuosas/viuda-de-las-dos-blancas",
  "mujeres-virtuosas/viuda-de-sarepta",
  "biografias/abraham",
  "biografias/adan",
  "biografias/andres",
  "biografias/bartolome",
  "biografias/bernabe",
  "biografias/comienza-aqui",
  "biografias/cornelio",
  "biografias/daniel",
  "biografias/david",
  "biografias/elias",
  "biografias/eliseo",
  "biografias/esdras-y-nehemias",
  "biografias/esteban",
  "biografias/felipe-el-evangelista",
  "biografias/felipe",
  "biografias/gedeon",
  "biografias/isaac",
  "biografias/isaias",
  "biografias/jacob",
  "biografias/jeremias",
  "biografias/job",
  "biografias/jonas",
  "biografias/jose-de-arimatea",
  "biografias/jose-de-nazaret",
  "biografias/jose-hijo-de-jacob",
  "biografias/josue",
  "biografias/juan-el-bautista",
  "biografias/juan-marcos",
  "biografias/juan",
  "biografias/judas-iscariote",
  "biografias/judas-tadeo",
  "biografias/lazaro",
  "biografias/linea-del-tiempo",
  "biografias/listas-de-los-doce",
  "biografias/lucas",
  "biografias/mateo",
  "biografias/matias",
  "biografias/moises",
  "biografias/nicodemo",
  "biografias/noe",
  "biografias/pablo",
  "biografias/pedro",
  "biografias/quien-es-quien",
  "biografias/salomon",
  "biografias/samuel",
  "biografias/sanson",
  "biografias/santiago-hermano-del-senor",
  "biografias/santiago-hijo-de-alfeo",
  "biografias/santiago-hijo-de-zebedeo",
  "biografias/saul",
  "biografias/silas",
  "biografias/simeon-del-templo",
  "biografias/simon-el-zelote",
  "biografias/timoteo",
  "biografias/tomas",
  "biografias/zacarias",
  "biografias/zaqueo",
  "caminando-gigantes/abigail",
  "caminando-gigantes/abraham",
  "caminando-gigantes/agar",
  "caminando-gigantes/ana",
  "caminando-gigantes/comienza-aqui",
  "caminando-gigantes/daniel",
  "caminando-gigantes/david-caida",
  "caminando-gigantes/david-perseguido",
  "caminando-gigantes/elias",
  "caminando-gigantes/esteban",
  "caminando-gigantes/ester",
  "caminando-gigantes/gedeon",
  "caminando-gigantes/jacob-y-esau",
  "caminando-gigantes/jeremias-lamentaciones",
  "caminando-gigantes/jeremias",
  "caminando-gigantes/jesus",
  "caminando-gigantes/job",
  "caminando-gigantes/jonas",
  "caminando-gigantes/jose",
  "caminando-gigantes/la-mujer-que-toco-el-manto",
  "caminando-gigantes/la-samaritana",
  "caminando-gigantes/marta-y-maria",
  "caminando-gigantes/moises",
  "caminando-gigantes/naaman",
  "caminando-gigantes/noemi",
  "caminando-gigantes/pablo",
  "caminando-gigantes/pedro",
  "caminando-gigantes/que-estas-viviendo",
  "caminando-gigantes/rut",
  "caminando-gigantes/sanson",
  "caminando-gigantes/timoteo",
  "caminando-gigantes/tres-jovenes",
  "caminando-gigantes/tu-caminas-con-gigantes",
  "caminando-gigantes/zaqueo",
  "palabras-senor/alguien-que-amo-esta-enfermo",
  "palabras-senor/busco-pareja-y-quiero-elegir-bien",
  "palabras-senor/caigo-siempre-en-la-misma-tentacion",
  "palabras-senor/cargo-heridas-de-mi-infancia",
  "palabras-senor/cometo-el-mismo-error-otra-vez",
  "palabras-senor/como-usar-esta-guia",
  "palabras-senor/convivo-con-alguien-dificil",
  "palabras-senor/creo-que-tengo-depresion",
  "palabras-senor/cuido-a-mis-padres-ancianos",
  "palabras-senor/el-amor-parece-enfriarse",
  "palabras-senor/el-dinero-no-alcanza",
  "palabras-senor/el-dinero-nos-divide",
  "palabras-senor/el-rencor-vuelve-una-y-otra-vez",
  "palabras-senor/envejezco-y-me-siento-inutil",
  "palabras-senor/estoy-agotado-por-dentro",
  "palabras-senor/estoy-enfermo-hace-mucho-tiempo",
  "palabras-senor/estoy-soltero-y-espero",
  "palabras-senor/fracaso-en-lo-que-emprendo",
  "palabras-senor/hablan-mal-de-mi",
  "palabras-senor/hacedores-de-la-palabra",
  "palabras-senor/hay-peleas-constantes-en-casa",
  "palabras-senor/hubo-infidelidad",
  "palabras-senor/justifico-lo-que-se-que-esta-mal",
  "palabras-senor/la-ansiedad-no-me-deja-en-paz",
  "palabras-senor/la-ira-me-domina",
  "palabras-senor/la-pereza-me-gana",
  "palabras-senor/la-tentacion-amenaza-mi-matrimonio",
  "palabras-senor/la-tristeza-no-se-va",
  "palabras-senor/las-redes-sociales-me-roban-la-paz",
  "palabras-senor/los-celos-me-quitan-la-paz",
  "palabras-senor/lucho-con-un-pecado-oculto",
  "palabras-senor/me-canso-del-camino-cristiano",
  "palabras-senor/me-comparo-con-los-demas",
  "palabras-senor/me-cuesta-hacer-amigos",
  "palabras-senor/me-cuesta-leer-la-biblia",
  "palabras-senor/me-da-verguenza-mi-fe",
  "palabras-senor/me-descubro-mintiendo",
  "palabras-senor/me-hirieron-en-la-iglesia",
  "palabras-senor/me-piden-hacer-algo-incorrecto",
  "palabras-senor/me-piden-perdon-y-no-se-si-creerles",
  "palabras-senor/me-presionan-para-decidir-ya",
  "palabras-senor/me-rechazan-o-me-abandonan",
  "palabras-senor/me-siento-estancado",
  "palabras-senor/me-siento-hipocrita",
  "palabras-senor/me-siento-incapaz",
  "palabras-senor/me-siento-lejos-de-dios",
  "palabras-senor/me-siento-solo",
  "palabras-senor/me-siento-sucio-por-dentro",
  "palabras-senor/me-siento-vacio",
  "palabras-senor/me-tienta-el-dinero-facil",
  "palabras-senor/me-toca-esperar",
  "palabras-senor/me-traiciona-alguien-cercano",
  "palabras-senor/me-va-bien-y-me-alejo-de-dios",
  "palabras-senor/mi-familia-no-entiende-mi-fe",
  "palabras-senor/mi-fe-esta-debil",
  "palabras-senor/mi-hijo-se-aleja-o-se-rebela",
  "palabras-senor/mi-jefe-es-injusto",
  "palabras-senor/mi-pareja-no-comparte-mi-fe",
  "palabras-senor/mis-padres-son-dificiles",
  "palabras-senor/muere-alguien-que-amo",
  "palabras-senor/necesito-pedir-perdon",
  "palabras-senor/necesito-poner-limites",
  "palabras-senor/necesito-que-todos-me-aprueben",
  "palabras-senor/no-logro-perdonarme-a-mi-mismo",
  "palabras-senor/no-me-gusta-quien-soy",
  "palabras-senor/no-puedo-perdonar-a-quien-me-hirio",
  "palabras-senor/no-se-administrar-lo-que-tengo",
  "palabras-senor/no-se-cual-es-mi-proposito",
  "palabras-senor/no-se-que-camino-elegir",
  "palabras-senor/no-tengo-tiempo-para-dios",
  "palabras-senor/nunca-me-parece-suficiente",
  "palabras-senor/odio-mi-trabajo",
  "palabras-senor/oro-y-parece-que-dios-no-responde",
  "palabras-senor/peleamos-todo-el-tiempo",
  "palabras-senor/perdi-un-embarazo",
  "palabras-senor/pienso-en-mudarme-o-emigrar",
  "palabras-senor/pienso-que-ya-no-hay-salida",
  "palabras-senor/pierdo-el-control-con-la-comida-o-las",
  "palabras-senor/pierdo-el-trabajo",
  "palabras-senor/quiero-dar-pero-tengo-poco",
  "palabras-senor/quiero-empezar-algo-nuevo",
  "palabras-senor/quiero-ensenar-la-fe-a-mis-hijos",
  "palabras-senor/quiero-hablar-de-jesus-sin-pelear",
  "palabras-senor/quiero-servir-y-no-se-como",
  "palabras-senor/quiero-una-fe-verdadera",
  "palabras-senor/recibo-consejos-que-se-contradicen",
  "palabras-senor/se-burlan-de-mi-fe",
  "palabras-senor/se-lo-correcto-pero-no-lo-hago",
  "palabras-senor/siento-envidia",
  "palabras-senor/siento-que-me-utilizan",
  "palabras-senor/sigo-actuando-como-antes",
  "palabras-senor/solo-oro-en-los-problemas",
  "palabras-senor/soy-yo-quien-habla-mal-de-otros",
  "palabras-senor/sufro-una-injusticia",
  "palabras-senor/sufro-y-no-entiendo-por-que",
  "palabras-senor/temo-por-mi-futuro-economico",
  "palabras-senor/tengo-dudas-sobre-dios",
  "palabras-senor/tengo-miedo-de-volver-a-intentarlo",
  "palabras-senor/tengo-que-confrontar-a-alguien",
  "palabras-senor/tengo-que-tomar-una-decision-importante",
  "palabras-senor/una-adiccion-me-domina",
  "palabras-senor/una-amistad-me-aleja-de-dios",
  "palabras-senor/una-puerta-se-cierra",
  "palabras-senor/vivo-con-miedo",
  "palabras-senor/vivo-endeudado",
  "palabras-senor/vivo-lejos-de-mi-familia"
])

/** A written lesson ("<guia>/<lesson id>"); null when it is not written yet. */
export function loadGuiaLeccion(key: string): Promise<GuiaLeccion | null> {
  return GUIA_LECCIONES.has(key) ? fetchContent<GuiaLeccion>(`guias/${key}`) : Promise.resolve(null)
}
