// Generated: the name of each day of the 90-day plans (the full texts load on demand).
export type PlanId = 'transformacion' | 'vivir-como-jesus' | 'nueva-mentalidad'

export const PLAN_TITLES: Record<PlanId, string[]> = {
  "transformacion": [
    "Un comienzo honesto",
    "Amado antes de cambiar",
    "Un lugar de encuentro",
    "Hablar como hijo",
    "La oración de una frase",
    "Una lámpara para hoy",
    "Primer descanso",
    "Escuchar, no solo hablar",
    "Rumiar un versículo",
    "Gracias antes de pedir",
    "Dios en lo cotidiano",
    "Traerle lo que pesa",
    "Piedras de memoria",
    "Misericordia cada mañana",
    "Orar con los Salmos",
    "Adorar quién es Él",
    "Pedir con confianza",
    "Orar por otros",
    "Cuando faltan palabras",
    "Guardar la Palabra",
    "La Palabra no vuelve vacía",
    "Leer para obedecer",
    "Una Palabra que ve",
    "Orar la Escritura",
    "Esperar la respuesta",
    "Orar en casa",
    "Dormir en paz",
    "Gozo en su presencia",
    "Amor primero",
    "El examen de la noche",
    "Confesar con nombre",
    "Sin condenación",
    "Un corazón nuevo",
    "Dar la vuelta",
    "La alegría del perdonado",
    "Lejos como el oriente",
    "La gracia que enseña",
    "No luchar solo",
    "El bien que pospuse",
    "Siempre hay salida",
    "Vestirse de Cristo",
    "Blanco como la nieve",
    "Soltar el control",
    "No mi voluntad",
    "Mitad del camino",
    "Echar la carga",
    "En medio del fuego",
    "Lamentar también es orar",
    "Estar quietos",
    "Recordar para confiar",
    "Fuerzas para esperar",
    "Él teje lo bueno",
    "Bástate mi gracia",
    "Acompañado en el valle",
    "La prueba que madura",
    "Su paz te guarda",
    "Permanecer en la vid",
    "El fruto del Espíritu",
    "Fiel en lo poco",
    "Una pausa en el Espíritu",
    "Gozo que fortalece",
    "Vestidos de bondad",
    "Dios produce el querer",
    "Un ayuno sencillo",
    "Diez minutos de silencio",
    "Tu cuerpo, su templo",
    "Cuidar lo que miro",
    "Amor que se nota",
    "Humilde ante tu Dios",
    "Verdes y con fruto",
    "Gratitud que adora",
    "Fruto de labios",
    "Tus dones para otros",
    "Servir en lo escondido",
    "Llevar cargas",
    "Animarnos unos a otros",
    "Perseverar juntos",
    "Contar lo que hizo",
    "Orar juntos",
    "Consolar con lo recibido",
    "A mí lo hicisteis",
    "Razón de tu esperanza",
    "Toda la vida, ofrenda",
    "Qué bueno es juntos",
    "Los ojos en Jesús",
    "No te canses",
    "Tu regla de vida",
    "Oraciones respondidas",
    "Grandes cosas ha hecho",
    "De gloria en gloria"
  ],
  "vivir-como-jesus": [
    "Jesús te llama hoy",
    "Aprender de Él",
    "Oír y hacer",
    "Lo más importante",
    "Mirar con compasión",
    "Tocar al que nadie toca",
    "Descansar con Jesús",
    "Los pequeños importan",
    "Cruzar la barrera",
    "Aceptar antes del cambio",
    "Gracia primero",
    "Preguntar antes de suponer",
    "Acompañar el dolor",
    "Quedarse con Él",
    "Pobres en espíritu",
    "Los que lloran",
    "La fuerza mansa",
    "Hambre de lo correcto",
    "Misericordia en lo cotidiano",
    "Un corazón limpio",
    "Oír y guardar",
    "Hacer la paz",
    "Cuando hacer el bien cuesta",
    "Sal que da sabor",
    "Luz en casa",
    "Obras que señalan al Padre",
    "Mi bienaventuranza",
    "Unido a la vid",
    "El enojo antes de dormir",
    "Primero reconcíliate",
    "Sí, sí; no, no",
    "La segunda milla",
    "Orar por quien me hiere",
    "Como el sol",
    "Misericordiosos como el Padre",
    "Dar en secreto",
    "Donde está tu tesoro",
    "No juzgar",
    "Mi parte primero",
    "La regla de oro",
    "El fruto en casa",
    "Casa sobre la roca",
    "En lo secreto",
    "Padre nuestro",
    "Venga tu reino",
    "Hágase tu voluntad",
    "Nuestro pan de cada día",
    "Perdonados para perdonar",
    "Enséñanos a orar",
    "Setenta veces siete",
    "La deuda perdonada",
    "Pedir perdón sin excusas",
    "Líbranos del mal",
    "Yo he rogado por ti",
    "La buena parte",
    "Primero el Reino",
    "Movido a misericordia",
    "Ve y haz lo mismo",
    "El padre que corre",
    "El hermano mayor",
    "Buscar a la que falta",
    "Sé propicio a mí",
    "Fruto con perseverancia",
    "Tus dones al servicio",
    "La vida no son las cosas",
    "Dar de lo que tienes",
    "Invitar al que no devuelve",
    "Amar mucho",
    "A mí lo hicisteis",
    "La levadura escondida",
    "Lavar los pies",
    "Grande es el que sirve",
    "El último lugar",
    "Como yo os he amado",
    "Conocidos por el amor",
    "Amigos hasta el final",
    "Un gozo completo",
    "Quedaos conmigo",
    "Sanar en vez de herir",
    "Padre, perdónalos",
    "He ahí tu madre",
    "Llamada por su nombre",
    "Caminar con el desanimado",
    "Corazones que arden",
    "¿Me amas?",
    "Así os envío",
    "Mi regla de vida",
    "Andar como Él anduvo",
    "En paz con todos",
    "Todos los días contigo"
  ],
  "nueva-mentalidad": [
    "Una mente que se renueva",
    "Cuenta tus quejas",
    "Pensamientos con raíz",
    "Detente, nombra, cambia",
    "¿Roba o da vida?",
    "El filtro de Filipenses",
    "Tu primera semana",
    "Mentira y verdad",
    "El primer pensamiento",
    "Lo que miras te llena",
    "Mirar desde arriba",
    "La oración flecha",
    "Quitarse y vestirse",
    "Dios termina lo que empieza",
    "Una nueva criatura",
    "Hijo, no empleado",
    "Sin condenación",
    "Tu pasado no te nombra",
    "Hecho con propósito",
    "Formidable y maravilloso",
    "Cristo vive en mí",
    "Libre de agradar",
    "Cuando te critican",
    "Háblate con gracia",
    "Fuerte en la debilidad",
    "Tus heridas no te nombran",
    "Escogido para brillar",
    "Tu nuevo nombre",
    "Vuelve a contar",
    "Tres gracias al día",
    "De queja a oración",
    "Gracias en lo pequeño",
    "Gracias a las personas",
    "Gracias en días grises",
    "Una semana agradecida",
    "Piedras de memoria",
    "Gratitud en la mesa",
    "El '¿y si…?'",
    "Pedir dando gracias",
    "La paz que vigila",
    "La hoja de cargas",
    "Tercer conteo",
    "Solo por hoy",
    "Mente que se apoya",
    "Cuando la mente no para",
    "Acostarte en paz",
    "Confiar a los tuyos",
    "El león y el oso",
    "Abre la hoja",
    "Vida en la lengua",
    "Lo que llena el corazón",
    "Pronto para oír",
    "Palabras que edifican",
    "La respuesta suave",
    "Háblale a tu alma",
    "Espada o medicina",
    "Bendecir a los tuyos",
    "Etiquetas sobre los hijos",
    "Elogiar en voz alta",
    "Sin leña",
    "Mensajes con gracia",
    "Guarda de mi boca",
    "Otra casa, otras palabras",
    "Tu propio camino",
    "Lo que la foto esconde",
    "Ponerle nombre a la envidia",
    "Alegrarte con otros",
    "El contentamiento se aprende",
    "Cuando tenga eso…",
    "Tu parte es hermosa",
    "La película repetida",
    "Cerrar la libreta",
    "Quitarse la amargura",
    "Deja el enojo",
    "Dios lo encamina a bien",
    "Soltar el lamento propio",
    "Un alma en calma",
    "Una rienda para ti",
    "Más que fuerza de voluntad",
    "El dinero en su lugar",
    "Administrador, no dueño",
    "Trabajar para el Señor",
    "Contar tus días",
    "Obras y pensamientos",
    "Esperanza que se elige",
    "Los pensamientos de Dios",
    "Portador de esperanza",
    "Tus nuevas frases",
    "Mira el camino",
    "Una mente nueva"
  ]
}
