// Gift guides → app files. Validates each guide first; a guide with errors is not published.
//   node content-src/guias/build-guias.mjs
// Writes lib/content/guias/<guia>/<id>.json (the lessons) and lib/content/guias/index.ts
// (sections of every guide + a loader per written lesson).
import fs from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(HERE, '..', '..')
const OUT = path.join(ROOT, 'lib', 'content', 'guias')
const GUIAS = ['mandamientos', 'milagros-jesus', 'mujeres-virtuosas', 'biografias']

const indices = {}
const loaders = []
let blocked = false
for (const guia of GUIAS) {
  const dir = path.join(HERE, guia)
  if (!fs.existsSync(path.join(dir, 'indice.json'))) continue
  const v = spawnSync(process.execPath, [path.join(HERE, 'validar-guia.mjs'), guia], { encoding: 'utf8' })
  const last = v.stdout.trim().split('\n').pop()
  console.log(`${guia}: ${last}`)
  if (v.status !== 0) {
    console.log(v.stdout.split('\n').filter((l) => l.startsWith('✗') || l.startsWith('   -')).slice(0, 12).join('\n'))
    blocked = true
    continue
  }
  const indice = JSON.parse(fs.readFileSync(path.join(dir, 'indice.json'), 'utf8'))
  indices[guia] = indice.secciones
  fs.mkdirSync(path.join(OUT, guia), { recursive: true })
  const ldir = path.join(dir, 'lecciones')
  for (const f of fs.existsSync(ldir) ? fs.readdirSync(ldir).filter((x) => x.endsWith('.json')) : []) {
    fs.copyFileSync(path.join(ldir, f), path.join(OUT, guia, f))
    const id = f.replace(/\.json$/, '')
    loaders.push(`  '${guia}/${id}': () => import('./${guia}/${id}.json').then((m) => m.default as unknown as GuiaLeccion),`)
  }
}

fs.writeFileSync(
  path.join(OUT, 'index.ts'),
  `// Generated by content-src/guias/build-guias.mjs — do not edit by hand.\n` +
    `import type { GuiaIndice, GuiaLeccion } from './types'\n\n` +
    `export const GUIA_SECCIONES: Record<string, GuiaIndice['secciones']> = ${JSON.stringify(indices, null, 2)}\n\n` +
    `/** "<guia>/<lesson id>" → the written lesson. */\n` +
    `export const GUIA_LECCIONES: Record<string, () => Promise<GuiaLeccion>> = {\n${loaders.join('\n')}\n}\n`,
)
console.log(`\nPublicado: ${Object.keys(indices).length} guias, ${loaders.length} lições.`)
if (blocked) {
  console.log('Atenção: pelo menos uma guia foi reprovada e ficou de fora (veja acima).')
  process.exit(1)
}
