// Generated by content-src/ninos/build-ninos.mjs — do not edit by hand.
// The stories live in content-private/ninos and come from /api/content (members only).
import { fetchContent } from '../fetch-content'
import type { HistoriaNinos, NinosIndice } from './types'

export const NINOS_SECCIONES: NinosIndice['secciones'] = [
  {
    "id": "los-comienzos",
    "titulo": "Los comienzos",
    "historias": [
      {
        "id": "dios-crea-el-mundo",
        "titulo": "Dios crea el mundo",
        "referencia": "Génesis 1–2"
      },
      {
        "id": "el-jardin",
        "titulo": "El jardín y la primera desobediencia",
        "referencia": "Génesis 3"
      },
      {
        "id": "noe-y-el-arca",
        "titulo": "Noé y el arca",
        "referencia": "Génesis 6–9"
      },
      {
        "id": "la-torre-de-babel",
        "titulo": "La torre de Babel",
        "referencia": "Génesis 11"
      }
    ]
  },
  {
    "id": "los-patriarcas",
    "titulo": "Los patriarcas",
    "historias": [
      {
        "id": "abraham-y-las-estrellas",
        "titulo": "Abraham cuenta las estrellas",
        "referencia": "Génesis 15"
      },
      {
        "id": "nace-isaac",
        "titulo": "Sara ríe: nace Isaac",
        "referencia": "Génesis 21"
      },
      {
        "id": "la-escalera-de-jacob",
        "titulo": "La escalera de Jacob",
        "referencia": "Génesis 28"
      },
      {
        "id": "la-tunica-de-jose",
        "titulo": "José y su túnica de colores",
        "referencia": "Génesis 37"
      },
      {
        "id": "jose-perdona",
        "titulo": "José perdona a sus hermanos",
        "referencia": "Génesis 45"
      },
      {
        "id": "job-confia",
        "titulo": "Job confía en Dios",
        "referencia": "Job 1–2"
      }
    ]
  },
  {
    "id": "moises-y-el-desierto",
    "titulo": "Moisés y el desierto",
    "historias": [
      {
        "id": "moises-en-la-canasta",
        "titulo": "Moisés en la canasta",
        "referencia": "Éxodo 2"
      },
      {
        "id": "la-zarza",
        "titulo": "La zarza que ardía",
        "referencia": "Éxodo 3"
      },
      {
        "id": "el-mar-rojo",
        "titulo": "El paso del mar Rojo",
        "referencia": "Éxodo 14"
      },
      {
        "id": "el-mana",
        "titulo": "Pan del cielo: el maná",
        "referencia": "Éxodo 16"
      },
      {
        "id": "los-diez-mandamientos",
        "titulo": "Los Diez Mandamientos",
        "referencia": "Éxodo 20"
      }
    ]
  },
  {
    "id": "la-tierra-prometida",
    "titulo": "La tierra prometida",
    "historias": [
      {
        "id": "jerico",
        "titulo": "Las murallas de Jericó",
        "referencia": "Josué 6"
      },
      {
        "id": "gedeon",
        "titulo": "Gedeón y los 300",
        "referencia": "Jueces 7"
      },
      {
        "id": "rut-la-amiga-fiel",
        "titulo": "Rut, la amiga fiel",
        "referencia": "Rut 1"
      }
    ]
  },
  {
    "id": "jueces-y-reyes",
    "titulo": "Jueces y reyes",
    "historias": [
      {
        "id": "ana-ora",
        "titulo": "Ana ora y Dios escucha",
        "referencia": "1 Samuel 1"
      },
      {
        "id": "dios-llama-a-samuel",
        "titulo": "«Habla, Señor»: Dios llama a Samuel",
        "referencia": "1 Samuel 3"
      },
      {
        "id": "david-el-pastorcito",
        "titulo": "David, el pastorcito",
        "referencia": "1 Samuel 16"
      },
      {
        "id": "david-y-goliat",
        "titulo": "David y Goliat",
        "referencia": "1 Samuel 17"
      },
      {
        "id": "salomon-pide-sabiduria",
        "titulo": "Salomón pide sabiduría",
        "referencia": "1 Reyes 3"
      }
    ]
  },
  {
    "id": "los-profetas",
    "titulo": "Los profetas",
    "historias": [
      {
        "id": "elias-y-la-viuda",
        "titulo": "Elías y la viuda de Sarepta",
        "referencia": "1 Reyes 17"
      },
      {
        "id": "jonas-y-el-gran-pez",
        "titulo": "Jonás y el gran pez",
        "referencia": "Jonás 1–4"
      },
      {
        "id": "naaman-y-la-nina",
        "titulo": "Naamán y la niña valiente",
        "referencia": "2 Reyes 5"
      }
    ]
  },
  {
    "id": "exilio-y-regreso",
    "titulo": "Exilio y regreso",
    "historias": [
      {
        "id": "daniel-y-los-leones",
        "titulo": "Daniel y los leones",
        "referencia": "Daniel 6"
      },
      {
        "id": "la-reina-ester",
        "titulo": "La reina Ester",
        "referencia": "Ester 4"
      },
      {
        "id": "nehemias-reconstruye",
        "titulo": "Nehemías reconstruye la muralla",
        "referencia": "Nehemías 2"
      }
    ]
  },
  {
    "id": "jesus-nace",
    "titulo": "Jesús nace",
    "historias": [
      {
        "id": "el-angel-visita-a-maria",
        "titulo": "El ángel visita a María",
        "referencia": "Lucas 1:26-38"
      },
      {
        "id": "jesus-nace-en-belen",
        "titulo": "Jesús nace en Belén",
        "referencia": "Lucas 2:1-7"
      },
      {
        "id": "los-pastores",
        "titulo": "Los pastores y los ángeles",
        "referencia": "Lucas 2:8-20"
      },
      {
        "id": "los-magos",
        "titulo": "Los magos siguen la estrella",
        "referencia": "Mateo 2:1-12"
      },
      {
        "id": "jesus-en-el-templo",
        "titulo": "Jesús, a los 12 años, en el templo",
        "referencia": "Lucas 2:41-52"
      }
    ]
  },
  {
    "id": "jesus-ensena-y-sana",
    "titulo": "Jesús enseña y sana",
    "historias": [
      {
        "id": "el-bautismo-de-jesus",
        "titulo": "El bautismo de Jesús",
        "referencia": "Marcos 1:9-11"
      },
      {
        "id": "pescadores-de-personas",
        "titulo": "Pescadores de personas",
        "referencia": "Lucas 5:1-11"
      },
      {
        "id": "agua-en-vino",
        "titulo": "Agua hecha vino en Caná",
        "referencia": "Juan 2:1-11"
      },
      {
        "id": "jesus-calma-la-tormenta",
        "titulo": "Jesús calma la tormenta",
        "referencia": "Marcos 4:35-41"
      },
      {
        "id": "la-casa-sobre-la-roca",
        "titulo": "La casa sobre la roca",
        "referencia": "Mateo 7:24-27"
      },
      {
        "id": "panes-y-peces",
        "titulo": "El niño de los panes y los peces",
        "referencia": "Juan 6:1-14"
      },
      {
        "id": "el-buen-samaritano",
        "titulo": "El buen samaritano",
        "referencia": "Lucas 10:25-37"
      },
      {
        "id": "la-oveja-perdida",
        "titulo": "La oveja perdida",
        "referencia": "Lucas 15:3-7"
      },
      {
        "id": "el-padre-que-abraza",
        "titulo": "El padre que corre a abrazar",
        "referencia": "Lucas 15:11-32"
      },
      {
        "id": "jesus-bendice-a-los-ninos",
        "titulo": "Jesús bendice a los niños",
        "referencia": "Marcos 10:13-16"
      },
      {
        "id": "bartimeo",
        "titulo": "Bartimeo vuelve a ver",
        "referencia": "Marcos 10:46-52"
      },
      {
        "id": "zaqueo",
        "titulo": "Zaqueo baja del árbol",
        "referencia": "Lucas 19:1-10"
      }
    ]
  },
  {
    "id": "pascua",
    "titulo": "Pascua",
    "historias": [
      {
        "id": "jesus-entra-en-jerusalen",
        "titulo": "Jesús entra en Jerusalén",
        "referencia": "Mateo 21:1-11"
      },
      {
        "id": "jesus-lava-los-pies",
        "titulo": "La última cena: Jesús lava los pies",
        "referencia": "Juan 13:1-17"
      },
      {
        "id": "la-cruz-y-la-tumba-vacia",
        "titulo": "La cruz y la tumba vacía",
        "referencia": "Lucas 24:1-12"
      }
    ]
  },
  {
    "id": "la-iglesia-nace",
    "titulo": "La Iglesia nace",
    "historias": [
      {
        "id": "pentecostes",
        "titulo": "Pentecostés: llega el Espíritu Santo",
        "referencia": "Hechos 2:1-13"
      },
      {
        "id": "pablo-y-silas",
        "titulo": "Pablo y Silas cantan en la cárcel",
        "referencia": "Hechos 16:16-34"
      },
      {
        "id": "cielo-nuevo",
        "titulo": "Un cielo nuevo y una tierra nueva",
        "referencia": "Apocalipsis 21:1-5"
      }
    ]
  }
]

/** Ids of the published stories. */
export const NINOS_HISTORIAS: ReadonlySet<string> = new Set([
  "abraham-y-las-estrellas",
  "agua-en-vino",
  "ana-ora",
  "bartimeo",
  "cielo-nuevo",
  "daniel-y-los-leones",
  "david-el-pastorcito",
  "david-y-goliat",
  "dios-crea-el-mundo",
  "dios-llama-a-samuel",
  "el-angel-visita-a-maria",
  "el-bautismo-de-jesus",
  "el-buen-samaritano",
  "el-jardin",
  "el-mana",
  "el-mar-rojo",
  "el-padre-que-abraza",
  "elias-y-la-viuda",
  "gedeon",
  "jerico",
  "jesus-bendice-a-los-ninos",
  "jesus-calma-la-tormenta",
  "jesus-en-el-templo",
  "jesus-entra-en-jerusalen",
  "jesus-lava-los-pies",
  "jesus-nace-en-belen",
  "job-confia",
  "jonas-y-el-gran-pez",
  "jose-perdona",
  "la-casa-sobre-la-roca",
  "la-cruz-y-la-tumba-vacia",
  "la-escalera-de-jacob",
  "la-oveja-perdida",
  "la-reina-ester",
  "la-torre-de-babel",
  "la-tunica-de-jose",
  "la-zarza",
  "los-diez-mandamientos",
  "los-magos",
  "los-pastores",
  "moises-en-la-canasta",
  "naaman-y-la-nina",
  "nace-isaac",
  "nehemias-reconstruye",
  "noe-y-el-arca",
  "pablo-y-silas",
  "panes-y-peces",
  "pentecostes",
  "pescadores-de-personas",
  "rut-la-amiga-fiel",
  "salomon-pide-sabiduria",
  "zaqueo"
])

/** A published story; null when it is not ready yet. */
export function loadHistoria(id: string): Promise<HistoriaNinos | null> {
  return NINOS_HISTORIAS.has(id) ? fetchContent<HistoriaNinos>(`ninos/${id}`) : Promise.resolve(null)
}
