// Estudio Cronológico → app files (lib/content/estudio). Runs the validator first: a lesson
// with errors is never published.
//   node content-src/estudio/build-estudio.mjs
// Writes:
//   lib/content/estudio/maestra.ts          — eras + the 90 lessons (id, section, title, label, date)
//   content-private/estudio/<id>.json       — each written lesson (served by /api/content to members)
//   lib/content/estudio/lecciones/index.ts  — the ids of the written lessons + their loader
//   lib/content/estudio/glosario.json       — the glossary (tap a word in a lesson)
import fs from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dropLegacyJson, privateDir } from '../private-out.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(HERE, '..', '..')
const OUT = path.join(ROOT, 'lib', 'content', 'estudio')
const SRC_LESSONS = path.join(HERE, 'lecciones')

// 1) Validate everything (master table, glossary, characters, every lesson).
const v = spawnSync(process.execPath, [path.join(HERE, 'validar.mjs')], { encoding: 'utf8' })
process.stdout.write(v.stdout.split('\n').filter((l) => /✗|ERROR|error|errores|OK|lecciones/i.test(l)).slice(-15).join('\n') + '\n')
if (v.status !== 0) {
  console.error('\nO validador reprovou: nada foi publicado. Rode node content-src/estudio/validar.mjs para ver os detalhes.')
  process.exit(1)
}

const maestra = JSON.parse(fs.readFileSync(path.join(HERE, 'maestra.json'), 'utf8'))
fs.mkdirSync(path.join(OUT, 'lecciones'), { recursive: true })

// 2) Master table, trimmed to what the app shows.
const eras = maestra.eras.map((e) => ({ id: e.id, titulo: e.titulo, fechas: e.fechas, frase: e.frase }))
const lecciones = maestra.lecciones.map((l) => ({ id: l.id, seccion: l.seccion, titulo: l.titulo, rotulo: l.rotulo, fecha: l.fecha?.texto ?? null }))
fs.writeFileSync(
  path.join(OUT, 'maestra.ts'),
  `// Generated by content-src/estudio/build-estudio.mjs from maestra.json — do not edit by hand.\n\n` +
    `export interface EstudioEra { id: string; titulo: string; fechas: string | null; frase: string }\n` +
    `export interface EstudioEntrada { id: string; seccion: string; titulo: string; rotulo: string; fecha: string | null }\n\n` +
    `export const ESTUDIO_ERAS: EstudioEra[] = ${JSON.stringify(eras, null, 2)}\n\n` +
    `export const ESTUDIO_LECCIONES: EstudioEntrada[] = ${JSON.stringify(lecciones, null, 2)}\n`,
)

// 3) Written lessons (private, served by /api/content) + their ids and loader.
const ids = new Set(maestra.lecciones.map((l) => l.id))
const written = fs
  .readdirSync(SRC_LESSONS)
  .filter((f) => f.endsWith('.json'))
  .map((f) => f.replace(/\.json$/, ''))
  .filter((id) => ids.has(id))
  .sort((a, b) => maestra.lecciones.findIndex((l) => l.id === a) - maestra.lecciones.findIndex((l) => l.id === b))
const PRIV = privateDir('estudio')
for (const id of written) fs.copyFileSync(path.join(SRC_LESSONS, `${id}.json`), path.join(PRIV, `${id}.json`))
dropLegacyJson(path.join(OUT, 'lecciones'))
fs.writeFileSync(
  path.join(OUT, 'lecciones', 'index.ts'),
  `// Generated by content-src/estudio/build-estudio.mjs — the lessons already written.\n` +
    `// Their texts live in content-private/estudio and come from /api/content (members only).\n` +
    `import { fetchContent } from '../../fetch-content'\n` +
    `import type { Leccion } from '../types'\n\n` +
    `export const LECCIONES_ESCRITAS: ReadonlySet<string> = new Set(${JSON.stringify(written, null, 2)})\n\n` +
    `/** A written lesson; null when it is not written yet. */\n` +
    `export function loadLeccion(id: string): Promise<Leccion | null> {\n` +
    `  return LECCIONES_ESCRITAS.has(id) ? fetchContent<Leccion>(\`estudio/\${id}\`) : Promise.resolve(null)\n` +
    `}\n`,
)

// 4) Glossary.
fs.copyFileSync(path.join(HERE, 'glosario.json'), path.join(OUT, 'glosario.json'))

console.log(`\nPublicado: ${lecciones.length} lições na tabela, ${written.length} escritas (${written.join(', ')}), ${eras.length} seções.`)
